// ERDModel → MySQL DDL. Pure; names already whitelist-validated at the boundary,
// backtick-quoted defensively.

const q = (s) => '`' + s + '`';

function columnDef(name, type, { nullable = false, pk = false, unique = false, defaultValue = null } = {}) {
  const parts = [q(name), type];
  if (!nullable) parts.push('NOT NULL');
  if (pk && /^(INT|BIGINT|TINYINT|SMALLINT)$/.test(type)) parts.push('AUTO_INCREMENT');
  if (unique) parts.push('UNIQUE');
  if (defaultValue) parts.push(`DEFAULT ${q(defaultValue)}`);
  return '  ' + parts.join(' ');
}

// FK placement: 1:N → child (to) holds FK to parent (from). 1:1 → 'to' side.
// N:M → junction table. Referenced table must have a single PK.
export function generateSql(model) {
  const fks = new Map(); // holderEntity -> [{col, type, refTable, refCol, unique}]
  for (const r of model.relationships) {
    if (r.type === 'N:M') continue;
    const parent = model.entities.find((e) => e.name === r.from);
    const pk = parent?.fields.find((f) => f.pk);
    if (!pk) continue; // no PK → skip FK (invalid schema, user fixes in editor)
    if (!fks.has(r.to)) fks.set(r.to, []);
    fks.get(r.to).push({ col: `${r.from}_${pk.name}`, type: pk.type, refTable: r.from, refCol: pk.name, unique: r.type === '1:1' });
  }

  const out = ['-- generated by erd-creator', ''];
  for (const e of model.entities) {
    const lines = e.fields.map((f) => columnDef(f.name, f.type, f));
    for (const k of fks.get(e.name) || []) lines.push(columnDef(k.col, k.type, { unique: k.unique }));
    const pks = e.fields.filter((f) => f.pk).map((f) => q(f.name));
    if (pks.length) lines.push(`  PRIMARY KEY (${pks.join(', ')})`);
    for (const k of fks.get(e.name) || []) {
      lines.push(`  FOREIGN KEY (${q(k.col)}) REFERENCES ${q(k.refTable)} (${q(k.refCol)})`);
    }
    out.push(`CREATE TABLE ${q(e.name)} (`, lines.join(',\n'), ') ENGINE=InnoDB;', '');
  }

  for (const r of model.relationships.filter((x) => x.type === 'N:M')) {
    const a = model.entities.find((e) => e.name === r.from);
    const b = model.entities.find((e) => e.name === r.to);
    const ap = a?.fields.find((f) => f.pk), bp = b?.fields.find((f) => f.pk);
    if (!ap || !bp) continue;
    const ac = `${a.name}_${ap.name}`, bc = `${b.name}_${bp.name}`;
    out.push(
      `CREATE TABLE ${q(`${a.name}_${b.name}`)} (`,
      columnDef(ac, ap.type),
      columnDef(bc, bp.type),
      `  PRIMARY KEY (${q(ac)}, ${q(bc)})`,
      `  CONSTRAINT ${q(`fk_${a.name}_${b.name}_a`)} FOREIGN KEY (${q(ac)}) REFERENCES ${q(a.name)} (${q(ap.name)})`,
      `  CONSTRAINT ${q(`fk_${a.name}_${b.name}_b`)} FOREIGN KEY (${q(bc)}) REFERENCES ${q(b.name)} (${q(bp.name)})`,
      ') ENGINE=InnoDB;',
      '',
    );
  }
  return out.join('\n');
}
