package main

import (
	"strings"
	"testing"
)

// defaultsSample exercises every DEFAULT shape the emitters must carry:
// a quoted string, a bare keyword/function, a numeric literal, and an
// expression wrapped in parens. The table carries a comment too, so the
// table-comment round-trip is pinned in the same place.
func defaultsSample() *Schema {
	users := Table{ID: "t1", Name: "users", Comment: "the users table", Columns: []Col{
		{Name: "id", Type: "INT", Pk: true, Nn: true, Ai: true},
		{Name: "status", Type: "VARCHAR(20)", Nn: true, Default: "'active'"},
		{Name: "created_at", Type: "DATETIME", Default: "CURRENT_TIMESTAMP"},
		{Name: "score", Type: "INT", Default: "0"},
		{Name: "token", Type: "VARCHAR(64)", Default: "(uuid())"},
	}}
	logs := Table{ID: "t2", Name: "logs", Columns: []Col{
		{Name: "msg", Type: "TEXT", Default: "'it''s fine'"},
	}}
	return &Schema{Tables: []Table{users, logs}}
}

func TestDefaultEmitAllDialects(t *testing.T) {
	cases := []struct{ dialect, want string }{
		{"mysql", "DEFAULT 'active'"},
		{"mysql", "DEFAULT CURRENT_TIMESTAMP"},
		{"mysql", "DEFAULT 0"},
		{"mysql", "DEFAULT (uuid())"},
		{"mariadb", "DEFAULT 'active'"},
		{"postgres", "DEFAULT 'active'"},
		{"postgres", "DEFAULT CURRENT_TIMESTAMP"},
		{"postgres", "DEFAULT (uuid())"},
		{"sqlite", "DEFAULT 'active'"},
		{"sqlite", "DEFAULT CURRENT_TIMESTAMP"},
		{"sqlite", "DEFAULT (uuid())"},
	}
	for _, c := range cases {
		sql, err := exportSQL(c.dialect, defaultsSample().Tables)
		if err != nil {
			t.Fatalf("%s: %v", c.dialect, err)
		}
		if !strings.Contains(sql, c.want) {
			t.Errorf("%s output missing %q:\n%s", c.dialect, c.want, sql)
		}
	}
}

func TestDefaultRoundTripEachDialect(t *testing.T) {
	for _, d := range []string{"mysql", "mariadb", "postgres", "sqlite"} {
		s := defaultsSample()
		s.Dialect = d
		sql, err := s.GenSQL()
		if err != nil {
			t.Fatalf("%s GenSQL: %v", d, err)
		}
		g, err := ParseDDL(sql)
		if err != nil {
			t.Fatalf("%s parse: %v\n%s", d, err, sql)
		}
		cols := g.Tables[0].Columns
		want := map[string]string{
			"status":     "'active'",
			"created_at": "CURRENT_TIMESTAMP",
			"score":      "0",
			"token":      "(uuid())",
		}
		for name, wantDefault := range want {
			var got string
			for _, c := range cols {
				if c.Name == name {
					got = c.Default
				}
			}
			if got != wantDefault {
				t.Errorf("%s: column %s default %q, want %q", d, name, got, wantDefault)
			}
		}
		// the escaped quote survives the string literal round-trip
		if g.Tables[1].Columns[0].Default != "'it''s fine'" {
			t.Errorf("%s: escaped-quote default %q lost", d, g.Tables[1].Columns[0].Default)
		}
	}
}

// An empty default emits no clause: files written before the field existed,
// and schemas that never set one, keep their exact bytes. The golden tests
// pin the full output; this pins the per-column shape.
func TestDefaultEmptyOmitsClause(t *testing.T) {
	for _, d := range []string{"mysql", "postgres", "sqlite"} {
		sql, err := exportSQL(d, sample()) // sample() (export_test.go) has no defaults
		if err != nil {
			t.Fatalf("%s: %v", d, err)
		}
		if hasDefaultClause(sql) {
			t.Errorf("%s emitted a DEFAULT for a schema with none:\n%s", d, sql)
		}
	}
}

// hasDefaultClause reports whether emitted DDL contains a DEFAULT clause.
// Postgres's identity rendering ("GENERATED BY DEFAULT AS IDENTITY") contains
// the word DEFAULT without being a column DEFAULT, so it is stripped first.
func hasDefaultClause(sql string) bool {
	cleaned := strings.ReplaceAll(sql, "GENERATED BY DEFAULT AS IDENTITY", "")
	return strings.Contains(cleaned, "DEFAULT")
}

func TestRejectsDefaultInjection(t *testing.T) {
	bad := []string{
		"0; DROP TABLE users;--",
		"'x'; DROP TABLE users;--",
		"5 -- trailing comment",
		"CURRENT_TIMESTAMP; ",
		`0" OR "1"="1`, // double-quote injection shape
		"0` OR 1=1",    // backtick injection shape
		"0 /* block comment */",
		"(0", // unbalanced parens
		"0)", // unbalanced parens
		"'unterminated",
	}
	for _, v := range bad {
		s := &Schema{Tables: []Table{{Name: "t", Columns: []Col{{Name: "c", Type: "INT", Default: v}}}}}
		if err := s.Validate(); err == nil {
			t.Errorf("accepted unsafe default %q", v)
		}
	}
	good := []string{
		"0", "-1", "1.5", ".5", "'a'", "''", "NULL", "TRUE", "FALSE",
		"CURRENT_TIMESTAMP", "CURRENT_TIMESTAMP(6)", "NOW()", "(uuid())",
		"'it''s'", "'a;b'", "CURRENT_TIMESTAMP + INTERVAL '1 day'",
	}
	for _, v := range good {
		s := &Schema{Tables: []Table{{Name: "t", Columns: []Col{{Name: "c", Type: "INT", Default: v}}}}}
		if err := s.Validate(); err != nil {
			t.Errorf("rejected legitimate default %q: %v", v, err)
		}
	}
}

// The validateOutput last gate is quote-aware: a `;` INSIDE a quoted default
// literal must emit cleanly (it is part of the value), while one outside would
// be the injection shape. Pin the full emit path (GenSQL runs validateOutput),
// not just Validate.
func TestDefaultQuotedSemicolonEmitsSafely(t *testing.T) {
	for _, d := range []string{"mysql", "postgres", "sqlite"} {
		s := &Schema{Dialect: d, Tables: []Table{{Name: "t", Columns: []Col{
			{Name: "c", Type: "INT", Default: "'a;b'"},
		}}}}
		sql, err := s.GenSQL()
		if err != nil {
			t.Fatalf("%s: GenSQL rejected a quoted-semicolon default: %v\n%s", d, err, sql)
		}
		if !strings.Contains(sql, "DEFAULT 'a;b'") {
			t.Errorf("%s: quoted-semicolon default not emitted:\n%s", d, sql)
		}
	}
}

// ENUM shares the mysql column line with DEFAULT (type args + DEFAULT clause):
// pin that the parser keeps both.
func TestDefaultEnumMysql(t *testing.T) {
	s := &Schema{Dialect: DialectMysql, Tables: []Table{{Name: "t", Columns: []Col{
		{Name: "status", Type: "ENUM('a','b')", Default: "'a'"},
	}}}}
	sql, err := s.GenSQL()
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(sql, "DEFAULT 'a'") {
		t.Fatalf("missing DEFAULT:\n%s", sql)
	}
	g, err := ParseDDL(sql)
	if err != nil {
		t.Fatal(err)
	}
	c := g.Tables[0].Columns[0]
	if c.Default != "'a'" || c.Type != "ENUM('a','b')" {
		t.Errorf("mysql ENUM+default round-trip: type %q default %q", c.Type, c.Default)
	}
}

// A PK that is not AI may carry a DEFAULT (MySQL allows it) — the AI+DEFAULT
// refusal is about auto-increment, not primary keys.
func TestDefaultOnPrimaryKey(t *testing.T) {
	s := &Schema{Dialect: DialectMysql, Tables: []Table{{Name: "t", Columns: []Col{
		{Name: "id", Type: "INT", Pk: true, Nn: true, Default: "0"},
	}}}}
	sql, err := s.GenSQL()
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(sql, "DEFAULT 0") {
		t.Fatalf("missing DEFAULT on PK:\n%s", sql)
	}
	g, err := ParseDDL(sql)
	if err != nil {
		t.Fatal(err)
	}
	if c := g.Tables[0].Columns[0]; c.Default != "0" || !c.Pk {
		t.Errorf("PK+default round-trip: default %q pk %v", c.Default, c.Pk)
	}
}

// Control characters and oversized expressions are refused the same way the
// type field is: a newline would break the line-oriented format, and the cap
// stops a request padding the model into an oversized response.
func TestRejectsBadDefaultShapes(t *testing.T) {
	bad := []string{
		"0\n1",
		"0\x01",
		strings.Repeat("0", maxDefaultLen+1),
	}
	for _, v := range bad {
		s := &Schema{Tables: []Table{{Name: "t", Columns: []Col{{Name: "c", Type: "INT", Default: v}}}}}
		if err := s.Validate(); err == nil {
			t.Errorf("accepted malformed default %q", v)
		}
	}
}

func TestRejectsOverlongTableComment(t *testing.T) {
	s := &Schema{Tables: []Table{{Name: "t", Comment: strings.Repeat("x", maxCommentLen+1), Columns: []Col{
		{Name: "id", Type: "INT", Pk: true},
	}}}}
	if err := s.Validate(); err == nil {
		t.Error("accepted an overlong table comment")
	}
}

// AI + DEFAULT is invalid DDL in every dialect (MySQL refuses a DEFAULT on
// AUTO_INCREMENT, Postgres on an identity column, SQLite on the rowid alias),
// so the pair is refused up front rather than emitted for the database to
// reject. A hand-written file carrying the pair must fail on open too.
func TestRejectsAiWithDefault(t *testing.T) {
	s := &Schema{Tables: []Table{{Name: "t", Columns: []Col{
		{Name: "id", Type: "INT", Ai: true, Nn: true, Pk: true, Default: "0"},
	}}}}
	if err := s.Validate(); err == nil {
		t.Error("accepted an AUTO_INCREMENT column with a DEFAULT")
	}
	// the file path: emitted by hand, opened through ParseDDL, rejected
	handWritten := "-- Generated by erd-creator\nCREATE TABLE `t` (\n  `id` INT NOT NULL AUTO_INCREMENT DEFAULT 0 PRIMARY KEY\n);\n"
	if _, err := ParseDDL(handWritten); err == nil {
		t.Error("ParseDDL accepted an AUTO_INCREMENT column with a DEFAULT")
	}
}

func TestTableCommentRoundTrip(t *testing.T) {
	for _, d := range []string{"mysql", "mariadb", "postgres"} {
		s := defaultsSample()
		s.Dialect = d
		sql, err := s.GenSQL()
		if err != nil {
			t.Fatalf("%s GenSQL: %v", d, err)
		}
		g, err := ParseDDL(sql)
		if err != nil {
			t.Fatalf("%s parse: %v\n%s", d, err, sql)
		}
		if g.Tables[0].Comment != "the users table" {
			t.Errorf("%s: table comment %q, want %q", d, g.Tables[0].Comment, "the users table")
		}
		if g.Tables[1].Comment != "" {
			t.Errorf("%s: comment-less table gained %q", d, g.Tables[1].Comment)
		}
	}
}

// SQLite has no table comment, so buildSqlite omits it. The omission is
// deliberate and documented (lossy, like TINYINT on postgres): assert it so
// nobody "fixes" it by emitting a -- line the parser cannot read back.
func TestTableCommentDroppedForSqlite(t *testing.T) {
	sql, err := exportSQL("sqlite", defaultsSample().Tables)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(sql, "COMMENT") {
		t.Errorf("sqlite emitted a table comment it cannot parse back:\n%s", sql)
	}
	g, err := ParseDDL(sql)
	if err != nil {
		t.Fatal(err)
	}
	if g.Tables[0].Comment != "" {
		t.Errorf("sqlite reopen gained comment %q", g.Tables[0].Comment)
	}
}

func TestTableCommentEscaping(t *testing.T) {
	s := &Schema{Dialect: "mysql", Tables: []Table{{Name: "t", Comment: "it's \"my\" table", Columns: []Col{
		{Name: "id", Type: "INT", Pk: true},
	}}}}
	sql, err := s.GenSQL()
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(sql, "COMMENT='it''s \"my\" table'") {
		t.Errorf("comment not escaped correctly:\n%s", sql)
	}
	g, err := ParseDDL(sql)
	if err != nil {
		t.Fatal(err)
	}
	if g.Tables[0].Comment != "it's \"my\" table" {
		t.Errorf("escaped comment round-trip %q", g.Tables[0].Comment)
	}
}

// Inserts follow the schema's dialect: quoting per grammar, NOW() where the
// dialect has it, CURRENT_TIMESTAMP for SQLite. The mysql output is unchanged
// from before the field-aware refactor — same header, same bytes.
func TestGenInsertsDialects(t *testing.T) {
	// sample() has no datetime column, so give the insert test its own
	// fixture with one: NOW()/CURRENT_TIMESTAMP only appear for DATETIME.
	s := &Schema{Tables: []Table{{Name: "events", Columns: []Col{
		{Name: "id", Type: "INT", Pk: true, Nn: true, Ai: true},
		{Name: "created_at", Type: "DATETIME"},
		{Name: "note", Type: "VARCHAR(255)"},
	}}}}
	ins := s.GenInserts()
	mysqlIns := ins // the mysql bytes, the equality baseline for mariadb
	if !strings.Contains(ins, "-- Seed row templates (edit values, remove per table as needed)") {
		t.Errorf("mysql header changed:\n%s", ins)
	}
	if !strings.Contains(ins, "INSERT INTO `events`") || !strings.Contains(ins, "NOW()") {
		t.Errorf("mysql inserts lost backtick quoting/NOW():\n%s", ins)
	}

	s.Dialect = DialectPostgres
	ins = s.GenInserts()
	if !strings.Contains(ins, `INSERT INTO "events"`) {
		t.Errorf("postgres inserts are not double-quoted:\n%s", ins)
	}
	if !strings.Contains(ins, "NOW()") {
		t.Errorf("postgres inserts lost NOW():\n%s", ins)
	}
	if strings.Contains(ins, "`") {
		t.Errorf("postgres inserts contain backticks:\n%s", ins)
	}

	s.Dialect = DialectSqlite
	ins = s.GenInserts()
	if !strings.Contains(ins, "INSERT INTO `events`") || !strings.Contains(ins, "CURRENT_TIMESTAMP") {
		t.Errorf("sqlite inserts missing backticks/CURRENT_TIMESTAMP:\n%s", ins)
	}
	if strings.Contains(ins, "NOW(") {
		t.Errorf("sqlite inserts contain NOW() which SQLite lacks:\n%s", ins)
	}

	// mariadb shares the mysql grammar, so its templates are byte-identical
	// to mysql's (same backticks, same NOW(), same header).
	s.Dialect = DialectMariaDB
	if got, want := s.GenInserts(), mysqlIns; got != want {
		t.Errorf("mariadb inserts differ from mysql's:\n--- got ---\n%s--- want ---\n%s", got, want)
	}
}

// Round-trip through the SAVED file keeps the SQLite default, including with
// the ENUM CHECK shape that shares the column line.
func TestSqliteDefaultWithEnum(t *testing.T) {
	s := &Schema{Dialect: DialectSqlite, Tables: []Table{{Name: "t", Columns: []Col{
		{Name: "status", Type: "ENUM('a','b')", Default: "'a'"},
	}}}}
	sql, err := s.GenSQL()
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(sql, "DEFAULT 'a'") {
		t.Fatalf("missing DEFAULT:\n%s", sql)
	}
	g, err := ParseDDL(sql)
	if err != nil {
		t.Fatal(err)
	}
	c := g.Tables[0].Columns[0]
	if c.Default != "'a'" || c.Type != "ENUM('a','b')" {
		t.Errorf("sqlite ENUM+default round-trip: type %q default %q", c.Type, c.Default)
	}
}
