package main

import (
	"strings"
	"testing"
)

func sample() []reqTable {
	return []reqTable{
		{Id: "t1", Name: "users", Columns: []reqCol{
			{Name: "id", Type: "INT", Pk: true, Nn: true, Ai: true, Comment: "pk"},
			{Name: "email", Type: "VARCHAR(190)", Nn: true, Ux: true, Ix: true},
			{Name: "status", Type: "ENUM('active','banned')"},
		}},
		{Id: "t2", Name: "posts", Columns: []reqCol{
			{Name: "id", Type: "BIGINT", Pk: true, Nn: true, Ai: true},
			{Name: "user_id", Type: "INT", Ref: &reqRef{TableId: "t1", Action: "SET NULL"}},
		}},
	}
}

func TestExportDialects(t *testing.T) {
	cases := []struct{ dialect, want string }{
		{"mysql", "AUTO_INCREMENT"},
		{"mysql", "ENUM('active','banned')"},
		{"mysql", "COMMENT 'pk'"},
		{"mariadb", "(MariaDB)"},
		{"mariadb", "ON DELETE SET NULL"},
		{"postgres", "GENERATED BY DEFAULT AS IDENTITY"},
		{"postgres", "COMMENT ON COLUMN"},
		{"postgres", "CREATE INDEX"},
		{"postgres", `CHECK ("status" IN ('active', 'banned'))`},
		{"sqlite", "INTEGER PRIMARY KEY"},
		{"sqlite", "CHECK (`status` IN ('active', 'banned'))"},
	}
	for _, c := range cases {
		sql, err := exportSQL(c.dialect, sample())
		if err != nil {
			t.Fatalf("%s: %v", c.dialect, err)
		}
		if !strings.Contains(sql, c.want) {
			t.Errorf("%s output missing %q:\n%s", c.dialect, c.want, sql)
		}
	}
}

func TestExportEscaping(t *testing.T) {
	tables := []reqTable{
		{Id: "t1", Name: "we`ird", Columns: []reqCol{
			{Name: "a`b", Type: "INT", Pk: true},
			{Name: "c", Type: "VARCHAR(10)", Comment: "it's \"quoted\""},
			{Name: "e", Type: "ENUM('a''b','c,d')"},
		}},
	}
	for _, d := range []string{"mysql", "postgres", "sqlite"} {
		sql, err := exportSQL(d, tables)
		if err != nil {
			t.Fatalf("%s: %v", d, err)
		}
		// mysql/sqlite double the backtick; PG wraps in "" and leaves ` literal
		want := "we``ird"
		if d == "postgres" {
			want = "\"we`ird\""
		}
		if !strings.Contains(sql, want) {
			t.Errorf("%s: identifier not escaped (%q):\n%s", d, want, sql)
		}
		// enum value a'b must survive as doubled quote in the emitted literal
		if !strings.Contains(sql, "'a''b'") {
			t.Errorf("%s: escaped enum value lost:\n%s", d, sql)
		}
		// comma inside quoted enum value must not split the value list
		if !strings.Contains(sql, "'c,d'") {
			t.Errorf("%s: comma-in-value enum split:\n%s", d, sql)
		}
	}
}

func TestExportEdgeCases(t *testing.T) {
	// dangling ref skipped; composite-PK parent FK skipped (invalid single-col FK);
	// empty action defaults CASCADE; composite PK itself all emitted
	tables := []reqTable{
		{Id: "t1", Name: "m", Columns: []reqCol{
			{Name: "a", Type: "INT", Pk: true},
			{Name: "b", Type: "INT", Pk: true},
			{Name: "g", Type: "INT", Ref: &reqRef{TableId: "gone"}},
		}},
		{Id: "t2", Name: "n", Columns: []reqCol{
			{Name: "id", Type: "INT", Pk: true},
			{Name: "m_a", Type: "INT", Ref: &reqRef{TableId: "t1", Action: "RESTRICT"}},
			{Name: "s", Type: "INT", Ref: &reqRef{TableId: "t3"}},
		}},
		{Id: "t3", Name: "singles", Columns: []reqCol{
			{Name: "id", Type: "INT", Pk: true},
		}},
	}
	sql, err := exportSQL("mysql", tables)
	if err != nil {
		t.Fatal(err)
	}
	for _, banned := range []string{"`gone`", "CONSTRAINT `fk_n_m_a`"} {
		if strings.Contains(sql, banned) {
			t.Errorf("must be skipped (%s):\n%s", banned, sql)
		}
	}
	for _, want := range []string{"ON DELETE CASCADE", "PRIMARY KEY (`a`, `b`)"} {
		if !strings.Contains(sql, want) {
			t.Errorf("missing %q:\n%s", want, sql)
		}
	}
}

func TestExportRejects(t *testing.T) {
	if _, err := exportSQL("oracle", sample()); err == nil {
		t.Error("unknown dialect must error")
	}
	if _, err := exportSQL("mysql", nil); err == nil {
		t.Error("empty schema must error")
	}
}
