// export.go — server-side dialect generator (MySQL, MariaDB, PostgreSQL, SQLite).
// Dialect grammar work lives here, not in the browser: the client POSTs its schema
// JSON and gets dialect DDL back. Saved files stay MySQL-canonical; other dialects
// are export-only, which keeps the client parser a single trivial grammar.
package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strings"
)

func handleExport(w http.ResponseWriter, r *http.Request) {
	b, ok := decodeBody(w, r)
	if !ok {
		return
	}
	// Dialect + schema in one pass; the schema half shares its accepted
	// envelope with every other schema endpoint via schemaEnvelope.
	var req struct {
		Dialect string `json:"dialect"`
		schemaEnvelope
	}
	if err := json.Unmarshal(b, &req); err != nil {
		http.Error(w, "bad json: "+err.Error(), http.StatusBadRequest)
		return
	}
	sql, err := schemaExportSQL(req.schema(), req.Dialect)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	fmt.Fprint(w, sql)
}

func exportSQL(dialect string, tables []Table) (string, error) {
	return exportSQLWith(dialect, tables, SqliteTypesNative)
}

// exportSQLWith is exportSQL with the SQLite type-rendering mode made explicit.
// Callers holding a Schema should prefer schemaExportSQL, which reads the mode
// off the schema instead of defaulting it.
func exportSQLWith(dialect string, tables []Table, sqliteTypes string) (string, error) {
	if len(tables) == 0 {
		return "", errors.New("schema has no tables")
	}
	switch strings.ToLower(dialect) {
	case "mysql":
		return buildMysql(tables, "-- Generated by erd-creator (MySQL)"), nil
	case "mariadb":
		return buildMariaDB(tables), nil
	case "postgres", "postgresql":
		return buildPostgres(tables), nil
	case "sqlite":
		return buildSqlite(tables, sqliteTypes), nil
	default:
		return "", fmt.Errorf("unknown dialect %q (want mysql, mariadb, postgres, sqlite)", dialect)
	}
}

// schemaExportSQL is the export path for a schema that carries its own dialect
// and SQLite type mode, which is what /export and the UI use. Keeping it next to
// exportSQL is deliberate: the two must stay one implementation, since a second
// emitter is exactly how the save/export drift happened before.
func schemaExportSQL(s *Schema, dialect string) (string, error) {
	return exportSQLWith(dialect, s.Tables, s.sqliteTypesMode())
}

// ---- helpers ----

func quoteTick(n string) string { return "`" + strings.ReplaceAll(n, "`", "``") + "`" }
func quoteDQ(n string) string   { return `"` + strings.ReplaceAll(n, `"`, `""`) + `"` }
func sqlStr(s string) string    { return "'" + strings.ReplaceAll(s, "'", "''") + "'" }

func splitType(ty string) (string, string) {
	if i := strings.Index(ty, "("); i >= 0 && strings.HasSuffix(ty, ")") {
		return strings.ToUpper(ty[:i]), ty[i+1 : len(ty)-1]
	}
	return strings.ToUpper(ty), ""
}

// splitTop splits on top-level commas, respecting parens and ” escaped strings.
func splitTop(s string) []string {
	var out []string
	depth, inStr, start := 0, false, 0
	for i := 0; i < len(s); i++ { // classic loop: body's i++ must skip the escaped quote
		c := s[i]
		switch {
		case c == '\'' && inStr && i+1 < len(s) && s[i+1] == '\'':
			i++ // skip second quote of '' escape
		case c == '\'':
			inStr = !inStr
		case inStr:
		case c == '(':
			depth++
		case c == ')':
			depth--
		case c == ',' && depth == 0:
			out = append(out, strings.TrimSpace(s[start:i]))
			start = i + 1
		}
	}
	if rest := strings.TrimSpace(s[start:]); rest != "" {
		out = append(out, rest)
	}
	return out
}

func enumValues(ty string) []string {
	base, args := splitType(ty)
	if base != "ENUM" {
		return nil
	}
	var vals []string
	for _, v := range splitTop(args) {
		if len(v) >= 2 && strings.HasPrefix(v, "'") && strings.HasSuffix(v, "'") {
			v = strings.ReplaceAll(v[1:len(v)-1], "''", "'")
		}
		vals = append(vals, v)
	}
	return vals
}

// enumCheck renders an ENUM as a CHECK constraint, for dialects without a
// native enum type: CHECK (<col> IN ('a', 'b')). ok=false when ty is not an
// ENUM with at least one value, leaving the caller to fall back to TEXT.
// q quotes the column identifier (backticks or double quotes, per dialect).
func enumCheck(colName, ty string, q func(string) string) (string, bool) {
	vals := enumValues(ty)
	if vals == nil {
		return "", false
	}
	quoted := make([]string, len(vals))
	for i, v := range vals {
		quoted[i] = sqlStr(v)
	}
	return fmt.Sprintf("CHECK (%s IN (%s))", q(colName), strings.Join(quoted, ", ")), true
}

func baseOf(ty string) string {
	base, _ := splitType(ty)
	return base
}

func isInt(base string) bool {
	switch base {
	case "INT", "BIGINT", "SMALLINT", "TINYINT":
		return true
	}
	return false
}

func findTable(tables []Table, id string) *Table {
	for i := range tables {
		if tables[i].Id == id {
			return &tables[i]
		}
	}
	return nil
}

// pkCol: the sole PK column. ok=false for a composite PK (a single-col FK onto
// it is invalid DDL) AND for a table with no PK at all — pointing an FK at a
// non-unique first column would emit invalid MySQL, so callers skip it. Lint
// reports both cases; save (GenSQL) and export (buildMysql) now agree via this.
func pkCol(t Table) (Col, bool) {
	var pk Col
	n := 0
	for _, c := range t.Columns {
		if c.Pk {
			n++
			pk = c
		}
	}
	if n == 1 {
		return pk, true
	}
	return Col{}, false
}

// fkTarget resolves a column's FK to its parent table and the single PK column
// that FK references. ok=false when the parent is missing (dangling ref) or has
// no sole PK — a single-column FK onto a composite or absent PK is invalid DDL,
// so every dialect omits it. Lint reports both cases.
//
// Shared by all three dialect builders: they differ in how they render the
// constraint, not in which FKs are emittable.
func fkTarget(tables []Table, c Col) (*Table, Col, bool) {
	if c.Ref == nil {
		return nil, Col{}, false
	}
	rt := findTable(tables, c.Ref.TableId)
	if rt == nil {
		return nil, Col{}, false
	}
	rp, ok := pkCol(*rt)
	if !ok {
		return nil, Col{}, false
	}
	return rt, rp, true
}

func refCols(t Table) []Col {
	var out []Col
	for _, c := range t.Columns {
		if c.Ref != nil {
			out = append(out, c)
		}
	}
	return out
}

func fkAction(c Col) string {
	if c.Ref.Action == "" {
		return "CASCADE"
	}
	return c.Ref.Action
}

func pkLine(t Table, q func(string) string) string {
	var pks []string
	for _, c := range pkCols(t) {
		pks = append(pks, q(c.Name))
	}
	if len(pks) == 0 {
		return ""
	}
	return "  PRIMARY KEY (" + strings.Join(pks, ", ") + ")"
}

// ---- MySQL / MariaDB ----

func buildMysql(tables []Table, header string) string {
	out := []string{header}
	for _, t := range tables {
		if len(t.Columns) == 0 {
			continue // empty table → invalid DDL (UI guards; parse can't produce)
		}
		var lines []string
		for _, c := range t.Columns {
			base, args := splitType(c.Type)
			ty := base
			if args != "" && !(c.Ai && isInt(base)) {
				ty = base + "(" + args + ")"
			}
			s := "  " + quoteTick(c.Name) + " " + ty
			if c.Nn || c.Pk {
				s += " NOT NULL"
			}
			if c.Ai && isInt(base) {
				s += " AUTO_INCREMENT"
			}
			if c.Ux {
				s += " UNIQUE"
			}
			if c.Comment != "" {
				s += " COMMENT " + sqlStr(c.Comment)
			}
			lines = append(lines, s)
		}
		if l := pkLine(t, quoteTick); l != "" {
			lines = append(lines, l)
		}
		for _, c := range t.Columns {
			if c.Ix {
				lines = append(lines, "  KEY "+quoteTick("idx_"+t.Name+"_"+c.Name)+" ("+quoteTick(c.Name)+")")
			}
		}
		for _, c := range refCols(t) {
			rt, rp, ok := fkTarget(tables, c)
			if !ok {
				continue
			}
			lines = append(lines, fmt.Sprintf(
				"  CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s) ON DELETE %s",
				quoteTick("fk_"+t.Name+"_"+c.Name), quoteTick(c.Name), quoteTick(rt.Name), quoteTick(rp.Name), fkAction(c)))
		}
		out = append(out, "CREATE TABLE "+quoteTick(t.Name)+" (\n"+strings.Join(lines, ",\n")+"\n) ENGINE=InnoDB;")
	}
	return strings.Join(out, "\n") + "\n"
}

// buildMariaDB emits MariaDB DDL.
//
// Today this is byte-identical to buildMysql apart from the header, because the
// two grammars have not diverged for any construct we emit. It exists as a
// separate function on purpose: it is the place MariaDB-specific syntax goes
// when it is needed, without a flag threading through the MySQL path.
//
// The cost of that headroom is two emitters that must be kept in step, which is
// the shape that produced the original save/export drift in this repo.
// TestMariaDBMatchesMysql pins the two to identical output so the moment they
// diverge — deliberately or by accident — it fails and forces a decision.
// If MariaDB genuinely needs different DDL, update that test deliberately and
// record the difference here.
func buildMariaDB(tables []Table) string {
	out := []string{"-- Generated by erd-creator (MariaDB)"}
	for _, t := range tables {
		if len(t.Columns) == 0 {
			continue // empty table → invalid DDL (UI guards; parse can't produce)
		}
		var lines []string
		for _, c := range t.Columns {
			base, args := splitType(c.Type)
			ty := base
			if args != "" && !(c.Ai && isInt(base)) {
				ty = base + "(" + args + ")"
			}
			s := "  " + quoteTick(c.Name) + " " + ty
			if c.Nn || c.Pk {
				s += " NOT NULL"
			}
			if c.Ai && isInt(base) {
				s += " AUTO_INCREMENT"
			}
			if c.Ux {
				s += " UNIQUE"
			}
			if c.Comment != "" {
				s += " COMMENT " + sqlStr(c.Comment)
			}
			lines = append(lines, s)
		}
		if l := pkLine(t, quoteTick); l != "" {
			lines = append(lines, l)
		}
		for _, c := range t.Columns {
			if c.Ix {
				lines = append(lines, "  KEY "+quoteTick("idx_"+t.Name+"_"+c.Name)+" ("+quoteTick(c.Name)+")")
			}
		}
		for _, c := range refCols(t) {
			rt, rp, ok := fkTarget(tables, c)
			if !ok {
				continue
			}
			lines = append(lines, fmt.Sprintf(
				"  CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s) ON DELETE %s",
				quoteTick("fk_"+t.Name+"_"+c.Name), quoteTick(c.Name), quoteTick(rt.Name), quoteTick(rp.Name), fkAction(c)))
		}
		out = append(out, "CREATE TABLE "+quoteTick(t.Name)+" (\n"+strings.Join(lines, ",\n")+"\n) ENGINE=InnoDB;")
	}
	return strings.Join(out, "\n") + "\n"
}

// ---- PostgreSQL ----

func pgType(c Col) (string, string) { // type + inline extra (CHECK for ENUM)
	base, args := splitType(c.Type)
	switch base {
	case "TINYINT":
		base = "SMALLINT"
	case "DATETIME":
		base = "TIMESTAMP"
	case "JSON":
		base = "JSONB"
	case "ENUM":
		if check, ok := enumCheck(c.Name, c.Type, quoteDQ); ok {
			return "TEXT", check
		}
		base = "TEXT"
	}
	if args != "" && base != "TEXT" {
		return base + "(" + args + ")", ""
	}
	return base, ""
}

func buildPostgres(tables []Table) string {
	out := []string{"-- Generated by erd-creator (PostgreSQL)"}
	for _, t := range tables {
		if len(t.Columns) == 0 {
			continue
		}
		var lines, post []string
		for _, c := range t.Columns {
			ty, extra := pgType(c)
			if c.Ai && isInt(ty) {
				ty += " GENERATED BY DEFAULT AS IDENTITY"
			}
			s := "  " + quoteDQ(c.Name) + " " + ty
			if c.Nn || c.Pk {
				s += " NOT NULL"
			}
			if c.Ux {
				s += " UNIQUE"
			}
			if extra != "" {
				s += " " + extra
			}
			lines = append(lines, s)
			if c.Comment != "" {
				post = append(post, fmt.Sprintf("COMMENT ON COLUMN %s.%s IS %s;",
					quoteDQ(t.Name), quoteDQ(c.Name), sqlStr(c.Comment)))
			}
			if c.Ix {
				post = append(post, fmt.Sprintf("CREATE INDEX %s ON %s (%s);",
					quoteDQ("idx_"+t.Name+"_"+c.Name), quoteDQ(t.Name), quoteDQ(c.Name)))
			}
		}
		if l := pkLine(t, quoteDQ); l != "" {
			lines = append(lines, l)
		}
		for _, c := range refCols(t) {
			rt, rp, ok := fkTarget(tables, c)
			if !ok {
				continue
			}
			lines = append(lines, fmt.Sprintf(
				"  CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s) ON DELETE %s",
				quoteDQ("fk_"+t.Name+"_"+c.Name), quoteDQ(c.Name), quoteDQ(rt.Name), quoteDQ(rp.Name), fkAction(c)))
		}
		out = append(out, "CREATE TABLE "+quoteDQ(t.Name)+" (\n"+strings.Join(lines, ",\n")+"\n);")
		out = append(out, post...)
	}
	return strings.Join(out, "\n") + "\n"
}

// ---- SQLite ----

// buildSqlite emits SQLite DDL. typesMode selects how BOOLEAN/DATETIME/
// TIMESTAMP render — see SqliteTypesNative / SqliteTypesPortable for what each
// buys and what the portable one costs. ENUM is TEXT + CHECK either way.
//
// The mode is recorded in the header comment when it is not the default, so a
// portable file reopens as portable. Without that the setting would be lost on
// reopen: the dropdown would read "native" while the bytes on disk were written
// as portable, and a newly added BOOLEAN column would contradict the file's own
// convention. The native header stays exactly as it was, so files already
// written keep their bytes.
//
// ponytail: SQLite lacks COMMENT and ENUM; comments become -- lines, ENUM becomes
// TEXT + inline CHECK, AUTO_INCREMENT relies on the INTEGER PRIMARY KEY rowid alias.
func buildSqlite(tables []Table, typesMode string) string {
	header := "-- Generated by erd-creator (SQLite)"
	portable := typesMode == SqliteTypesPortable
	if portable {
		header = "-- Generated by erd-creator (SQLite, types: " + SqliteTypesPortable + ")"
	}
	out := []string{header}
	for _, t := range tables {
		if len(t.Columns) == 0 {
			continue
		}
		var lines, post []string
		pks := pkCols(t)
		// rowid alias: single integer PK → inline INTEGER PRIMARY KEY, auto-assign for free
		aiPk := len(pks) == 1 && pks[0].Ai && isInt(baseOf(pks[0].Type))
		for _, c := range t.Columns {
			base, args := splitType(c.Type)
			ty, check := base, ""
			switch base {
			case "ENUM":
				// unaffected by the mode: SQLite has no enum type at all
				ty = "TEXT"
				if sql, ok := enumCheck(c.Name, c.Type, quoteTick); ok {
					check = sql
				}
			case "BOOLEAN":
				if portable {
					ty = "INTEGER"
				}
			case "DATETIME", "TIMESTAMP":
				if portable {
					ty = "TEXT"
				}
			}
			if args != "" && ty == base {
				ty = base + "(" + args + ")"
			}
			var s string
			if aiPk && c.Pk {
				s = "  " + quoteTick(c.Name) + " INTEGER PRIMARY KEY"
			} else {
				s = "  " + quoteTick(c.Name) + " " + ty
				if c.Nn || c.Pk {
					s += " NOT NULL"
				}
				if c.Ux {
					s += " UNIQUE"
				}
				if check != "" {
					s += " " + check
				}
			}
			if c.Comment != "" {
				// The comment rides along in the SAME list entry as its column.
				// As a separate entry it would pick up the comma the join adds,
				// and the parser would read that comma back as part of the
				// comment text ("pk" → "pk,"), so the file stopped round-tripping.
				s = "  -- " + c.Name + ": " + c.Comment + "\n" + s
			}
			lines = append(lines, s)
			if c.Ix {
				post = append(post, fmt.Sprintf("CREATE INDEX IF NOT EXISTS %s ON %s (%s);",
					quoteTick("idx_"+t.Name+"_"+c.Name), quoteTick(t.Name), quoteTick(c.Name)))
			}
		}
		if !aiPk {
			if l := pkLine(t, quoteTick); l != "" {
				lines = append(lines, l)
			}
		}
		for _, c := range refCols(t) {
			rt, rp, ok := fkTarget(tables, c)
			if !ok {
				continue
			}
			lines = append(lines, fmt.Sprintf(
				"  FOREIGN KEY (%s) REFERENCES %s (%s) ON DELETE %s",
				quoteTick(c.Name), quoteTick(rt.Name), quoteTick(rp.Name), fkAction(c)))
		}
		out = append(out, "CREATE TABLE "+quoteTick(t.Name)+" (\n"+strings.Join(lines, ",\n")+"\n);")
		out = append(out, post...)
	}
	return strings.Join(out, "\n") + "\n"
}
