package main

import (
	"encoding/json"
	"strings"
	"testing"
)

func sample() []Table {
	return baseSchema().Tables
}

func TestExportDialects(t *testing.T) {
	cases := []struct{ dialect, want string }{
		{"mysql", "AUTO_INCREMENT"},
		{"mysql", "ENUM('active','banned')"},
		{"mysql", "COMMENT 'pk'"},
		{"mariadb", "(MariaDB)"},
		{"mariadb", "ON DELETE SET NULL"},
		{"postgres", "GENERATED BY DEFAULT AS IDENTITY"},
		{"postgres", "COMMENT ON COLUMN"},
		{"postgres", "CREATE INDEX"},
		{"postgres", `CHECK ("status" IN ('active', 'banned'))`},
		{"sqlite", "INTEGER PRIMARY KEY"},
		{"sqlite", "CHECK (`status` IN ('active', 'banned'))"},
	}
	for _, c := range cases {
		sql, err := exportSQL(c.dialect, sample())
		if err != nil {
			t.Fatalf("%s: %v", c.dialect, err)
		}
		if !strings.Contains(sql, c.want) {
			t.Errorf("%s output missing %q:\n%s", c.dialect, c.want, sql)
		}
	}
}

func TestExportEscaping(t *testing.T) {
	tables := []Table{
		{ID: "t1", Name: "we`ird", Columns: []Col{
			{Name: "a`b", Type: "INT", Pk: true},
			{Name: "c", Type: "VARCHAR(10)", Comment: "it's \"quoted\""},
			{Name: "e", Type: "ENUM('a''b','c,d')"},
		}},
	}
	for _, d := range []string{"mysql", "postgres", "sqlite"} {
		sql, err := exportSQL(d, tables)
		if err != nil {
			t.Fatalf("%s: %v", d, err)
		}
		// mysql/sqlite double the backtick; PG wraps in "" and leaves ` literal
		want := "we``ird"
		if d == "postgres" {
			want = "\"we`ird\""
		}
		if !strings.Contains(sql, want) {
			t.Errorf("%s: identifier not escaped (%q):\n%s", d, want, sql)
		}
		// enum value a'b must survive as doubled quote in the emitted literal
		if !strings.Contains(sql, "'a''b'") {
			t.Errorf("%s: escaped enum value lost:\n%s", d, sql)
		}
		// comma inside quoted enum value must not split the value list
		if !strings.Contains(sql, "'c,d'") {
			t.Errorf("%s: comma-in-value enum split:\n%s", d, sql)
		}
	}
}

func TestExportEdgeCases(t *testing.T) {
	// dangling ref skipped; composite-PK parent FK skipped (invalid single-col FK);
	// empty action defaults CASCADE; composite PK itself all emitted
	tables := []Table{
		{ID: "t1", Name: "m", Columns: []Col{
			{Name: "a", Type: "INT", Pk: true},
			{Name: "b", Type: "INT", Pk: true},
			{Name: "g", Type: "INT", Ref: &Ref{TableID: "gone"}},
		}},
		{ID: "t2", Name: "n", Columns: []Col{
			{Name: "id", Type: "INT", Pk: true},
			{Name: "m_a", Type: "INT", Ref: &Ref{TableID: "t1", Action: "RESTRICT"}},
			{Name: "s", Type: "INT", Ref: &Ref{TableID: "t3"}},
		}},
		{ID: "t3", Name: "singles", Columns: []Col{
			{Name: "id", Type: "INT", Pk: true},
		}},
	}
	sql, err := exportSQL("mysql", tables)
	if err != nil {
		t.Fatal(err)
	}
	for _, banned := range []string{"`gone`", "CONSTRAINT `fk_n_m_a`"} {
		if strings.Contains(sql, banned) {
			t.Errorf("must be skipped (%s):\n%s", banned, sql)
		}
	}
	for _, want := range []string{"ON DELETE CASCADE", "PRIMARY KEY (`a`, `b`)"} {
		if !strings.Contains(sql, want) {
			t.Errorf("missing %q:\n%s", want, sql)
		}
	}
}

func TestExportRejects(t *testing.T) {
	if _, err := exportSQL("oracle", sample()); err == nil {
		t.Error("unknown dialect must error")
	}
	if _, err := exportSQL("mysql", nil); err == nil {
		t.Error("empty schema must error")
	}
}

// noPKParent: child.pid → parent.email, but parent has NO primary key.
func noPKParent() *Schema {
	return &Schema{Tables: []Table{
		{ID: "t1", Name: "parent", Columns: []Col{{Name: "email", Type: "VARCHAR(190)", Nn: true}}},
		{ID: "t2", Name: "child", Columns: []Col{
			{Name: "id", Type: "INT", Pk: true},
			{Name: "pid", Type: "VARCHAR(190)", Ref: &Ref{TableID: "t1"}},
		}},
	}}
}

// TestNoPKParentDropsFK: an FK onto a PK-less parent is omitted from BOTH the
// saved file and the export. MySQL requires an FK target to be unique, so
// pointing at the first column would emit invalid DDL. The FK is surfaced as a
// lint diagnostic instead of silently vanishing.
func TestNoPKParentDropsFK(t *testing.T) {
	s := noPKParent()
	if strings.Contains(mustGenSQL(s), "FOREIGN KEY") {
		t.Errorf("save emitted FK onto PK-less parent:\n%s", mustGenSQL(s))
	}
	sql, err := exportSQL("mysql", s.Tables)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(sql, "FOREIGN KEY") {
		t.Errorf("export emitted FK onto PK-less parent:\n%s", sql)
	}
	if l := s.Lint(); len(l) != 1 || !strings.Contains(l[0], "has no PK") {
		t.Errorf("expected one no-PK lint diagnostic, got %v", l)
	}
}

// TestNoPKParentSurvivesRoundTrip: the saved file must still parse back, and the
// FK must stay gone on regeneration (not resurrected by ParseDDL).
func TestNoPKParentSurvivesRoundTrip(t *testing.T) {
	s := noPKParent()
	sql1 := mustGenSQL(s)
	s2, err := ParseDDL(sql1)
	if err != nil {
		t.Fatal(err)
	}
	if got := mustGenSQL(s2); got != sql1 {
		t.Errorf("round-trip drift:\n%s\n----\n%s", sql1, got)
	}
	for _, tb := range s2.Tables {
		for _, c := range tb.Columns {
			if c.Ref != nil {
				t.Errorf("FK resurrected on round-trip: %s.%s", tb.Name, c.Name)
			}
		}
	}
}

// TestSchemaEnvelopeShapes pins the accepted POST bodies. Every schema endpoint
// takes either {"schema":{"tables":[...]}} or a bare {"tables":[...]}, and
// /export additionally carries "dialect". The embedded schemaEnvelope relies on
// encoding/json promoting its fields, so the export shape is worth asserting.
func TestSchemaEnvelopeShapes(t *testing.T) {
	const wrapped = `{"schema":{"tables":[{"id":"t1","name":"w","columns":[]}]}}`
	const bare = `{"tables":[{"id":"t1","name":"b","columns":[]}]}`

	for _, tc := range []struct{ name, body string }{{"wrapped", wrapped}, {"bare", bare}} {
		s, err := decodeSchemaJSON([]byte(tc.body))
		if err != nil {
			t.Fatalf("%s: %v", tc.name, err)
		}
		if len(s.Tables) != 1 {
			t.Errorf("%s: got %d tables, want 1", tc.name, len(s.Tables))
		}
	}

	// /export shape: dialect alongside the embedded envelope, both nestings.
	for _, tc := range []struct{ name, body, dialect string }{
		{"export wrapped", `{"dialect":"postgres","schema":{"tables":[{"id":"t1","name":"p","columns":[]}]}}`, "postgres"},
		{"export bare", `{"dialect":"sqlite","tables":[{"id":"t1","name":"s","columns":[]}]}`, "sqlite"},
	} {
		var req struct {
			Dialect string `json:"dialect"`
			schemaEnvelope
		}
		if err := json.Unmarshal([]byte(tc.body), &req); err != nil {
			t.Fatalf("%s: %v", tc.name, err)
		}
		if req.Dialect != tc.dialect {
			t.Errorf("%s: dialect = %q, want %q", tc.name, req.Dialect, tc.dialect)
		}
		if len(req.schema().Tables) != 1 {
			t.Errorf("%s: got %d tables, want 1", tc.name, len(req.schema().Tables))
		}
	}
}

// TestSaveableIsTotal: normalizeDialect maps every input onto one of the four
// known dialects, and all four have parsers, so saveable() is always true. The
// `return false` branch is therefore unreachable today.
//
// This is pinned rather than deleted because the guard is a safety net for the
// case that matters: a future dialect added to normalizeDialect without an
// emitter or parser would be saveable()==false and refused by saveFile, instead
// of silently writing a file that cannot be read back. If this test fails
// because saveable() returned false for something, the new dialect needs an
// emitter and parser — or the switch needs it explicitly.
func TestSaveableIsTotal(t *testing.T) {
	// anything normalizeDialect can produce must be saveable
	for _, d := range []string{"", "mysql", "mariadb", "postgres", "postgresql", "pg", "sqlite", "SQLITE", " MariaDB ", "oracle", "unknown", "mysql; DROP"} {
		s := &Schema{Dialect: d}
		if !s.saveable() {
			t.Errorf("saveable(%q) = false (normalized %q) — every dialect needs an emitter and parser", d, s.dialect())
		}
		// and the normalized name must be one the emitters know
		switch s.dialect() {
		case DialectMysql, DialectMariaDB, DialectPostgres, DialectSqlite:
		default:
			t.Errorf("normalizeDialect(%q) = %q, which no emitter handles", d, s.dialect())
		}
	}
	// every dialect constant must round-trip through normalization unchanged,
	// or a saved file would reopen under a different grammar
	for _, d := range []string{DialectMysql, DialectMariaDB, DialectPostgres, DialectSqlite} {
		if got := normalizeDialect(d); got != d {
			t.Errorf("normalizeDialect(%q) = %q, want identity", d, got)
		}
	}
}

// TestSchemaExportSQL: the schema-aware export path must read the dialect AND
// the sqlite types mode off the schema. The handler uses it, so a regression
// here would make the panel/Copy/Export disagree with Save.
func TestSchemaExportSQL(t *testing.T) {
	base := func() *Schema {
		return &Schema{Tables: []Table{{ID: "t1", Name: "t", Columns: []Col{
			{Name: "id", Type: "INT", Pk: true},
			{Name: "flag", Type: "BOOLEAN"},
		}}}}
	}

	t.Run("uses the schema's sqlite types mode", func(t *testing.T) {
		s := base()
		s.Dialect = DialectSqlite
		s.SqliteTypes = SqliteTypesPortable
		sql, err := schemaExportSQL(s, DialectSqlite)
		if err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(sql, "`flag` INTEGER") {
			t.Errorf("portable mode ignored:\n%s", sql)
		}

		s.SqliteTypes = SqliteTypesNative
		sql, err = schemaExportSQL(s, DialectSqlite)
		if err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(sql, "`flag` BOOLEAN") {
			t.Errorf("native mode ignored:\n%s", sql)
		}
	})

	t.Run("mode is ignored for other dialects", func(t *testing.T) {
		s := base()
		s.Dialect = DialectSqlite
		s.SqliteTypes = SqliteTypesPortable
		for _, d := range []string{DialectMysql, DialectMariaDB, DialectPostgres} {
			sql, err := schemaExportSQL(s, d)
			if err != nil {
				t.Fatalf("%s: %v", d, err)
			}
			if !strings.Contains(sql, "BOOLEAN") {
				t.Errorf("%s: sqlite mode leaked into the output:\n%s", d, sql)
			}
		}
	})

	t.Run("agrees with exportSQL for the default mode", func(t *testing.T) {
		// the two entry points must not diverge: exportSQL is the free-function
		// form, schemaExportSQL the schema-aware one
		for _, d := range []string{DialectMysql, DialectMariaDB, DialectPostgres, DialectSqlite} {
			s := base()
			s.Dialect = d
			viaSchema, err := schemaExportSQL(s, d)
			if err != nil {
				t.Fatal(err)
			}
			viaFree, err := exportSQL(d, s.Tables)
			if err != nil {
				t.Fatal(err)
			}
			if viaSchema != viaFree {
				t.Errorf("%s: schema and free export paths disagree:\n%s\n----\n%s", d, viaSchema, viaFree)
			}
		}
	})

	t.Run("empty schema errors", func(t *testing.T) {
		if _, err := schemaExportSQL(&Schema{}, DialectMysql); err == nil {
			t.Error("empty schema must error")
		}
	})
}
