// export.go — server-side dialect generator (MySQL, MariaDB, PostgreSQL, SQLite).
// Dialect grammar work lives here, not in the browser: the client POSTs its schema
// JSON and gets dialect DDL back. Saved files stay MySQL-canonical; other dialects
// are export-only, which keeps the client parser a single trivial grammar.
package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strings"
)

type reqRef struct {
	TableId string `json:"tableId"`
	Action  string `json:"action"`
}
type reqCol struct {
	Name    string  `json:"name"`
	Type    string  `json:"type"`
	Pk      bool    `json:"pk"`
	Nn      bool    `json:"nn"`
	Ai      bool    `json:"ai"`
	Ux      bool    `json:"ux"`
	Ix      bool    `json:"ix"`
	Comment string  `json:"comment"`
	Ref     *reqRef `json:"ref"`
}
type reqTable struct {
	Id      string   `json:"id"`
	Name    string   `json:"name"`
	Columns []reqCol `json:"columns"`
}
type exportReq struct {
	Dialect string `json:"dialect"`
	Schema  struct {
		Tables []reqTable `json:"tables"`
	} `json:"schema"`
}

func handleExport(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "POST only", http.StatusMethodNotAllowed)
		return
	}
	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
	var req exportReq
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "bad json: "+err.Error(), http.StatusBadRequest)
		return
	}
	sql, err := exportSQL(req.Dialect, req.Schema.Tables)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	fmt.Fprint(w, sql)
}

func exportSQL(dialect string, tables []reqTable) (string, error) {
	if len(tables) == 0 {
		return "", errors.New("schema has no tables")
	}
	switch strings.ToLower(dialect) {
	case "mysql":
		return buildMysql(tables, "-- Generated by erd-creator (MySQL)"), nil
	case "mariadb":
		return buildMysql(tables, "-- Generated by erd-creator (MariaDB)"), nil
	case "postgres", "postgresql":
		return buildPostgres(tables), nil
	case "sqlite":
		return buildSqlite(tables), nil
	default:
		return "", fmt.Errorf("unknown dialect %q (want mysql, mariadb, postgres, sqlite)", dialect)
	}
}

// ---- helpers ----

func quoteTick(n string) string { return "`" + strings.ReplaceAll(n, "`", "``") + "`" }
func quoteDQ(n string) string   { return `"` + strings.ReplaceAll(n, `"`, `""`) + `"` }
func sqlStr(s string) string    { return "'" + strings.ReplaceAll(s, "'", "''") + "'" }

func splitType(ty string) (string, string) {
	if i := strings.Index(ty, "("); i >= 0 && strings.HasSuffix(ty, ")") {
		return strings.ToUpper(ty[:i]), ty[i+1 : len(ty)-1]
	}
	return strings.ToUpper(ty), ""
}

// splitTop splits on top-level commas, respecting parens and ” escaped strings.
func splitTop(s string) []string {
	var out []string
	depth, inStr, start := 0, false, 0
	for i := 0; i < len(s); i++ { // classic loop: body's i++ must skip the escaped quote
		c := s[i]
		switch {
		case c == '\'' && inStr && i+1 < len(s) && s[i+1] == '\'':
			i++ // skip second quote of '' escape
		case c == '\'':
			inStr = !inStr
		case inStr:
		case c == '(':
			depth++
		case c == ')':
			depth--
		case c == ',' && depth == 0:
			out = append(out, strings.TrimSpace(s[start:i]))
			start = i + 1
		}
	}
	if rest := strings.TrimSpace(s[start:]); rest != "" {
		out = append(out, rest)
	}
	return out
}

func enumValues(ty string) []string {
	base, args := splitType(ty)
	if base != "ENUM" {
		return nil
	}
	var vals []string
	for _, v := range splitTop(args) {
		if len(v) >= 2 && strings.HasPrefix(v, "'") && strings.HasSuffix(v, "'") {
			v = strings.ReplaceAll(v[1:len(v)-1], "''", "'")
		}
		vals = append(vals, v)
	}
	return vals
}

func baseOf(ty string) string {
	base, _ := splitType(ty)
	return base
}

func isInt(base string) bool {
	switch base {
	case "INT", "BIGINT", "SMALLINT", "TINYINT":
		return true
	}
	return false
}

func findTable(tables []reqTable, id string) *reqTable {
	for i := range tables {
		if tables[i].Id == id {
			return &tables[i]
		}
	}
	return nil
}

// pkCol mirrors the JS generate(): sole PK, else first column; ok=false only
// for composite PK (a single-col FK onto it is invalid DDL — caller skips; lint warns).
func pkCol(t reqTable) (reqCol, bool) {
	var pk reqCol
	n := 0
	for _, c := range t.Columns {
		if c.Pk {
			n++
			pk = c
		}
	}
	switch {
	case n > 1:
		return reqCol{}, false
	case n == 1:
		return pk, true
	case len(t.Columns) > 0:
		return t.Columns[0], true
	}
	return reqCol{}, false
}

func refCols(t reqTable) []reqCol {
	var out []reqCol
	for _, c := range t.Columns {
		if c.Ref != nil {
			out = append(out, c)
		}
	}
	return out
}

func fkAction(c reqCol) string {
	if c.Ref.Action == "" {
		return "CASCADE"
	}
	return c.Ref.Action
}

func pkLine(t reqTable, q func(string) string) string {
	var pks []string
	for _, c := range t.Columns {
		if c.Pk {
			pks = append(pks, q(c.Name))
		}
	}
	if len(pks) == 0 {
		return ""
	}
	return "  PRIMARY KEY (" + strings.Join(pks, ", ") + ")"
}

// ---- MySQL / MariaDB ----

func buildMysql(tables []reqTable, header string) string {
	out := []string{header}
	for _, t := range tables {
		if len(t.Columns) == 0 {
			continue // empty table → invalid DDL (UI guards; parse can't produce)
		}
		var lines []string
		for _, c := range t.Columns {
			base, args := splitType(c.Type)
			ty := base
			if args != "" && !(c.Ai && isInt(base)) {
				ty = base + "(" + args + ")"
			}
			s := "  " + quoteTick(c.Name) + " " + ty
			if c.Nn || c.Pk {
				s += " NOT NULL"
			}
			if c.Ai && isInt(base) {
				s += " AUTO_INCREMENT"
			}
			if c.Ux {
				s += " UNIQUE"
			}
			if c.Comment != "" {
				s += " COMMENT " + sqlStr(c.Comment)
			}
			lines = append(lines, s)
		}
		if l := pkLine(t, quoteTick); l != "" {
			lines = append(lines, l)
		}
		for _, c := range t.Columns {
			if c.Ix {
				lines = append(lines, "  KEY "+quoteTick("idx_"+t.Name+"_"+c.Name)+" ("+quoteTick(c.Name)+")")
			}
		}
		for _, c := range refCols(t) {
			rt := findTable(tables, c.Ref.TableId)
			if rt == nil {
				continue
			}
			rp, ok := pkCol(*rt)
			if !ok {
				continue // composite PK parent → invalid single-col FK; client lint warns
			}
			lines = append(lines, fmt.Sprintf(
				"  CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s) ON DELETE %s",
				quoteTick("fk_"+t.Name+"_"+c.Name), quoteTick(c.Name), quoteTick(rt.Name), quoteTick(rp.Name), fkAction(c)))
		}
		out = append(out, "CREATE TABLE "+quoteTick(t.Name)+" (\n"+strings.Join(lines, ",\n")+"\n) ENGINE=InnoDB;")
	}
	return strings.Join(out, "\n") + "\n"
}

// ---- PostgreSQL ----

func pgType(c reqCol) (string, string) { // type + inline extra (CHECK for ENUM)
	base, args := splitType(c.Type)
	switch base {
	case "TINYINT":
		base = "SMALLINT"
	case "DATETIME":
		base = "TIMESTAMP"
	case "JSON":
		base = "JSONB"
	case "ENUM":
		if vals := enumValues(c.Type); vals != nil {
			quoted := make([]string, len(vals))
			for i, v := range vals {
				quoted[i] = sqlStr(v)
			}
			return "TEXT", fmt.Sprintf("CHECK (%s IN (%s))", quoteDQ(c.Name), strings.Join(quoted, ", "))
		}
		base = "TEXT"
	}
	if args != "" && base != "TEXT" {
		return base + "(" + args + ")", ""
	}
	return base, ""
}

func buildPostgres(tables []reqTable) string {
	out := []string{"-- Generated by erd-creator (PostgreSQL)"}
	for _, t := range tables {
		if len(t.Columns) == 0 {
			continue
		}
		var lines, post []string
		for _, c := range t.Columns {
			ty, extra := pgType(c)
			if c.Ai && isInt(ty) {
				ty += " GENERATED BY DEFAULT AS IDENTITY"
			}
			s := "  " + quoteDQ(c.Name) + " " + ty
			if c.Nn || c.Pk {
				s += " NOT NULL"
			}
			if c.Ux {
				s += " UNIQUE"
			}
			if extra != "" {
				s += " " + extra
			}
			lines = append(lines, s)
			if c.Comment != "" {
				post = append(post, fmt.Sprintf("COMMENT ON COLUMN %s.%s IS %s;",
					quoteDQ(t.Name), quoteDQ(c.Name), sqlStr(c.Comment)))
			}
			if c.Ix {
				post = append(post, fmt.Sprintf("CREATE INDEX %s ON %s (%s);",
					quoteDQ("idx_"+t.Name+"_"+c.Name), quoteDQ(t.Name), quoteDQ(c.Name)))
			}
		}
		if l := pkLine(t, quoteDQ); l != "" {
			lines = append(lines, l)
		}
		for _, c := range refCols(t) {
			rt := findTable(tables, c.Ref.TableId)
			if rt == nil {
				continue
			}
			rp, ok := pkCol(*rt)
			if !ok {
				continue
			}
			lines = append(lines, fmt.Sprintf(
				"  CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s) ON DELETE %s",
				quoteDQ("fk_"+t.Name+"_"+c.Name), quoteDQ(c.Name), quoteDQ(rt.Name), quoteDQ(rp.Name), fkAction(c)))
		}
		out = append(out, "CREATE TABLE "+quoteDQ(t.Name)+" (\n"+strings.Join(lines, ",\n")+"\n);")
		out = append(out, post...)
	}
	return strings.Join(out, "\n") + "\n"
}

// ---- SQLite ----

// ponytail: SQLite lacks COMMENT and ENUM; comments become -- lines, ENUM becomes
// TEXT + inline CHECK, AUTO_INCREMENT relies on the INTEGER PRIMARY KEY rowid alias.
func buildSqlite(tables []reqTable) string {
	out := []string{"-- Generated by erd-creator (SQLite)"}
	for _, t := range tables {
		if len(t.Columns) == 0 {
			continue
		}
		var lines, post []string
		pks := make([]reqCol, 0, 2)
		for _, c := range t.Columns {
			if c.Pk {
				pks = append(pks, c)
			}
		}
		// rowid alias: single integer PK → inline INTEGER PRIMARY KEY, auto-assign for free
		aiPk := len(pks) == 1 && pks[0].Ai && isInt(baseOf(pks[0].Type))
		for _, c := range t.Columns {
			if c.Comment != "" {
				lines = append(lines, "  -- "+c.Name+": "+c.Comment)
			}
			base, args := splitType(c.Type)
			ty, check := base, ""
			switch base {
			case "ENUM":
				ty = "TEXT"
				if vals := enumValues(c.Type); vals != nil {
					quoted := make([]string, len(vals))
					for i, v := range vals {
						quoted[i] = sqlStr(v)
					}
					check = fmt.Sprintf("CHECK (%s IN (%s))", quoteTick(c.Name), strings.Join(quoted, ", "))
				}
			case "BOOLEAN":
				ty = "INTEGER"
			case "DATETIME", "TIMESTAMP":
				ty = "TEXT"
			}
			if args != "" && ty == base {
				ty = base + "(" + args + ")"
			}
			if aiPk && c.Pk {
				lines = append(lines, "  "+quoteTick(c.Name)+" INTEGER PRIMARY KEY")
				continue
			}
			s := "  " + quoteTick(c.Name) + " " + ty
			if c.Nn || c.Pk {
				s += " NOT NULL"
			}
			if c.Ux {
				s += " UNIQUE"
			}
			if check != "" {
				s += " " + check
			}
			lines = append(lines, s)
			if c.Ix {
				post = append(post, fmt.Sprintf("CREATE INDEX IF NOT EXISTS %s ON %s (%s);",
					quoteTick("idx_"+t.Name+"_"+c.Name), quoteTick(t.Name), quoteTick(c.Name)))
			}
		}
		if !aiPk {
			if l := pkLine(t, quoteTick); l != "" {
				lines = append(lines, l)
			}
		}
		for _, c := range refCols(t) {
			rt := findTable(tables, c.Ref.TableId)
			if rt == nil {
				continue
			}
			rp, ok := pkCol(*rt)
			if !ok {
				continue
			}
			lines = append(lines, fmt.Sprintf(
				"  FOREIGN KEY (%s) REFERENCES %s (%s) ON DELETE %s",
				quoteTick(c.Name), quoteTick(rt.Name), quoteTick(rp.Name), fkAction(c)))
		}
		out = append(out, "CREATE TABLE "+quoteTick(t.Name)+" (\n"+strings.Join(lines, ",\n")+"\n);")
		out = append(out, post...)
	}
	return strings.Join(out, "\n") + "\n"
}
