package main

import (
	"encoding/json"
	"strings"
	"testing"
)

func sample() []Table {
	return []Table{
		{Id: "t1", Name: "users", Columns: []Col{
			{Name: "id", Type: "INT", Pk: true, Nn: true, Ai: true, Comment: "pk"},
			{Name: "email", Type: "VARCHAR(190)", Nn: true, Ux: true, Ix: true},
			{Name: "status", Type: "ENUM('active','banned')"},
		}},
		{Id: "t2", Name: "posts", Columns: []Col{
			{Name: "id", Type: "BIGINT", Pk: true, Nn: true, Ai: true},
			{Name: "user_id", Type: "INT", Ref: &Ref{TableId: "t1", Action: "SET NULL"}},
		}},
	}
}

func TestExportDialects(t *testing.T) {
	cases := []struct{ dialect, want string }{
		{"mysql", "AUTO_INCREMENT"},
		{"mysql", "ENUM('active','banned')"},
		{"mysql", "COMMENT 'pk'"},
		{"mariadb", "(MariaDB)"},
		{"mariadb", "ON DELETE SET NULL"},
		{"postgres", "GENERATED BY DEFAULT AS IDENTITY"},
		{"postgres", "COMMENT ON COLUMN"},
		{"postgres", "CREATE INDEX"},
		{"postgres", `CHECK ("status" IN ('active', 'banned'))`},
		{"sqlite", "INTEGER PRIMARY KEY"},
		{"sqlite", "CHECK (`status` IN ('active', 'banned'))"},
	}
	for _, c := range cases {
		sql, err := exportSQL(c.dialect, sample())
		if err != nil {
			t.Fatalf("%s: %v", c.dialect, err)
		}
		if !strings.Contains(sql, c.want) {
			t.Errorf("%s output missing %q:\n%s", c.dialect, c.want, sql)
		}
	}
}

func TestExportEscaping(t *testing.T) {
	tables := []Table{
		{Id: "t1", Name: "we`ird", Columns: []Col{
			{Name: "a`b", Type: "INT", Pk: true},
			{Name: "c", Type: "VARCHAR(10)", Comment: "it's \"quoted\""},
			{Name: "e", Type: "ENUM('a''b','c,d')"},
		}},
	}
	for _, d := range []string{"mysql", "postgres", "sqlite"} {
		sql, err := exportSQL(d, tables)
		if err != nil {
			t.Fatalf("%s: %v", d, err)
		}
		// mysql/sqlite double the backtick; PG wraps in "" and leaves ` literal
		want := "we``ird"
		if d == "postgres" {
			want = "\"we`ird\""
		}
		if !strings.Contains(sql, want) {
			t.Errorf("%s: identifier not escaped (%q):\n%s", d, want, sql)
		}
		// enum value a'b must survive as doubled quote in the emitted literal
		if !strings.Contains(sql, "'a''b'") {
			t.Errorf("%s: escaped enum value lost:\n%s", d, sql)
		}
		// comma inside quoted enum value must not split the value list
		if !strings.Contains(sql, "'c,d'") {
			t.Errorf("%s: comma-in-value enum split:\n%s", d, sql)
		}
	}
}

func TestExportEdgeCases(t *testing.T) {
	// dangling ref skipped; composite-PK parent FK skipped (invalid single-col FK);
	// empty action defaults CASCADE; composite PK itself all emitted
	tables := []Table{
		{Id: "t1", Name: "m", Columns: []Col{
			{Name: "a", Type: "INT", Pk: true},
			{Name: "b", Type: "INT", Pk: true},
			{Name: "g", Type: "INT", Ref: &Ref{TableId: "gone"}},
		}},
		{Id: "t2", Name: "n", Columns: []Col{
			{Name: "id", Type: "INT", Pk: true},
			{Name: "m_a", Type: "INT", Ref: &Ref{TableId: "t1", Action: "RESTRICT"}},
			{Name: "s", Type: "INT", Ref: &Ref{TableId: "t3"}},
		}},
		{Id: "t3", Name: "singles", Columns: []Col{
			{Name: "id", Type: "INT", Pk: true},
		}},
	}
	sql, err := exportSQL("mysql", tables)
	if err != nil {
		t.Fatal(err)
	}
	for _, banned := range []string{"`gone`", "CONSTRAINT `fk_n_m_a`"} {
		if strings.Contains(sql, banned) {
			t.Errorf("must be skipped (%s):\n%s", banned, sql)
		}
	}
	for _, want := range []string{"ON DELETE CASCADE", "PRIMARY KEY (`a`, `b`)"} {
		if !strings.Contains(sql, want) {
			t.Errorf("missing %q:\n%s", want, sql)
		}
	}
}

func TestExportRejects(t *testing.T) {
	if _, err := exportSQL("oracle", sample()); err == nil {
		t.Error("unknown dialect must error")
	}
	if _, err := exportSQL("mysql", nil); err == nil {
		t.Error("empty schema must error")
	}
}

// TestGenSQLMatchesBuildMysql pins the single-emitter contract. GenSQL delegates
// to buildMysql today, so this is deliberately tautological — it exists to fail
// loudly if anyone re-inlines a second MySQL emitter, which is exactly how the
// save/export drift happened (save dropped an FK onto a PK-less parent, export
// emitted one onto a non-unique column). Cases cover the edges where they differed.
func TestGenSQLMatchesBuildMysql(t *testing.T) {
	schemas := map[string]*Schema{
		"sample":       sampleSchema(),
		"no-pk parent": noPKParent(),
		"composite pk": {Tables: []Table{{Id: "t1", Name: "m", Columns: []Col{{Name: "a", Type: "INT", Pk: true}, {Name: "b", Type: "INT", Pk: true}}}}},
		"empty table":  {Tables: []Table{{Id: "t1", Name: "empty"}}},
		"escaping":     {Tables: []Table{{Id: "t1", Name: "we`ird", Columns: []Col{{Name: "a`b", Type: "INT", Pk: true}, {Name: "c", Type: "VARCHAR(10)", Comment: "it's \"quoted\""}}}}},
	}
	for name, s := range schemas {
		saved := s.GenSQL()
		exported := buildMysql(s.Tables, "-- Generated by erd-creator")
		if saved != exported {
			t.Errorf("%s: save/export drift:\n--- GenSQL ---\n%s\n--- buildMysql ---\n%s", name, saved, exported)
		}
	}
}

// noPKParent: child.pid → parent.email, but parent has NO primary key.
func noPKParent() *Schema {
	return &Schema{Tables: []Table{
		{Id: "t1", Name: "parent", Columns: []Col{{Name: "email", Type: "VARCHAR(190)", Nn: true}}},
		{Id: "t2", Name: "child", Columns: []Col{
			{Name: "id", Type: "INT", Pk: true},
			{Name: "pid", Type: "VARCHAR(190)", Ref: &Ref{TableId: "t1"}},
		}},
	}}
}

// TestNoPKParentDropsFK: an FK onto a PK-less parent is omitted from BOTH the
// saved file and the export. MySQL requires an FK target to be unique, so
// pointing at the first column would emit invalid DDL. The FK is surfaced as a
// lint diagnostic instead of silently vanishing.
func TestNoPKParentDropsFK(t *testing.T) {
	s := noPKParent()
	if strings.Contains(s.GenSQL(), "FOREIGN KEY") {
		t.Errorf("save emitted FK onto PK-less parent:\n%s", s.GenSQL())
	}
	sql, err := exportSQL("mysql", s.Tables)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(sql, "FOREIGN KEY") {
		t.Errorf("export emitted FK onto PK-less parent:\n%s", sql)
	}
	if l := s.Lint(); len(l) != 1 || !strings.Contains(l[0], "has no PK") {
		t.Errorf("expected one no-PK lint diagnostic, got %v", l)
	}
}

// TestNoPKParentSurvivesRoundTrip: the saved file must still parse back, and the
// FK must stay gone on regeneration (not resurrected by ParseDDL).
func TestNoPKParentSurvivesRoundTrip(t *testing.T) {
	s := noPKParent()
	sql1 := s.GenSQL()
	s2, err := ParseDDL(sql1)
	if err != nil {
		t.Fatal(err)
	}
	if got := s2.GenSQL(); got != sql1 {
		t.Errorf("round-trip drift:\n%s\n----\n%s", sql1, got)
	}
	for _, tb := range s2.Tables {
		for _, c := range tb.Columns {
			if c.Ref != nil {
				t.Errorf("FK resurrected on round-trip: %s.%s", tb.Name, c.Name)
			}
		}
	}
}

// TestSchemaEnvelopeShapes pins the accepted POST bodies. Every schema endpoint
// takes either {"schema":{"tables":[...]}} or a bare {"tables":[...]}, and
// /export additionally carries "dialect". The embedded schemaEnvelope relies on
// encoding/json promoting its fields, so the export shape is worth asserting.
func TestSchemaEnvelopeShapes(t *testing.T) {
	const wrapped = `{"schema":{"tables":[{"id":"t1","name":"w","columns":[]}]}}`
	const bare = `{"tables":[{"id":"t1","name":"b","columns":[]}]}`

	for _, tc := range []struct{ name, body string }{{"wrapped", wrapped}, {"bare", bare}} {
		s, err := decodeSchemaJSON([]byte(tc.body))
		if err != nil {
			t.Fatalf("%s: %v", tc.name, err)
		}
		if len(s.Tables) != 1 {
			t.Errorf("%s: got %d tables, want 1", tc.name, len(s.Tables))
		}
	}

	// /export shape: dialect alongside the embedded envelope, both nestings.
	for _, tc := range []struct{ name, body, dialect string }{
		{"export wrapped", `{"dialect":"postgres","schema":{"tables":[{"id":"t1","name":"p","columns":[]}]}}`, "postgres"},
		{"export bare", `{"dialect":"sqlite","tables":[{"id":"t1","name":"s","columns":[]}]}`, "sqlite"},
	} {
		var req struct {
			Dialect string `json:"dialect"`
			schemaEnvelope
		}
		if err := json.Unmarshal([]byte(tc.body), &req); err != nil {
			t.Fatalf("%s: %v", tc.name, err)
		}
		if req.Dialect != tc.dialect {
			t.Errorf("%s: dialect = %q, want %q", tc.name, req.Dialect, tc.dialect)
		}
		if len(req.schema().Tables) != 1 {
			t.Errorf("%s: got %d tables, want 1", tc.name, len(req.schema().Tables))
		}
	}
}
