package main

import (
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestHasClausePrefixTable(t *testing.T) {
	trues := []string{
		"PRIMARY KEY (`id`)",
		"UNIQUE KEY `ux` (`a`)",
		"CONSTRAINT `fk` FOREIGN KEY (`a`) REFERENCES `t` (`id`)",
		"KEY `idx` (`a`)",
		"INDEX `idx` (`a`)",
		"FOREIGN KEY (`x`) REFERENCES `y` (`id`)",
		"primary key (`id`)",
		"key `idx` (`a`)",
		"constraint `fk` foreign key (`a`) references `t` (`id`)",
		"KEY",
		"PRIMARY KEY",
		"INDEX",
		"KEY\t`idx` (`a`)",
	}
	for _, s := range trues {
		if !hasClausePrefix(s) {
			t.Errorf("hasClausePrefix(%q) = false, want true", s)
		}
	}
	falses := []string{
		"",
		"`id` INT NOT NULL",
		"name TEXT",
		"PRIMARY",
		"PRIMARY KEYSTONE (`a`)",
		"KEYSTONE (`a`)",
		"INDEXED (`a`)",
		"CONSTRAINTX (`a`)",
		"FOREIGN KEYSTONE (`a`)",
		"UNIQUE KEYX (`a`)",
		"KEY(`a`)",
		"PRIMARY KEY(`id`)",
		"INDEX(`a`)",
		"CONSTRAINT(`fk`)",
	}
	for _, s := range falses {
		if hasClausePrefix(s) {
			t.Errorf("hasClausePrefix(%q) = true, want false", s)
		}
	}
}

func TestEmptyBodyMysqlLine(t *testing.T) {
	tbl := &Table{ID: "t1", Name: "a"}
	var pending []pendingFK
	if err := parseMysqlBodyLine("", "", tbl, &pending, 1); err == nil {
		t.Error("empty body should error, not panic or append")
	}
	if len(tbl.Columns) != 0 {
		t.Errorf("empty body appended %d columns", len(tbl.Columns))
	}
	if _, err := ParseDDL("-- Generated by erd-creator\nCREATE TABLE `a` (\n,\n) ENGINE=InnoDB;\n"); err == nil {
		t.Error("mysql stray-comma body line should reject the file")
	}
}

func TestEmptyBodyPgSqlite(t *testing.T) {
	pg := "-- Generated by erd-creator (PostgreSQL)\nCREATE TABLE \"a\" (\n,\n);\n"
	if _, err := ParseDDL(pg); err == nil {
		t.Error("postgres empty body line should error")
	}
	lite := "-- Generated by erd-creator (SQLite)\nCREATE TABLE `a` (\n,\n);\n"
	if _, err := ParseDDL(lite); err == nil {
		t.Error("sqlite empty body line should error")
	}
}

func TestOpenFileGaps(t *testing.T) {
	dir := t.TempDir()

	rec := httptest.NewRecorder()
	openFile(rec, filepath.Join(dir, "gone.sql"), "gone.sql")
	if rec.Code != http.StatusNotFound {
		t.Errorf("missing: code %d, want 404", rec.Code)
	}
	if !strings.Contains(rec.Body.String(), "gone.sql") {
		t.Errorf("404 should name the file: %q", rec.Body.String())
	}

	// A directory at the path is unreadable as a file on any user, unlike
	// chmod 000 which root ignores. Must be 500 without leaking the path.
	rec = httptest.NewRecorder()
	openFile(rec, dir, "sub")
	if rec.Code != http.StatusInternalServerError {
		t.Errorf("unreadable: code %d, want 500", rec.Code)
	}
	if !strings.Contains(rec.Body.String(), "open failed") {
		t.Errorf("500 should say 'open failed': %q", rec.Body.String())
	}
	if strings.Contains(rec.Body.String(), dir) {
		t.Errorf("500 must not leak resolved path: %q", rec.Body.String())
	}

	if err := os.WriteFile(filepath.Join(dir, "junk.sql"), []byte("NOT SQL AT ALL\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	rec = httptest.NewRecorder()
	openFile(rec, filepath.Join(dir, "junk.sql"), "junk.sql")
	if rec.Code != http.StatusBadRequest {
		t.Errorf("corrupt: code %d, want 400", rec.Code)
	}
}

func TestTempCleanupGaps(t *testing.T) {
	dir := t.TempDir()

	removeTemp(filepath.Join(dir, "nonexistent.tmp"))

	f, err := createTemp(dir)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(f.Name()); err != nil {
		t.Errorf("createTemp file missing: %v", err)
	}
	if !strings.Contains(filepath.Base(f.Name()), ".save-") {
		t.Errorf("temp name should carry .save- prefix: %q", f.Name())
	}
	discardTemp(f)
	if _, err := os.Stat(f.Name()); !os.IsNotExist(err) {
		t.Errorf("discardTemp left %q behind (err=%v)", f.Name(), err)
	}

	sweepTrash(filepath.Join(dir, "no-store"))
}

func TestSaveNoTempOnFailure(t *testing.T) {
	dir := t.TempDir()
	h := handleFiles(dir)
	body := `{"dialect":"mysql","tables":[{"id":"t1","name":"t","columns":[{"name":"a","type":"INT);DROP TABLE x;--"}]}]}`
	rec := httptest.NewRecorder()
	h.ServeHTTP(rec, httptest.NewRequest("PUT", "/api/files/evil.sql", strings.NewReader(body)))
	if rec.Code != http.StatusBadRequest {
		t.Fatalf("code %d, want 400 (%s)", rec.Code, rec.Body)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), ".save-") {
			t.Errorf("failed save left temp behind: %s", e.Name())
		}
	}
}

func TestWriteJSONTextNoPanic(t *testing.T) {
	rec := httptest.NewRecorder()
	writeJSON(rec, sampleSchema())
	if rec.Code != http.StatusOK {
		t.Errorf("writeJSON code %d, want 200", rec.Code)
	}
	if !strings.Contains(rec.Body.String(), "users") {
		t.Errorf("writeJSON body missing schema: %q", rec.Body.String())
	}

	rec = httptest.NewRecorder()
	writeText(rec, "hello")
	if rec.Code != http.StatusOK {
		t.Errorf("writeText code %d, want 200", rec.Code)
	}
	if rec.Body.String() != "hello" {
		t.Errorf("writeText body = %q, want hello", rec.Body.String())
	}
}
