// grammar_postgres_test.go — the PostgreSQL saved-file grammar: golden output,
// generate↔parse round-trip, escaping, and dialect detection.
//
// The mysql grammar has had its own suite since the parser was ported. Postgres
// gained a parser later, and two parsers for two emitters is exactly the shape
// that produced the earlier save/export drift — so each dialect is pinned
// independently rather than trusting that "the other one is covered".
package main

import (
	"strings"
	"testing"
)

// pgSchema returns sampleSchema tagged as postgres.
func pgSchema() *Schema {
	s := sampleSchema()
	s.Dialect = DialectPostgres
	return s
}

// TestPostgresGolden pins the exact saved-file bytes for postgres. Like
// TestGenSQLGolden, this is the test that fails on an output-format change;
// updating it is a deliberate act, since the format is a contract with files
// already on disk.
func TestPostgresGolden(t *testing.T) {
	const want = `-- Generated by erd-creator (PostgreSQL)
CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "email" VARCHAR(190) NOT NULL UNIQUE,
  "status" TEXT CHECK ("status" IN ('active', 'banned')),
  PRIMARY KEY ("id")
);
COMMENT ON COLUMN "users"."id" IS 'pk';
CREATE TABLE "posts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" INT,
  "tag" VARCHAR(40),
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_posts_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL
);
CREATE INDEX "idx_posts_tag" ON "posts" ("tag");
`
	if got := mustGenSQL(pgSchema()); got != want {
		t.Errorf("postgres saved-file format drifted.\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// TestPostgresRoundTripStable: emit → parse → emit must be byte-identical. The
// model itself is NOT expected to survive unchanged (see TestPostgresTypeMapping
// below); what must hold is that the second emit matches the first.
func TestPostgresRoundTripStable(t *testing.T) {
	sql1 := mustGenSQL(pgSchema())
	s2, err := ParseDDL(sql1)
	if err != nil {
		t.Fatal(err)
	}
	if s2.Dialect != DialectPostgres {
		t.Errorf("dialect lost on parse: got %q", s2.Dialect)
	}
	if sql2 := mustGenSQL(s2); sql1 != sql2 {
		t.Errorf("round-trip drift:\n%s\n----\n%s", sql1, sql2)
	}
	// FK survived with its action intact — this regressed once when the extra
	// constraint-name capture group shifted the action's submatch index.
	if got := s2.Tables[1].Columns[1].Ref; got == nil || got.Action != "SET NULL" {
		t.Errorf("FK action lost in round-trip: %+v", got)
	}
}

// TestPostgresTypeMapping documents which types survive a round-trip exactly
// and which do not.
//
// TINYINT and DATETIME are genuinely lossy: Postgres has no such types, so the
// information does not exist in that representation and cannot be recovered.
// SMALLINT and TIMESTAMP are valid in every dialect we emit, so this loss is
// harmless in practice.
//
// JSON and ENUM round-trip exactly. Both used to not: JSON came back as JSONB
// (a Postgres-only name, which made the model unportable — see
// TestPostgresReopenIsPortable), and ENUM's value list came back respaced.
func TestPostgresTypeMapping(t *testing.T) {
	exact := []string{
		"INT", "BIGINT", "SMALLINT", "DECIMAL(10,2)", "VARCHAR(190)", "TEXT",
		"BOOLEAN", "DATE", "TIMESTAMP", "JSON",
		"ENUM('a','b')", "ENUM('x''y','z,w')", "ENUM('a','b','c')",
		// Array forms round-trip exactly, including the two where the suffix has
		// to survive the dialect's own mapping (JSON -> JSONB, and a
		// parameterised base). The suffix is re-attached after the mapping, so
		// `JSON[]` comes back as `JSON[]` rather than a bare `JSON`.
		"INT[]", "TEXT[]", "VARCHAR(190)[]", "DECIMAL(10,2)[]", "JSON[]",
	}
	for _, in := range exact {
		s := &Schema{Dialect: DialectPostgres, Tables: []Table{
			{ID: "t1", Name: "t", Columns: []Col{{Name: "c", Type: in}}},
		}}
		parsed, err := ParseDDL(mustGenSQL(s))
		if err != nil {
			t.Fatalf("%s: %v", in, err)
		}
		if got := parsed.Tables[0].Columns[0].Type; got != in {
			t.Errorf("%s: round-tripped to %q, want it unchanged", in, got)
		}
	}

	// The two known-lossy mappings, asserted so a change to them is deliberate.
	lossy := map[string]string{"TINYINT": "SMALLINT", "DATETIME": "TIMESTAMP"}
	for in, want := range lossy {
		s := &Schema{Dialect: DialectPostgres, Tables: []Table{
			{ID: "t1", Name: "t", Columns: []Col{{Name: "c", Type: in}}},
		}}
		parsed, err := ParseDDL(mustGenSQL(s))
		if err != nil {
			t.Fatalf("%s: %v", in, err)
		}
		if got := parsed.Tables[0].Columns[0].Type; got != want {
			t.Errorf("%s: round-tripped to %q, want %q", in, got, want)
		}
	}
}

// TestPostgresReopenIsPortable guards the bug that made a postgres file unsafe
// to reopen and re-export: JSONB is a Postgres-only type name, so leaving it in
// the model produced `c` JSONB when the reopened schema was exported to mysql
// or sqlite — invalid DDL in both.
func TestPostgresReopenIsPortable(t *testing.T) {
	for _, in := range []string{"JSON", "TINYINT", "DATETIME", "ENUM('a','b')", "INT", "VARCHAR(9)"} {
		s := &Schema{Dialect: DialectPostgres, Tables: []Table{
			{ID: "t1", Name: "t", Columns: []Col{{Name: "c", Type: in}}},
		}}
		reopened, err := ParseDDL(mustGenSQL(s))
		if err != nil {
			t.Fatalf("%s: %v", in, err)
		}
		// Only the non-postgres dialects must be free of JSONB: it is valid
		// Postgres, and the emitter maps JSON -> JSONB there on purpose.
		for _, dialect := range []string{"mysql", "sqlite"} {
			sql, err := exportSQL(dialect, reopened.Tables)
			if err != nil {
				t.Fatalf("%s/%s: %v", in, dialect, err)
			}
			if strings.Contains(sql, "JSONB") {
				t.Errorf("%s reopened then exported to %s contains JSONB (postgres-only):\n%s", in, dialect, sql)
			}
		}
	}
}

// TestPostgresJSONBInput: a hand-written file already using JSONB is accepted
// and normalized to the portable model type, so it re-emits as JSONB (the
// emitter's choice) and stays valid everywhere else.
func TestPostgresJSONBInput(t *testing.T) {
	hand := "-- Generated by erd-creator (PostgreSQL)\nCREATE TABLE \"t\" (\n  \"c\" JSONB\n);\n"
	parsed, err := ParseDDL(hand)
	if err != nil {
		t.Fatal(err)
	}
	if got := parsed.Tables[0].Columns[0].Type; got != "JSON" {
		t.Errorf("JSONB should normalize to JSON in the model, got %q", got)
	}
	if got := mustGenSQL(parsed); got != hand {
		t.Errorf("hand-written JSONB file did not re-emit unchanged:\n%s\n----\n%s", hand, got)
	}
}

// TestPostgresRoundTripEscaping: identifiers with embedded quotes and comments
// with embedded single quotes must survive.
func TestPostgresRoundTripEscaping(t *testing.T) {
	s := &Schema{Dialect: DialectPostgres, Tables: []Table{{ID: "t1", Name: `we"ird`, Columns: []Col{
		{Name: `a"b`, Type: "INT", Pk: true},
		{Name: "c", Type: "VARCHAR(10)", Comment: `it's "quoted"`},
		{Name: "e", Type: "ENUM('a''b','c,d')"},
	}}}}
	sql := mustGenSQL(s)
	parsed, err := ParseDDL(sql)
	if err != nil {
		t.Fatal(err)
	}
	if got := mustGenSQL(parsed); got != sql {
		t.Errorf("escaping drift:\n%s\n----\n%s", sql, got)
	}
	if parsed.Tables[0].Name != `we"ird` || parsed.Tables[0].Columns[0].Name != `a"b` {
		t.Error("double-quoted identifiers mangled")
	}
	if got := parsed.Tables[0].Columns[1].Comment; got != `it's "quoted"` {
		t.Errorf("comment mangled: %q", got)
	}
}

// TestPostgresEdgeCases: the FK-eligibility rules must match the mysql path.
func TestPostgresEdgeCases(t *testing.T) {
	t.Run("composite PK parent drops FK", func(t *testing.T) {
		s := &Schema{Dialect: DialectPostgres, Tables: []Table{
			{ID: "t1", Name: "m", Columns: []Col{{Name: "a", Type: "INT", Pk: true}, {Name: "b", Type: "INT", Pk: true}}},
			{ID: "t2", Name: "c", Columns: []Col{{Name: "id", Type: "INT", Pk: true}, {Name: "mid", Type: "INT", Ref: &Ref{TableID: "t1"}}}},
		}}
		sql := mustGenSQL(s)
		if strings.Contains(sql, "FOREIGN KEY") {
			t.Errorf("FK onto composite PK must not be emitted:\n%s", sql)
		}
		parsed, err := ParseDDL(sql)
		if err != nil {
			t.Fatal(err)
		}
		if n := len(pkCols(parsed.Tables[0])); n != 2 {
			t.Errorf("composite PK lost: %d cols", n)
		}
	})

	t.Run("no-PK parent drops FK", func(t *testing.T) {
		s := &Schema{Dialect: DialectPostgres, Tables: []Table{
			{ID: "t1", Name: "p", Columns: []Col{{Name: "email", Type: "VARCHAR(9)"}}},
			{ID: "t2", Name: "c", Columns: []Col{{Name: "id", Type: "INT", Pk: true}, {Name: "pid", Type: "VARCHAR(9)", Ref: &Ref{TableID: "t1"}}}},
		}}
		if strings.Contains(mustGenSQL(s), "FOREIGN KEY") {
			t.Errorf("FK onto PK-less parent must not be emitted:\n%s", mustGenSQL(s))
		}
	})

	t.Run("empty table skipped", func(t *testing.T) {
		s := &Schema{Dialect: DialectPostgres, Tables: []Table{{ID: "t1", Name: "empty"}}}
		if strings.Contains(mustGenSQL(s), "CREATE TABLE") {
			t.Error("empty table emitted")
		}
	})

	t.Run("self reference emits FK", func(t *testing.T) {
		s := &Schema{Dialect: DialectPostgres, Tables: []Table{
			{ID: "t1", Name: "n", Columns: []Col{{Name: "id", Type: "INT", Pk: true}, {Name: "parent_id", Type: "INT", Ref: &Ref{TableID: "t1"}}}},
		}}
		sql := mustGenSQL(s)
		if !strings.Contains(sql, "FOREIGN KEY") {
			t.Errorf("self-referencing FK missing:\n%s", sql)
		}
		parsed, err := ParseDDL(sql)
		if err != nil {
			t.Fatal(err)
		}
		if parsed.Tables[0].Columns[1].Ref == nil {
			t.Error("self-ref FK lost in round-trip")
		}
	})

	t.Run("dangling FK dropped, not fatal", func(t *testing.T) {
		// The header matters: without it the input would detect as mysql and
		// exercise the wrong parser.
		sql := "-- Generated by erd-creator (PostgreSQL)\nCREATE TABLE \"a\" (\n  \"id\" INT,\n  CONSTRAINT \"fk_a_id\" FOREIGN KEY (\"id\") REFERENCES \"gone\" (\"id\") ON DELETE CASCADE\n);\n"
		parsed, err := ParseDDL(sql)
		if err != nil {
			t.Fatal(err)
		}
		if parsed.Tables[0].Columns[0].Ref != nil {
			t.Error("dangling ref must be dropped")
		}
	})
}

// TestPostgresParseRejects: malformed input is rejected rather than half-read,
// matching the mysql parser's contract.
func TestPostgresParseRejects(t *testing.T) {
	cases := map[string]string{
		"unsupported clause": "-- Generated by erd-creator (PostgreSQL)\nCREATE TABLE \"a\" (\n  CHECK (x)\n);\n",
		"garbage line":       "-- Generated by erd-creator (PostgreSQL)\nCREATE TABLE \"a\" (\n  ??? \n);\n",
		"outside table":      "-- Generated by erd-creator (PostgreSQL)\nDROP TABLE \"a\";\n",
		"no tables":          "-- Generated by erd-creator (PostgreSQL)\n-- nothing\n",
		"duplicate table":    "-- Generated by erd-creator (PostgreSQL)\nCREATE TABLE \"a\" (\n  \"id\" INT\n);\nCREATE TABLE \"a\" (\n  \"id\" INT\n);\n",
	}
	for name, sql := range cases {
		if _, err := ParseDDL(sql); err == nil {
			t.Errorf("%s: expected error", name)
		}
	}
}

// TestDialectDetection: the header decides the parser, and anything unmarked
// stays mysql so files written before dialects existed keep loading.
func TestDialectDetection(t *testing.T) {
	cases := map[string]string{
		"-- Generated by erd-creator (PostgreSQL)\nCREATE TABLE \"a\" (": DialectPostgres,
		"-- Generated by erd-creator (Postgres)\nCREATE TABLE \"a\" (":   DialectPostgres,
		"-- Generated by erd-creator\nCREATE TABLE `a` (":                DialectMysql,
		"-- Generated by erd-creator (MySQL)\nCREATE TABLE `a` (":        DialectMysql,
		"-- some hand-written file\nCREATE TABLE `a` (":                  DialectMysql,
		"CREATE TABLE `a` (": DialectMysql,
		"":                   DialectMysql,
	}
	for sql, want := range cases {
		if got := detectDialect(sql); got != want {
			t.Errorf("detectDialect(%q) = %q, want %q", firstLine(sql), got, want)
		}
	}
}

func firstLine(s string) string {
	if i := strings.Index(s, "\n"); i >= 0 {
		return s[:i]
	}
	return s
}

// TestNormalizeDialect: spellings map to canonical names, unknown input falls
// back to mysql rather than erroring (an unset dialect is the common case).
//
// mariadb is its own canonical name, not a spelling of mysql: the two share a
// grammar but a mariadb schema must keep that identity on save.
func TestNormalizeDialect(t *testing.T) {
	cases := map[string]string{
		"":            DialectMysql,
		"mysql":       DialectMysql,
		"MySQL":       DialectMysql,
		"mariadb":     DialectMariaDB,
		"MariaDB":     DialectMariaDB,
		"maria":       DialectMariaDB,
		"  mariadb  ": DialectMariaDB,
		"postgres":    DialectPostgres,
		"PostgreSQL":  DialectPostgres,
		"postgresql":  DialectPostgres,
		"pg":          DialectPostgres,
		"  postgres ": DialectPostgres,
		// sqlite keeps its own name so saveable() can reject it. Letting it
		// fall through to mysql made a sqlite schema saveable as MySQL.
		"sqlite":   DialectSqlite,
		"SQLite":   DialectSqlite,
		"nonsense": DialectMysql,
	}
	for in, want := range cases {
		if got := normalizeDialect(in); got != want {
			t.Errorf("normalizeDialect(%q) = %q, want %q", in, got, want)
		}
	}
}

// TestMysqlFilesUnaffected: adding dialects must not change what an unmarked
// (pre-dialect) file emits, or every existing .sql would churn on save.
func TestMysqlFilesUnaffected(t *testing.T) {
	legacy := sampleSchema() // Dialect is "" — as every existing file is
	sql := mustGenSQL(legacy)
	if strings.Contains(sql, "(PostgreSQL)") {
		t.Errorf("unmarked schema emitted postgres:\n%s", sql)
	}
	if !strings.HasPrefix(sql, "-- Generated by erd-creator\n") {
		t.Errorf("legacy header changed:\n%s", firstLine(sql))
	}
	// and it round-trips through the mysql parser as before
	parsed, err := ParseDDL(sql)
	if err != nil {
		t.Fatal(err)
	}
	if mustGenSQL(parsed) != sql {
		t.Error("legacy file round-trip drifted")
	}
	if parsed.Dialect != DialectMysql {
		t.Errorf("legacy file parsed as %q, want mysql", parsed.Dialect)
	}
}

// TestPostgresJunctionRoundTrip: a many-to-many junction — composite PK over
// exactly two FK columns, the shape the client's createManyToMany builds — must
// keep both Pk and Ref through emit→parse, or the derived N:N badge would be
// lost on reopen.
func TestPostgresJunctionRoundTrip(t *testing.T) {
	s := &Schema{Dialect: DialectPostgres, Tables: []Table{
		{ID: "t1", Name: "users", Columns: []Col{{Name: "id", Type: "INT", Pk: true, Nn: true, Ai: true}}},
		{ID: "t2", Name: "posts", Columns: []Col{{Name: "id", Type: "INT", Pk: true, Nn: true, Ai: true}}},
		{ID: "t3", Name: "users_posts", Columns: []Col{
			{Name: "user_id", Type: "INT", Pk: true, Nn: true, Ref: &Ref{TableID: "t1", Action: "CASCADE"}},
			{Name: "post_id", Type: "INT", Pk: true, Nn: true, Ref: &Ref{TableID: "t2", Action: "CASCADE"}},
		}},
	}}
	sql := mustGenSQL(s)
	s2, err := ParseDDL(sql)
	if err != nil {
		t.Fatalf("junction round-trip: %v\n%s", err, sql)
	}
	j := s2.Tables[2]
	if len(j.Columns) != 2 {
		t.Fatalf("junction lost its composite PK on round-trip: %d columns\n%s", len(j.Columns), sql)
	}
	for i, want := range []string{"user_id", "post_id"} {
		c := j.Columns[i]
		if c.Pk != true || c.Ref == nil || c.Ref.TableID == "" {
			t.Errorf("junction member %q lost PK/FK on round-trip", want)
		}
	}
}
