// grammar_mariadb_test.go — MariaDB as a first-class dialect.
//
// MariaDB shares the MySQL grammar (every construct we emit is valid in both),
// but it is its own identity: a schema saved as MariaDB keeps that header, is
// detected as MariaDB on reopen, and is offered as saveable in the UI.
//
// The emitter is a separate function (buildMariaDB) so MariaDB-specific syntax
// has a home if the two ever diverge. That headroom costs a second emitter to
// keep in step, so TestMariaDBMatchesMysql pins them to identical output and
// fails the moment they differ.
package main

import (
	"strings"
	"testing"
)

// mariadbSchema returns sampleSchema tagged as mariadb.
func mariadbSchema() *Schema {
	s := sampleSchema()
	s.Dialect = DialectMariaDB
	return s
}

// TestMariaDBGolden pins the exact saved-file bytes, the same contract the
// mysql and postgres suites hold their emitters to.
func TestMariaDBGolden(t *testing.T) {
	const want = `-- Generated by erd-creator (MariaDB)
CREATE TABLE ~users~ (
  ~id~ INT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  ~email~ VARCHAR(190) NOT NULL UNIQUE,
  ~status~ ENUM('active','banned'),
  PRIMARY KEY (~id~)
) ENGINE=InnoDB;
CREATE TABLE ~posts~ (
  ~id~ BIGINT NOT NULL AUTO_INCREMENT,
  ~user_id~ INT,
  ~tag~ VARCHAR(40),
  PRIMARY KEY (~id~),
  KEY ~idx_posts_tag~ (~tag~),
  CONSTRAINT ~fk_posts_user_id~ FOREIGN KEY (~user_id~) REFERENCES ~users~ (~id~) ON DELETE SET NULL
) ENGINE=InnoDB;
`
	got := mariadbSchema().GenSQL()
	if got != strings.ReplaceAll(want, "~", "`") {
		t.Errorf("mariadb saved-file format drifted.\n--- got ---\n%s\n--- want ---\n%s",
			got, strings.ReplaceAll(want, "~", "`"))
	}
}

// TestMariaDBMatchesMysql is the guard on having two emitters. MariaDB and
// MySQL have not diverged for anything we emit, so their bodies must be
// byte-identical and only the header may differ.
//
// When MariaDB genuinely needs different DDL, this test SHOULD fail — that is
// the signal to record the divergence deliberately, update this test, and note
// the difference in buildMariaDB. It must never be "fixed" by relaxing the
// comparison to a substring check, which would defeat its purpose.
func TestMariaDBMatchesMysql(t *testing.T) {
	schemas := map[string]*Schema{
		"sample":       sampleSchema(),
		"no-pk parent": noPKParent(),
		"composite pk": {Tables: []Table{{Id: "t1", Name: "m", Columns: []Col{{Name: "a", Type: "INT", Pk: true}, {Name: "b", Type: "INT", Pk: true}}}}},
		"empty table":  {Tables: []Table{{Id: "t1", Name: "empty"}}},
		"escaping":     {Tables: []Table{{Id: "t1", Name: "we`ird", Columns: []Col{{Name: "a`b", Type: "INT", Pk: true}, {Name: "c", Type: "VARCHAR(10)", Comment: "it's \"quoted\""}}}}},
		"all flag combos": {Tables: []Table{{Id: "t1", Name: "t", Columns: []Col{
			{Name: "a", Type: "INT", Pk: true, Nn: true, Ai: true, Ux: true, Ix: true, Comment: "c"},
			{Name: "b", Type: "TINYINT", Ai: true},
			{Name: "c", Type: "DECIMAL(10,2)"},
			{Name: "d", Type: "ENUM('x','y')", Ix: true},
		}}}},
	}
	for name, s := range schemas {
		mysqlBody := strings.TrimPrefix(buildMysql(s.Tables, ""), "\n")
		mariadbBody := strings.TrimPrefix(buildMariaDB(s.Tables), "-- Generated by erd-creator (MariaDB)\n")
		if mysqlBody != mariadbBody {
			t.Errorf("%s: mysql and mariadb bodies diverged.\n--- mysql ---\n%s\n--- mariadb ---\n%s",
				name, mysqlBody, mariadbBody)
		}
	}
}

// TestMariaDBRoundTripStable: a mariadb file must reopen as mariadb and
// re-emit byte-identically. Before mariadb was a real dialect, normalizeDialect
// collapsed it to mysql, so saving dropped the identity and reopening reported
// the wrong dialect.
func TestMariaDBRoundTripStable(t *testing.T) {
	sql1 := mariadbSchema().GenSQL()
	s2, err := ParseDDL(sql1)
	if err != nil {
		t.Fatal(err)
	}
	if s2.Dialect != DialectMariaDB {
		t.Errorf("dialect lost on parse: got %q, want %q", s2.Dialect, DialectMariaDB)
	}
	if sql2 := s2.GenSQL(); sql1 != sql2 {
		t.Errorf("round-trip drift:\n%s\n----\n%s", sql1, sql2)
	}
	// the schema itself survived, not just the header
	if s2.Tables[1].Columns[1].Ref == nil || s2.Tables[1].Columns[1].Ref.Action != "SET NULL" {
		t.Error("FK action lost in mariadb round-trip")
	}
	if n := len(pkCols(s2.Tables[0])); n != 1 {
		t.Errorf("PK lost: %d cols", n)
	}
}

// TestMariaDBDetectedFromHeader: the header decides the dialect, and mariadb
// must win over the generic erd-creator marker it also contains.
func TestMariaDBDetectedFromHeader(t *testing.T) {
	cases := map[string]string{
		"-- Generated by erd-creator (MariaDB)\nCREATE TABLE `t` (": DialectMariaDB,
		"-- Generated by erd-creator (mariadb)\nCREATE TABLE `t` (": DialectMariaDB,
		"-- Generated by erd-creator (MySQL)\nCREATE TABLE `t` (":   DialectMysql,
		"-- Generated by erd-creator\nCREATE TABLE `t` (":           DialectMysql,
		"CREATE TABLE `t` (": DialectMysql,
	}
	for sql, want := range cases {
		if got := detectDialect(sql); got != want {
			t.Errorf("detectDialect(%q) = %q, want %q", firstLine(sql), got, want)
		}
	}
}

// TestMariaDBIsSaveable: the server must accept what the UI offers. The two
// disagreed before — the UI labelled MariaDB "export only" while the server
// would have saved it as mysql.
func TestMariaDBIsSaveable(t *testing.T) {
	saveable := map[string]bool{
		DialectMysql:    true,
		DialectMariaDB:  true,
		DialectPostgres: true,
		"sqlite":        false, // export-only: no parser
	}
	for dialect, want := range saveable {
		s := &Schema{Dialect: dialect}
		if got := s.saveable(); got != want {
			t.Errorf("saveable(%q) = %v, want %v", dialect, got, want)
		}
	}
}

// TestMariaDBReopenIsPortable: a reopened mariadb schema must export cleanly to
// every other dialect, since it shares the mysql grammar.
func TestMariaDBReopenIsPortable(t *testing.T) {
	reopened, err := ParseDDL(mariadbSchema().GenSQL())
	if err != nil {
		t.Fatal(err)
	}
	for _, dialect := range []string{"mysql", "mariadb", "postgres", "sqlite"} {
		sql, err := exportSQL(dialect, reopened.Tables)
		if err != nil {
			t.Fatalf("%s: %v", dialect, err)
		}
		if !strings.Contains(sql, "CREATE TABLE") {
			t.Errorf("%s: no tables emitted:\n%s", dialect, sql)
		}
		if strings.Contains(sql, "JSONB") {
			t.Errorf("%s: leaked a postgres-only type:\n%s", dialect, sql)
		}
	}
}

// TestMariaDBSaveAndExportAgree: the saved file and the /export path must
// produce identical bytes for the same schema. They are different call sites
// into the emitters, and exportSQL originally still routed mariadb to
// buildMysql while GenSQL used buildMariaDB — the same split-brain that caused
// the original save/export drift.
func TestMariaDBSaveAndExportAgree(t *testing.T) {
	s := mariadbSchema()
	saved := s.GenSQL()
	exported, err := exportSQL("mariadb", s.Tables)
	if err != nil {
		t.Fatal(err)
	}
	if saved != exported {
		t.Errorf("save and export disagree for mariadb:\n--- GenSQL ---\n%s\n--- exportSQL ---\n%s", saved, exported)
	}
}

// TestMariaDBParseRejects: malformed input is rejected rather than half-read,
// matching the mysql parser's contract (it is the same parser).
func TestMariaDBParseRejects(t *testing.T) {
	cases := map[string]string{
		"unsupported clause": "-- Generated by erd-creator (MariaDB)\nCREATE TABLE `a` (\n  ENGINE=InnoDB\n) ENGINE=InnoDB;\n",
		"garbage line":       "-- Generated by erd-creator (MariaDB)\nCREATE TABLE `a` (\n  ??? \n) ENGINE=InnoDB;\n",
		"no tables":          "-- Generated by erd-creator (MariaDB)\n-- nothing\n",
	}
	for name, sql := range cases {
		if _, err := ParseDDL(sql); err == nil {
			t.Errorf("%s: expected error", name)
		}
	}
}
