// grammar_postgres.go — the PostgreSQL parse half of the saved-file grammar.
//
// This reads back exactly what buildPostgres (export.go) emits, the same
// contract parseMysql has with buildMysql. Postgres needs its own parser rather
// than a flag on the mysql one because the two grammars differ structurally,
// not just in quoting:
//
//   - identifiers are "double quoted", not `backticked`
//   - tables end with ");" — there is no ENGINE=InnoDB clause
//   - comments and indexes are separate statements AFTER the table
//     (COMMENT ON COLUMN / CREATE INDEX), not inline clauses
//   - AUTO_INCREMENT is GENERATED BY DEFAULT AS IDENTITY
//
// Keeping it a separate parser is what lets the mysql path stay untouched.
package main

import (
	"fmt"
	"regexp"
	"strings"
)

var (
	// Every pattern captures the FULL quoted token, quotes included, so
	// unquoteDQ can be applied uniformly. Capturing only the inner text looks
	// natural but silently skips unescaping, because unquoteDQ keys off the
	// leading quote to decide there is anything to strip.
	rePgCreate   = regexp.MustCompile(`(?i)^CREATE TABLE ("(?:[^"]|"")*") \($`)
	rePgEndTable = regexp.MustCompile(`^\);$`)
	rePgPK       = regexp.MustCompile(`(?i)^PRIMARY KEY \((.+)\)$`)
	rePgFK       = regexp.MustCompile(`(?i)^CONSTRAINT ("(?:[^"]|"")*") FOREIGN KEY \(("(?:[^"]|"")*")\) REFERENCES ("(?:[^"]|"")*") \(("(?:[^"]|"")*")\)( ON DELETE (SET NULL|SET DEFAULT|NO ACTION|RESTRICT|CASCADE))?$`)
	// "col" TYPE [GENERATED BY DEFAULT AS IDENTITY] [NOT NULL] [UNIQUE] [CHECK ("col" IN (...))]
	// The CHECK column is deliberately non-capturing: it always repeats the
	// column name, so capturing it would just shift the IN-list's index.
	rePgColumn  = regexp.MustCompile(`(?i)^("(?:[^"]|"")*") ([A-Z][A-Z0-9]*(?:\([^)]*\))?)( GENERATED BY DEFAULT AS IDENTITY)?( NOT NULL)?( UNIQUE)?( CHECK \("(?:[^"]|"")*" IN \((.*)\)\))?$`)
	rePgKeyword = regexp.MustCompile(`(?i)^(PRIMARY KEY|CONSTRAINT|FOREIGN KEY|CHECK)\b`)

	// Out-of-line statements, emitted after their table.
	rePgComment = regexp.MustCompile(`(?i)^COMMENT ON COLUMN ("(?:[^"]|"")*")\.("(?:[^"]|"")*") IS '(.*)';$`)
	rePgIndex   = regexp.MustCompile(`(?i)^CREATE INDEX "(?:[^"]|"")*" ON ("(?:[^"]|"")*") \(("(?:[^"]|"")*")\);$`)
)

// unquoteDQ strips the double quotes buildPostgres puts around identifiers and
// undoes its "" escaping. Mirrors unquoteTick.
func unquoteDQ(s string) string {
	s = strings.TrimSpace(s)
	if len(s) >= 2 && strings.HasPrefix(s, `"`) && strings.HasSuffix(s, `"`) {
		return strings.ReplaceAll(s[1:len(s)-1], `""`, `"`)
	}
	return s
}

// pgToModelType maps a Postgres-emitted type name back to the model's portable
// name. Most Postgres spellings are left alone because they are valid in every
// dialect we emit; JSONB is not:
//
//	JSONB -> JSON
//
// JSONB is a Postgres-only type name. Leaving it in the model meant that
// opening a postgres file, switching the dropdown to mysql and exporting
// produced `c` JSONB — invalid MySQL and invalid SQLite. JSON is the exact
// inverse of the emitter's JSON -> JSONB, and Postgres has had a native JSON
// type since 9.2, so nothing is lost by mapping back.
//
// SMALLINT and TIMESTAMP are deliberately NOT remapped. They are valid in every
// dialect, so the TINYINT/DATETIME information loss stays harmless in practice;
// rewriting them to a dialect-specific spelling would only add a second
// mismatch to reason about.
func pgToModelType(ty string) string {
	if ty == "JSONB" {
		return "JSON"
	}
	return ty
}

// parsePostgres reads the grammar buildPostgres emits.
func parsePostgres(sql string) (*Schema, error) {
	s := &Schema{Dialect: DialectPostgres}
	byName := map[string]int{} // name → index in s.Tables
	byID := map[string]int{}   // id → index, O(1) for pending FK attachment
	var pending []pendingFK
	cur := -1
	tableID := 0

	lines := strings.Split(sql, "\n")
	for i, raw := range lines {
		n := i + 1
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "--") || reInsert.MatchString(line) {
			continue
		}

		if m := rePgCreate.FindStringSubmatch(line); m != nil {
			name := unquoteDQ(m[1])
			if _, dup := byName[name]; dup {
				return nil, fmt.Errorf("line %d: duplicate table %q", n, name)
			}
			tableID++
			id := fmt.Sprintf("t%d", tableID)
			s.Tables = append(s.Tables, Table{ID: id, Name: name})
			byName[name] = len(s.Tables) - 1
			byID[id] = len(s.Tables) - 1
			cur = len(s.Tables) - 1
			continue
		}
		if rePgEndTable.MatchString(line) {
			cur = -1
			continue
		}

		// COMMENT ON / CREATE INDEX stand alone and may follow any table, so
		// they are matched before the inside-a-table check.
		if m := rePgComment.FindStringSubmatch(line); m != nil {
			idx, ok := byName[unquoteDQ(m[1])]
			if !ok {
				continue // comment for an unknown table → dropped, not fatal
			}
			markCol(&s.Tables[idx], unquoteDQ(m[2]), func(c *Col) {
				c.Comment = strings.ReplaceAll(m[3], "''", "'")
			})
			continue
		}
		if m := rePgIndex.FindStringSubmatch(line); m != nil {
			idx, ok := byName[unquoteDQ(m[1])]
			if !ok {
				continue
			}
			markCol(&s.Tables[idx], unquoteDQ(m[2]), func(c *Col) { c.Ix = true })
			continue
		}

		if cur < 0 {
			return nil, fmt.Errorf("line %d: not inside CREATE TABLE: %s", n, line)
		}
		body := strings.TrimSuffix(line, ",")
		tbl := &s.Tables[cur]

		if m := rePgPK.FindStringSubmatch(body); m != nil {
			for _, name := range strings.Split(m[1], ",") {
				markCol(tbl, unquoteDQ(name), func(c *Col) { c.Pk = true })
			}
			continue
		}
		if m := rePgFK.FindStringSubmatch(body); m != nil {
			// m[5] is the whole " ON DELETE <action>" clause; m[6] is the action.
			// (The constraint-name capture at the front shifts these one past
			// the mysql regex, which has no such group and uses m[5].)
			action := m[6]
			if action == "" {
				action = "CASCADE"
			}
			pending = append(pending, pendingFK{tbl.ID, unquoteDQ(m[2]), unquoteDQ(m[3]), action})
			continue
		}
		if rePgKeyword.MatchString(body) {
			return nil, fmt.Errorf("line %d: unsupported clause: %s", n, line)
		}

		m := rePgColumn.FindStringSubmatch(body)
		if m == nil {
			return nil, fmt.Errorf("line %d: cannot parse: %s", n, line)
		}
		ty := m[2]
		// An ENUM round-trips as TEXT + CHECK, so recover the original ENUM
		// rather than degrading it to TEXT. Only ENUMs produce that shape.
		if m[6] != "" {
			// Rebuild without the spaces splitTop inserted, so ENUM('a','b')
			// comes back as written rather than ENUM('a', 'b') — otherwise a
			// saved file's bytes change on the first reopen for no reason.
			vals := enumValues("ENUM(" + m[7] + ")")
			quoted := make([]string, len(vals))
			for i, v := range vals {
				quoted[i] = sqlStr(v)
			}
			ty = "ENUM(" + strings.Join(quoted, ",") + ")"
		} else {
			ty = pgToModelType(ty)
		}
		tbl.Columns = append(tbl.Columns, Col{
			Name: unquoteDQ(m[1]),
			Type: ty,
			Nn:   m[4] != "",
			Ai:   m[3] != "",
			Ux:   m[5] != "",
		})
	}

	// attach FKs now that every table exists (parents may be defined later)
	for _, p := range pending {
		idx, ok := byName[p.table]
		if !ok {
			continue // dangling FK ref → dropped, not crashed on
		}
		si, ok := byID[p.tableID]
		if !ok {
			continue
		}
		markCol(&s.Tables[si], p.col, func(c *Col) {
			c.Ref = &Ref{TableID: s.Tables[idx].ID, Action: p.action}
		})
	}
	if len(s.Tables) == 0 {
		return nil, fmt.Errorf("no CREATE TABLE found")
	}
	return s, nil
}
