// grammar.go — the schema model, MySQL canonical parse, and lint.
// Single source of truth: the browser sends/renders schema JSON; grammar
// decisions live in this package. The saved .sql is exactly what GenSQL emits —
// GenSQL delegates to buildMysql (export.go) so save and export share ONE
// emitter — and ParseDDL reads only that subset (same contract the old JS
// parser had).
package main

import (
	"fmt"
	"regexp"
	"strings"
)

// ---- model ----

// Ref has no JSON tags: on the wire the browser sends {"tableId","action"}.
type Ref struct {
	TableId string `json:"tableId"`
	Action  string `json:"action"`
}

type Col struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	Pk      bool   `json:"pk"`
	Nn      bool   `json:"nn"`
	Ai      bool   `json:"ai"`
	Ux      bool   `json:"ux"`
	Ix      bool   `json:"ix"`
	Comment string `json:"comment"`
	Ref     *Ref   `json:"ref"`
}

// Id is the wire key the browser uses for ref.tableId; on open the client
// re-allocates ids in its own namespace (adoptIds). X/Y are client-only.
type Table struct {
	Id      string `json:"id"`
	Name    string `json:"name"`
	X       int    `json:"-"`
	Y       int    `json:"-"`
	Columns []Col  `json:"columns"`
}

type Schema struct {
	Tables []Table `json:"tables"`
}

// Lint: FK base-type vs referenced PK base-type mismatch; FK onto composite PK.
func (s *Schema) Lint() []string {
	var out []string
	for _, t := range s.Tables {
		for _, c := range t.Columns {
			if c.Ref == nil {
				continue
			}
			p := findTable(s.Tables, c.Ref.TableId)
			if p == nil {
				continue
			}
			var pks []Col
			for _, x := range p.Columns {
				if x.Pk {
					pks = append(pks, x)
				}
			}
			switch {
			case len(pks) > 1:
				out = append(out, fmt.Sprintf("%s.%s → %s has composite PK; single-col FK is invalid DDL", t.Name, c.Name, p.Name))
				continue
			case len(pks) == 0:
				// No PK → no unique column to point at, so the FK is omitted
				// from every dialect rather than silently targeting the first
				// column (invalid DDL). Report it, or the relationship just
				// vanishes from the output with no explanation.
				out = append(out, fmt.Sprintf("%s.%s → %s has no PK; FK omitted from DDL", t.Name, c.Name, p.Name))
				continue
			}
			pk := pks[0]
			if baseOf(pk.Type) != baseOf(c.Type) {
				out = append(out, fmt.Sprintf("%s.%s %s vs %s.%s %s", t.Name, c.Name, baseOf(c.Type), p.Name, pk.Name, baseOf(pk.Type)))
			}
		}
	}
	return out
}

// ---- MySQL canonical emit ----

func pkCols(t Table) []Col {
	var out []Col
	for _, c := range t.Columns {
		if c.Pk {
			out = append(out, c)
		}
	}
	return out
}

// GenSQL is the saved-file grammar: exactly what saveFile writes to disk, and
// exactly what ParseDDL reads back. It delegates to buildMysql so the save path
// and the /export mysql|mariadb path share ONE emitter. Two emitters for one
// grammar drifted on the no-PK-parent edge — save dropped the FK, export emitted
// one onto a non-unique column. Output is pinned by TestGenSQLGolden.
func (s *Schema) GenSQL() string {
	return buildMysql(s.Tables, "-- Generated by erd-creator")
}

// ---- seed INSERT templates ----

func (s *Schema) GenInserts() string {
	out := []string{"-- Seed row templates (edit values, remove per table as needed)"}
	for _, t := range s.Tables {
		if len(t.Columns) == 0 {
			continue
		}
		vals := make([]string, len(t.Columns))
		names := make([]string, len(t.Columns))
		for i, c := range t.Columns {
			b := baseOf(c.Type)
			switch {
			case c.Ai:
				vals[i] = "NULL"
			case isInt(b):
				vals[i] = "0"
			case b == "DECIMAL":
				vals[i] = "0.00"
			case b == "BOOLEAN":
				vals[i] = "FALSE"
			case b == "DATE":
				vals[i] = "'2026-01-01'"
			case b == "DATETIME" || b == "TIMESTAMP":
				vals[i] = "NOW()"
			case b == "JSON":
				vals[i] = "'{}'"
			default:
				vals[i] = "''"
			}
			names[i] = quoteTick(c.Name)
		}
		out = append(out, "INSERT INTO "+quoteTick(t.Name)+" ("+strings.Join(names, ", ")+") VALUES ("+strings.Join(vals, ", ")+");")
	}
	return strings.Join(out, "\n") + "\n"
}

// ---- parse: reads only GenSQL output ----

var (
	reInsert   = regexp.MustCompile(`(?i)^INSERT INTO `)
	reCreate   = regexp.MustCompile(`(?i)^CREATE TABLE (\S+) \($`)
	reEndTable = regexp.MustCompile(`(?i)^\) ENGINE=InnoDB;?$`)
	rePK       = regexp.MustCompile(`(?i)^PRIMARY KEY \((.+)\)$`)
	reUKey     = regexp.MustCompile(`(?i)^UNIQUE KEY (\S+) \((.+)\)$`)
	reIndex    = regexp.MustCompile(`(?i)^(KEY|INDEX) \S+ \(.+\)$`)
	reFK       = regexp.MustCompile(`(?i)^CONSTRAINT \S+ FOREIGN KEY \((\S+)\) REFERENCES (\S+) \((\S+)\)( ON DELETE (SET NULL|SET DEFAULT|NO ACTION|RESTRICT|CASCADE))?$`)
	reColumn   = regexp.MustCompile(`(?i)^(\S+) ([A-Z]+(?:\([^)]*\))?)( NOT NULL)?( AUTO_INCREMENT)?( UNIQUE)?( COMMENT '((?:[^']|'')*)')?$`)
	reKeyword  = regexp.MustCompile(`(?i)^(PRIMARY KEY|UNIQUE KEY|CONSTRAINT|KEY|INDEX|FOREIGN KEY)\b`)
	reTypeNorm = regexp.MustCompile(`(?i)^([A-Za-z]+)(\(.*\))?$`)
)

func unquoteTick(s string) string {
	s = strings.TrimSpace(s)
	if len(s) >= 2 && strings.HasPrefix(s, "`") {
		return strings.ReplaceAll(s[1:len(s)-1], "``", "`")
	}
	return s
}

type pendingFK struct {
	tableID, col, table, action string
}

// ParseDDL rebuilds the schema from DDL this tool emitted. Any unsupported line
// rejects the whole file; caller keeps prior state.
func ParseDDL(sql string) (*Schema, error) {
	s := &Schema{}
	byName := map[string]int{} // name → index in s.Tables
	var pending []pendingFK
	cur := -1
	tableID := 0

	lines := strings.Split(sql, "\n")
	for i, raw := range lines {
		n := i + 1
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "--") || reInsert.MatchString(line) {
			continue
		}
		if m := reCreate.FindStringSubmatch(line); m != nil {
			name := unquoteTick(m[1])
			if _, dup := byName[name]; dup {
				return nil, fmt.Errorf("line %d: duplicate table %q", n, name)
			}
			tableID++
			s.Tables = append(s.Tables, Table{Id: fmt.Sprintf("t%d", tableID), Name: name})
			byName[name] = len(s.Tables) - 1
			cur = len(s.Tables) - 1
			continue
		}
		if reEndTable.MatchString(line) {
			cur = -1
			continue
		}
		if cur < 0 {
			return nil, fmt.Errorf("line %d: not inside CREATE TABLE: %s", n, line)
		}
		body := strings.TrimSuffix(line, ",")
		tbl := &s.Tables[cur]

		if m := rePK.FindStringSubmatch(body); m != nil {
			for _, name := range strings.Split(m[1], ",") {
				markCol(tbl, unquoteTick(name), func(c *Col) { c.Pk = true })
			}
			continue
		}
		if m := reUKey.FindStringSubmatch(body); m != nil {
			markCol(tbl, unquoteTick(m[2]), func(c *Col) { c.Ux = true })
			continue
		}
		if reIndex.MatchString(body) {
			markCol(tbl, unquoteTick(body[strings.Index(body, "(")+1:strings.LastIndex(body, ")")]), func(c *Col) { c.Ix = true })
			continue
		}
		if m := reFK.FindStringSubmatch(body); m != nil {
			action := m[5]
			if action == "" {
				action = "CASCADE"
			}
			pending = append(pending, pendingFK{tbl.Id, unquoteTick(m[1]), unquoteTick(m[2]), action})
			continue
		}
		if reKeyword.MatchString(body) {
			return nil, fmt.Errorf("line %d: unsupported clause: %s", n, line)
		}
		m := reColumn.FindStringSubmatch(body)
		if m == nil {
			return nil, fmt.Errorf("line %d: cannot parse: %s", n, line)
		}
		ty := m[2]
		if mm := reTypeNorm.FindStringSubmatch(ty); mm != nil {
			ty = strings.ToUpper(mm[1]) + mm[2]
		}
		tbl.Columns = append(tbl.Columns, Col{
			Name:    unquoteTick(m[1]),
			Type:    ty,
			Nn:      m[3] != "",
			Ai:      m[4] != "",
			Ux:      m[5] != "",
			Comment: strings.ReplaceAll(m[7], "''", "'"),
		})
	}
	// attach FKs now that every table exists (parents may be defined later)
	for _, p := range pending {
		idx, ok := byName[p.table]
		if !ok {
			continue // dangling FK ref → dropped, not crashed on
		}
		for i := range s.Tables {
			if s.Tables[i].Id != p.tableID {
				continue
			}
			markCol(&s.Tables[i], p.col, func(c *Col) {
				c.Ref = &Ref{TableId: s.Tables[idx].Id, Action: p.action}
			})
		}
	}
	if len(s.Tables) == 0 {
		return nil, fmt.Errorf("no CREATE TABLE found")
	}
	return s, nil
}

func markCol(t *Table, name string, f func(*Col)) {
	for i := range t.Columns {
		if t.Columns[i].Name == name {
			f(&t.Columns[i])
		}
	}
}
