// grammar_sqlite_test.go — the SQLite saved-file grammar: emit↔parse round-trip,
// type mapping, comments, and rejects. Mirrors grammar_test.go's coverage of the
// mysql path and grammar_postgres_test.go's coverage of the postgres one.
package main

import (
	"strings"
	"testing"
)

// sqliteSample is sampleSchema with a few constructs SQLite renders specially:
// BOOLEAN and DATETIME (no native type), an indexed column, and an FK action.
func sqliteSample() *Schema {
	return &Schema{Dialect: DialectSqlite, Tables: []Table{
		{ID: "t1", Name: "users", Columns: []Col{
			{Name: "id", Type: "INT", Pk: true, Nn: true, Ai: true, Comment: "pk"},
			{Name: "email", Type: "VARCHAR(190)", Nn: true, Ux: true},
			{Name: "status", Type: "ENUM('active','banned')"},
			{Name: "active", Type: "BOOLEAN"},
			{Name: "seen_at", Type: "DATETIME", Comment: "last login"},
			{Name: "stamp", Type: "TIMESTAMP"},
		}},
		{ID: "t2", Name: "posts", Columns: []Col{
			{Name: "id", Type: "BIGINT", Pk: true, Nn: true, Ai: true},
			{Name: "user_id", Type: "INT", Ref: &Ref{TableID: "t1", Action: "SET NULL"}},
			{Name: "tag", Type: "VARCHAR(40)", Ix: true},
		}},
	}}
}

func TestSqliteRoundTripStable(t *testing.T) {
	s := sqliteSample()
	sql1 := mustGenSQL(s)
	s2, err := ParseDDL(sql1)
	if err != nil {
		t.Fatal(err)
	}
	if sql2 := mustGenSQL(s2); sql1 != sql2 {
		t.Errorf("round-trip drift:\n%s\n----\n%s", sql1, sql2)
	}
	// identity: a sqlite file must reopen as sqlite, not silently become mysql
	if s2.Dialect != DialectSqlite {
		t.Errorf("dialect = %q, want %q", s2.Dialect, DialectSqlite)
	}
}

func TestSqliteDetectDialect(t *testing.T) {
	if got := detectDialect(mustGenSQL(sqliteSample())); got != DialectSqlite {
		t.Errorf("detectDialect = %q, want sqlite", got)
	}
	// the sqlite header contains the generic marker too, so ordering matters:
	// mysql must not win on the shared "generated by erd-creator" prefix
	if got := detectDialect("-- Generated by erd-creator (SQLite)\nCREATE TABLE `a` (\n  `id` INT\n);\n"); got != DialectSqlite {
		t.Errorf("detectDialect = %q, want sqlite", got)
	}
}

// TestSqliteShapes pins the constructs that differ from MySQL's rendering.
func TestSqliteShapes(t *testing.T) {
	sql := mustGenSQL(sqliteSample())
	for _, want := range []string{
		"INTEGER PRIMARY KEY",                      // rowid alias instead of AUTO_INCREMENT
		"CHECK (`status` IN ('active', 'banned'))", // ENUM → TEXT + CHECK
		"CREATE INDEX IF NOT EXISTS `idx_posts_tag` ON `posts` (`tag`);",
		"FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL",
	} {
		if !strings.Contains(sql, want) {
			t.Errorf("missing %q in:\n%s", want, sql)
		}
	}
	for _, banned := range []string{"AUTO_INCREMENT", "ENGINE=InnoDB", "ENUM("} {
		if strings.Contains(sql, banned) {
			t.Errorf("sqlite output must not contain %q:\n%s", banned, sql)
		}
	}
}

// TestSqliteTypeModes covers both renderings of the types SQLite has no storage
// class for. The default (native) keeps the model's type name, so the schema
// survives a round-trip unchanged; portable rewrites to INTEGER/TEXT, which is
// what the emitter did before the choice existed, and is lossy on purpose.
func TestSqliteTypeModes(t *testing.T) {
	types := map[string]string{
		"active":  "BOOLEAN",
		"seen_at": "DATETIME",
		"stamp":   "TIMESTAMP",
	}

	t.Run("native keeps the model type", func(t *testing.T) {
		s := sqliteSample() // SqliteTypes empty → native
		sql := mustGenSQL(s)
		for col, want := range types {
			if !strings.Contains(sql, "`"+col+"` "+want) {
				t.Errorf("native mode should emit %s as %s:\n%s", col, want, sql)
			}
		}
		s2, err := ParseDDL(sql)
		if err != nil {
			t.Fatal(err)
		}
		byName := map[string]Col{}
		for _, c := range s2.Tables[0].Columns {
			byName[c.Name] = c
		}
		for col, want := range types {
			if got := byName[col].Type; got != want {
				t.Errorf("native round-trip changed %s: %q → %q", col, want, got)
			}
		}
		// the whole point: reopen+save is byte-identical, so an export to
		// another dialect is not silently downgraded to INTEGER/TEXT
		if got := mustGenSQL(s2); got != sql {
			t.Errorf("native mode drift:\n%s\n----\n%s", sql, got)
		}
	})

	t.Run("portable rewrites to the storage class", func(t *testing.T) {
		s := sqliteSample()
		s.SqliteTypes = SqliteTypesPortable
		sql := mustGenSQL(s)
		for _, want := range []string{"`active` INTEGER", "`seen_at` TEXT", "`stamp` TEXT"} {
			if !strings.Contains(sql, want) {
				t.Errorf("portable mode missing %q:\n%s", want, sql)
			}
		}
		s2, err := ParseDDL(sql)
		if err != nil {
			t.Fatal(err)
		}
		byName := map[string]Col{}
		for _, c := range s2.Tables[0].Columns {
			byName[c.Name] = c
		}
		// documented loss: the model type is gone after a reopen
		if got := byName["active"].Type; got != "INTEGER" {
			t.Errorf("portable BOOLEAN → %q, want INTEGER", got)
		}
		if got := byName["seen_at"].Type; got != "TEXT" {
			t.Errorf("portable DATETIME → %q, want TEXT", got)
		}
		// but it is stable: re-emitting the reopened schema does not keep changing
		if got := mustGenSQL(s2); got != sql {
			t.Errorf("portable mode drift:\n%s\n----\n%s", sql, got)
		}
	})

	// ENUM is unaffected by the mode: SQLite has no enum type at all, so both
	// render TEXT + CHECK and both must recover the values.
	t.Run("ENUM is mode-independent", func(t *testing.T) {
		for _, mode := range []string{SqliteTypesNative, SqliteTypesPortable} {
			s := sqliteSample()
			s.SqliteTypes = mode
			sql := mustGenSQL(s)
			if !strings.Contains(sql, "CHECK (`status` IN ('active', 'banned'))") {
				t.Errorf("%s: ENUM CHECK missing:\n%s", mode, sql)
			}
			s2, err := ParseDDL(sql)
			if err != nil {
				t.Fatal(err)
			}
			for _, c := range s2.Tables[0].Columns {
				if c.Name == "status" && c.Type != "ENUM('active','banned')" {
					t.Errorf("%s: ENUM not recovered: %q", mode, c.Type)
				}
			}
		}
	})

	// the mode must not leak into the other dialects
	t.Run("other dialects unaffected", func(t *testing.T) {
		s := sqliteSample()
		s.SqliteTypes = SqliteTypesPortable
		s.Dialect = DialectMysql
		if got := mustGenSQL(s); !strings.Contains(got, "`active` BOOLEAN") {
			t.Errorf("mysql must still emit BOOLEAN:\n%s", got)
		}
	})
}

// TestSqliteCommentRoundTrip: the comment rides in the same comma-joined entry
// as its column. As a separate entry it picked up the join's comma and the
// parser read it back as part of the text ("pk" → "pk,").
func TestSqliteCommentRoundTrip(t *testing.T) {
	s := &Schema{Dialect: DialectSqlite, Tables: []Table{{ID: "t1", Name: "t", Columns: []Col{
		{Name: "id", Type: "INT", Pk: true, Ai: true, Comment: "pk"},
		{Name: "note", Type: "VARCHAR(10)", Comment: "no trailing comma"},
	}}}}
	sql := mustGenSQL(s)
	if strings.Contains(sql, "pk,") {
		t.Errorf("comment picked up the join comma:\n%s", sql)
	}
	s2, err := ParseDDL(sql)
	if err != nil {
		t.Fatal(err)
	}
	if got := s2.Tables[0].Columns[0].Comment; got != "pk" {
		t.Errorf("comment = %q, want %q", got, "pk")
	}
	if got := s2.Tables[0].Columns[1].Comment; got != "no trailing comma" {
		t.Errorf("comment = %q, want %q", got, "no trailing comma")
	}
}

// TestSqliteCommentWithColon: the "-- name: text" prefix is stripped by matching
// the KNOWN column name, not by splitting on the first ": ", so a colon in
// either the name or the text survives.
func TestSqliteCommentWithColon(t *testing.T) {
	s := &Schema{Dialect: DialectSqlite, Tables: []Table{{ID: "t1", Name: "t", Columns: []Col{
		{Name: "a:b", Type: "INT", Pk: true, Ai: true, Comment: "has: colon"},
		{Name: "plain", Type: "INT", Comment: "x:y:z"},
	}}}}
	sql := mustGenSQL(s)
	s2, err := ParseDDL(sql)
	if err != nil {
		t.Fatalf("%v\n%s", err, sql)
	}
	if got := s2.Tables[0].Columns[0].Comment; got != "has: colon" {
		t.Errorf("comment on colon-named column = %q, want %q", got, "has: colon")
	}
	if got := s2.Tables[0].Columns[0].Name; got != "a:b" {
		t.Errorf("column name = %q, want %q", got, "a:b")
	}
	if got := s2.Tables[0].Columns[1].Comment; got != "x:y:z" {
		t.Errorf("comment = %q, want %q", got, "x:y:z")
	}
}

// TestSqliteIndexedPkKeepsIndex: the rowid-alias branch used to `continue` past
// the index collection, so an indexed PK column silently lost its CREATE INDEX.
func TestSqliteIndexedPkKeepsIndex(t *testing.T) {
	s := &Schema{Dialect: DialectSqlite, Tables: []Table{{ID: "t1", Name: "t", Columns: []Col{
		{Name: "id", Type: "INT", Pk: true, Ai: true, Ix: true},
	}}}}
	sql := mustGenSQL(s)
	if !strings.Contains(sql, "CREATE INDEX IF NOT EXISTS `idx_t_id`") {
		t.Errorf("indexed PK lost its index:\n%s", sql)
	}
	s2, err := ParseDDL(sql)
	if err != nil {
		t.Fatal(err)
	}
	if !s2.Tables[0].Columns[0].Ix {
		t.Error("index flag lost on round-trip")
	}
	if got := mustGenSQL(s2); got != sql {
		t.Errorf("drift:\n%s\n----\n%s", sql, got)
	}
}

func TestSqliteCompositePK(t *testing.T) {
	s := &Schema{Dialect: DialectSqlite, Tables: []Table{{ID: "t1", Name: "m", Columns: []Col{
		{Name: "a", Type: "INT", Pk: true},
		{Name: "b", Type: "INT", Pk: true},
	}}}}
	sql := mustGenSQL(s)
	if !strings.Contains(sql, "PRIMARY KEY (`a`, `b`)") {
		t.Errorf("composite PK not emitted as a table constraint:\n%s", sql)
	}
	s2, err := ParseDDL(sql)
	if err != nil {
		t.Fatal(err)
	}
	if n := len(pkCols(s2.Tables[0])); n != 2 {
		t.Errorf("composite PK lost: %d cols", n)
	}
}

// TestSqliteEscaping: identifiers are backticked like MySQL's, and enum values
// containing a comma must not split the CHECK list.
func TestSqliteEscaping(t *testing.T) {
	s := &Schema{Dialect: DialectSqlite, Tables: []Table{{ID: "t1", Name: "we`ird", Columns: []Col{
		{Name: "a`b", Type: "INT", Pk: true, Ai: true},
		{Name: "e", Type: "ENUM('a''b','c,d')"},
		{Name: "c", Type: "VARCHAR(10)", Comment: "it's \"quoted\""},
	}}}}
	sql := mustGenSQL(s)
	s2, err := ParseDDL(sql)
	if err != nil {
		t.Fatalf("%v\n%s", err, sql)
	}
	if s2.Tables[0].Name != "we`ird" || s2.Tables[0].Columns[0].Name != "a`b" {
		t.Error("backtick identifiers mangled")
	}
	if got := s2.Tables[0].Columns[1].Type; got != "ENUM('a''b','c,d')" {
		t.Errorf("enum values mangled: %q", got)
	}
	if got := s2.Tables[0].Columns[2].Comment; got != `it's "quoted"` {
		t.Errorf("comment mangled: %q", got)
	}
	if got := mustGenSQL(s2); got != sql {
		t.Errorf("escaping drift:\n%s\n----\n%s", sql, got)
	}
}

// TestSqliteTypesModeSurvivesReopen: the mode changes the bytes, so it must be
// recoverable from the file. Otherwise a portable file reopens as native and the
// UI would claim a convention the file does not follow.
func TestSqliteTypesModeSurvivesReopen(t *testing.T) {
	// native is the default and is NOT written into the header, so files from
	// before the setting existed keep their exact bytes
	native := sqliteSample()
	if got := mustGenSQL(native); !strings.HasPrefix(got, "-- Generated by erd-creator (SQLite)\n") {
		t.Errorf("native header must stay unchanged, got %q", firstLine(got))
	}
	s2, err := ParseDDL(mustGenSQL(native))
	if err != nil {
		t.Fatal(err)
	}
	if s2.sqliteTypesMode() != SqliteTypesNative {
		t.Errorf("native reopen = %q, want native", s2.sqliteTypesMode())
	}

	// portable is recorded, and survives
	portable := sqliteSample()
	portable.SqliteTypes = SqliteTypesPortable
	sql := mustGenSQL(portable)
	if !strings.Contains(firstLine(sql), SqliteTypesPortable) {
		t.Errorf("portable header must record the mode, got %q", firstLine(sql))
	}
	s3, err := ParseDDL(sql)
	if err != nil {
		t.Fatal(err)
	}
	if s3.sqliteTypesMode() != SqliteTypesPortable {
		t.Errorf("portable reopen = %q, want portable", s3.sqliteTypesMode())
	}
	// and the reopened schema re-emits identically, mode included
	if got := mustGenSQL(s3); got != sql {
		t.Errorf("portable mode lost on reopen:\n%s\n----\n%s", sql, got)
	}
}

// TestSqliteTypesModeIsSqliteOnly: the field must not leak into the other
// dialects' output or headers.
func TestSqliteTypesModeIsSqliteOnly(t *testing.T) {
	for _, d := range []string{DialectMysql, DialectMariaDB, DialectPostgres} {
		s := sqliteSample()
		s.Dialect = d
		s.SqliteTypes = SqliteTypesPortable
		sql := mustGenSQL(s)
		if strings.Contains(strings.ToLower(sql), "types:") {
			t.Errorf("%s header must not mention sqlite types:\n%s", d, sql)
		}
		reopened, err := ParseDDL(sql)
		if err != nil {
			t.Fatalf("%s: %v", d, err)
		}
		if reopened.sqliteTypesMode() != SqliteTypesNative {
			t.Errorf("%s reopened with sqlite mode %q", d, reopened.sqliteTypesMode())
		}
	}
}

func TestSqliteRejects(t *testing.T) {
	header := "-- Generated by erd-creator (SQLite)\n"
	cases := map[string]string{
		"garbage line":    header + "CREATE TABLE `a` (\n  ???\n);\n",
		"no tables":       header + "-- nothing\n",
		"outside table":   header + "DROP TABLE `a`;\n",
		"duplicate table": header + "CREATE TABLE `a` (\n  `id` INT\n);\nCREATE TABLE `a` (\n  `id` INT\n);\n",
	}
	for name, sql := range cases {
		if _, err := ParseDDL(sql); err == nil {
			t.Errorf("%s: expected error", name)
		}
	}
}

// TestSqliteDanglingFKDropped mirrors the mysql/postgres behaviour: an FK whose
// parent is absent is dropped rather than crashing the load.
func TestSqliteDanglingFKDropped(t *testing.T) {
	sql := "-- Generated by erd-creator (SQLite)\nCREATE TABLE `a` (\n  `id` INT,\n  FOREIGN KEY (`id`) REFERENCES `gone` (`id`) ON DELETE CASCADE\n);\n"
	s, err := ParseDDL(sql)
	if err != nil {
		t.Fatal(err)
	}
	if s.Tables[0].Columns[0].Ref != nil {
		t.Error("dangling ref must be dropped")
	}
}

// TestSqliteSaveable: sqlite is a first-class saveable dialect now, so the save
// guard must accept it (it previously refused, which is what kept the missing
// parser from producing unreadable files).
func TestSqliteSaveable(t *testing.T) {
	s := sqliteSample()
	if !s.saveable() {
		t.Error("sqlite must be saveable")
	}
	if got := mustGenSQL(s); !strings.Contains(got, "SQLite") {
		t.Errorf("GenSQL must emit sqlite DDL:\n%s", got)
	}
}

// TestSqliteJunctionRoundTrip: a many-to-many junction — composite PK over
// exactly two FK columns, the shape the client's createManyToMany builds — must
// keep both Pk and Ref through emit→parse, or the derived N:N badge would be
// lost on reopen.
func TestSqliteJunctionRoundTrip(t *testing.T) {
	s := &Schema{Dialect: DialectSqlite, Tables: []Table{
		{ID: "t1", Name: "users", Columns: []Col{{Name: "id", Type: "INT", Pk: true, Nn: true, Ai: true}}},
		{ID: "t2", Name: "posts", Columns: []Col{{Name: "id", Type: "INT", Pk: true, Nn: true, Ai: true}}},
		{ID: "t3", Name: "users_posts", Columns: []Col{
			{Name: "user_id", Type: "INT", Pk: true, Nn: true, Ref: &Ref{TableID: "t1", Action: "CASCADE"}},
			{Name: "post_id", Type: "INT", Pk: true, Nn: true, Ref: &Ref{TableID: "t2", Action: "CASCADE"}},
		}},
	}}
	sql := mustGenSQL(s)
	s2, err := ParseDDL(sql)
	if err != nil {
		t.Fatalf("junction round-trip: %v\n%s", err, sql)
	}
	j := s2.Tables[2]
	if len(j.Columns) != 2 {
		t.Fatalf("junction lost its composite PK on round-trip: %d columns\n%s", len(j.Columns), sql)
	}
	for i, want := range []string{"user_id", "post_id"} {
		c := j.Columns[i]
		if c.Pk != true || c.Ref == nil || c.Ref.TableID == "" {
			t.Errorf("junction member %q lost PK/FK on round-trip", want)
		}
	}
}
