// grammar_postgres_test.go — the PostgreSQL saved-file grammar: golden output,
// generate↔parse round-trip, escaping, and dialect detection.
//
// The mysql grammar has had its own suite since the parser was ported. Postgres
// gained a parser later, and two parsers for two emitters is exactly the shape
// that produced the earlier save/export drift — so each dialect is pinned
// independently rather than trusting that "the other one is covered".
package main

import (
	"slices"
	"strings"
	"testing"
)

// pgSchema returns sampleSchema tagged as postgres.
func pgSchema() *Schema {
	s := sampleSchema()
	s.Dialect = DialectPostgres
	return s
}

// TestPostgresGolden pins the exact saved-file bytes for postgres. Like
// TestGenSQLGolden, this is the test that fails on an output-format change;
// updating it is a deliberate act, since the format is a contract with files
// already on disk.
func TestPostgresGolden(t *testing.T) {
	const want = `-- Generated by erd-creator (PostgreSQL)
CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "email" VARCHAR(190) NOT NULL UNIQUE,
  "status" TEXT CHECK ("status" IN ('active', 'banned')),
  PRIMARY KEY ("id")
);
COMMENT ON COLUMN "users"."id" IS 'pk';
CREATE TABLE "posts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" INT,
  "tag" VARCHAR(40),
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_posts_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL
);
CREATE INDEX "idx_posts_tag" ON "posts" ("tag");
`
	if got := pgSchema().GenSQL(); got != want {
		t.Errorf("postgres saved-file format drifted.\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// TestPostgresRoundTripStable: emit → parse → emit must be byte-identical. The
// model itself is NOT expected to survive unchanged (see TestPostgresTypeMapping
// below); what must hold is that the second emit matches the first.
func TestPostgresRoundTripStable(t *testing.T) {
	sql1 := pgSchema().GenSQL()
	s2, err := ParseDDL(sql1)
	if err != nil {
		t.Fatal(err)
	}
	if s2.Dialect != DialectPostgres {
		t.Errorf("dialect lost on parse: got %q", s2.Dialect)
	}
	if sql2 := s2.GenSQL(); sql1 != sql2 {
		t.Errorf("round-trip drift:\n%s\n----\n%s", sql1, sql2)
	}
	// FK survived with its action intact — this regressed once when the extra
	// constraint-name capture group shifted the action's submatch index.
	if got := s2.Tables[1].Columns[1].Ref; got == nil || got.Action != "SET NULL" {
		t.Errorf("FK action lost in round-trip: %+v", got)
	}
}

// TestPostgresTypeMapping documents the one-way mappings. Postgres has no
// TINYINT/DATETIME, so those are genuinely lossy — the information does not
// exist in that representation, and asserting otherwise would be a lie.
//
// ENUM is the interesting case: it survives semantically (values intact) but
// its text normalizes, because splitTop re-joins the IN-list with ", ". So the
// contract is idempotent output, not model equality.
func TestPostgresTypeMapping(t *testing.T) {
	lossy := map[string]string{ // model type → type after one round-trip
		"TINYINT":       "SMALLINT",
		"DATETIME":      "TIMESTAMP",
		"JSON":          "JSONB",
		"DECIMAL(10,2)": "DECIMAL(10,2)",
		"VARCHAR(190)":  "VARCHAR(190)",
		"INT":           "INT",
		"BIGINT":        "BIGINT",
		"TEXT":          "TEXT",
	}
	for in, want := range lossy {
		s := &Schema{Dialect: DialectPostgres, Tables: []Table{
			{Id: "t1", Name: "t", Columns: []Col{{Name: "c", Type: in}}},
		}}
		parsed, err := ParseDDL(s.GenSQL())
		if err != nil {
			t.Fatalf("%s: %v", in, err)
		}
		if got := parsed.Tables[0].Columns[0].Type; got != want {
			t.Errorf("%s: round-tripped to %q, want %q", in, got, want)
		}
	}

	// ENUM values must survive; the surrounding text may normalize.
	for _, in := range []string{"ENUM('a','b')", "ENUM('x''y','z,w')", "ENUM('a','b','c')"} {
		s := &Schema{Dialect: DialectPostgres, Tables: []Table{
			{Id: "t1", Name: "t", Columns: []Col{{Name: "c", Type: in}}},
		}}
		parsed, err := ParseDDL(s.GenSQL())
		if err != nil {
			t.Fatalf("%s: %v", in, err)
		}
		got := parsed.Tables[0].Columns[0].Type
		if !strings.HasPrefix(got, "ENUM(") {
			t.Errorf("%s: lost its ENUM-ness, became %q", in, got)
		}
		if want, have := enumValues(in), enumValues(got); !slices.Equal(want, have) {
			t.Errorf("%s: values changed across round-trip: %q vs %q", in, want, have)
		}
		// and re-emitting must be stable, even though the text normalized
		if again := parsed.GenSQL(); again != s.GenSQL() {
			t.Errorf("%s: not idempotent:\n%s\n----\n%s", in, s.GenSQL(), again)
		}
	}
}

// TestPostgresRoundTripEscaping: identifiers with embedded quotes and comments
// with embedded single quotes must survive.
func TestPostgresRoundTripEscaping(t *testing.T) {
	s := &Schema{Dialect: DialectPostgres, Tables: []Table{{Id: "t1", Name: `we"ird`, Columns: []Col{
		{Name: `a"b`, Type: "INT", Pk: true},
		{Name: "c", Type: "VARCHAR(10)", Comment: `it's "quoted"`},
		{Name: "e", Type: "ENUM('a''b','c,d')"},
	}}}}
	sql := s.GenSQL()
	parsed, err := ParseDDL(sql)
	if err != nil {
		t.Fatal(err)
	}
	if got := parsed.GenSQL(); got != sql {
		t.Errorf("escaping drift:\n%s\n----\n%s", sql, got)
	}
	if parsed.Tables[0].Name != `we"ird` || parsed.Tables[0].Columns[0].Name != `a"b` {
		t.Error("double-quoted identifiers mangled")
	}
	if got := parsed.Tables[0].Columns[1].Comment; got != `it's "quoted"` {
		t.Errorf("comment mangled: %q", got)
	}
}

// TestPostgresEdgeCases: the FK-eligibility rules must match the mysql path.
func TestPostgresEdgeCases(t *testing.T) {
	t.Run("composite PK parent drops FK", func(t *testing.T) {
		s := &Schema{Dialect: DialectPostgres, Tables: []Table{
			{Id: "t1", Name: "m", Columns: []Col{{Name: "a", Type: "INT", Pk: true}, {Name: "b", Type: "INT", Pk: true}}},
			{Id: "t2", Name: "c", Columns: []Col{{Name: "id", Type: "INT", Pk: true}, {Name: "mid", Type: "INT", Ref: &Ref{TableId: "t1"}}}},
		}}
		sql := s.GenSQL()
		if strings.Contains(sql, "FOREIGN KEY") {
			t.Errorf("FK onto composite PK must not be emitted:\n%s", sql)
		}
		parsed, err := ParseDDL(sql)
		if err != nil {
			t.Fatal(err)
		}
		if n := len(pkCols(parsed.Tables[0])); n != 2 {
			t.Errorf("composite PK lost: %d cols", n)
		}
	})

	t.Run("no-PK parent drops FK", func(t *testing.T) {
		s := &Schema{Dialect: DialectPostgres, Tables: []Table{
			{Id: "t1", Name: "p", Columns: []Col{{Name: "email", Type: "VARCHAR(9)"}}},
			{Id: "t2", Name: "c", Columns: []Col{{Name: "id", Type: "INT", Pk: true}, {Name: "pid", Type: "VARCHAR(9)", Ref: &Ref{TableId: "t1"}}}},
		}}
		if strings.Contains(s.GenSQL(), "FOREIGN KEY") {
			t.Errorf("FK onto PK-less parent must not be emitted:\n%s", s.GenSQL())
		}
	})

	t.Run("empty table skipped", func(t *testing.T) {
		s := &Schema{Dialect: DialectPostgres, Tables: []Table{{Id: "t1", Name: "empty"}}}
		if strings.Contains(s.GenSQL(), "CREATE TABLE") {
			t.Error("empty table emitted")
		}
	})

	t.Run("self reference emits FK", func(t *testing.T) {
		s := &Schema{Dialect: DialectPostgres, Tables: []Table{
			{Id: "t1", Name: "n", Columns: []Col{{Name: "id", Type: "INT", Pk: true}, {Name: "parent_id", Type: "INT", Ref: &Ref{TableId: "t1"}}}},
		}}
		sql := s.GenSQL()
		if !strings.Contains(sql, "FOREIGN KEY") {
			t.Errorf("self-referencing FK missing:\n%s", sql)
		}
		parsed, err := ParseDDL(sql)
		if err != nil {
			t.Fatal(err)
		}
		if parsed.Tables[0].Columns[1].Ref == nil {
			t.Error("self-ref FK lost in round-trip")
		}
	})

	t.Run("dangling FK dropped, not fatal", func(t *testing.T) {
		// The header matters: without it the input would detect as mysql and
		// exercise the wrong parser.
		sql := "-- Generated by erd-creator (PostgreSQL)\nCREATE TABLE \"a\" (\n  \"id\" INT,\n  CONSTRAINT \"fk_a_id\" FOREIGN KEY (\"id\") REFERENCES \"gone\" (\"id\") ON DELETE CASCADE\n);\n"
		parsed, err := ParseDDL(sql)
		if err != nil {
			t.Fatal(err)
		}
		if parsed.Tables[0].Columns[0].Ref != nil {
			t.Error("dangling ref must be dropped")
		}
	})
}

// TestPostgresParseRejects: malformed input is rejected rather than half-read,
// matching the mysql parser's contract.
func TestPostgresParseRejects(t *testing.T) {
	cases := map[string]string{
		"unsupported clause": "-- Generated by erd-creator (PostgreSQL)\nCREATE TABLE \"a\" (\n  CHECK (x)\n);\n",
		"garbage line":       "-- Generated by erd-creator (PostgreSQL)\nCREATE TABLE \"a\" (\n  ??? \n);\n",
		"outside table":      "-- Generated by erd-creator (PostgreSQL)\nDROP TABLE \"a\";\n",
		"no tables":          "-- Generated by erd-creator (PostgreSQL)\n-- nothing\n",
		"duplicate table":    "-- Generated by erd-creator (PostgreSQL)\nCREATE TABLE \"a\" (\n  \"id\" INT\n);\nCREATE TABLE \"a\" (\n  \"id\" INT\n);\n",
	}
	for name, sql := range cases {
		if _, err := ParseDDL(sql); err == nil {
			t.Errorf("%s: expected error", name)
		}
	}
}

// TestDialectDetection: the header decides the parser, and anything unmarked
// stays mysql so files written before dialects existed keep loading.
func TestDialectDetection(t *testing.T) {
	cases := map[string]string{
		"-- Generated by erd-creator (PostgreSQL)\nCREATE TABLE \"a\" (": DialectPostgres,
		"-- Generated by erd-creator (Postgres)\nCREATE TABLE \"a\" (":   DialectPostgres,
		"-- Generated by erd-creator\nCREATE TABLE `a` (":                DialectMysql,
		"-- Generated by erd-creator (MySQL)\nCREATE TABLE `a` (":        DialectMysql,
		"-- some hand-written file\nCREATE TABLE `a` (":                  DialectMysql,
		"CREATE TABLE `a` (": DialectMysql,
		"":                   DialectMysql,
	}
	for sql, want := range cases {
		if got := detectDialect(sql); got != want {
			t.Errorf("detectDialect(%q) = %q, want %q", firstLine(sql), got, want)
		}
	}
}

func firstLine(s string) string {
	if i := strings.Index(s, "\n"); i >= 0 {
		return s[:i]
	}
	return s
}

// TestNormalizeDialect: spellings map to canonical names, unknown input falls
// back to mysql rather than erroring (an unset dialect is the common case).
func TestNormalizeDialect(t *testing.T) {
	cases := map[string]string{
		"":            DialectMysql,
		"mysql":       DialectMysql,
		"MySQL":       DialectMysql,
		"mariadb":     DialectMysql, // shares the mysql grammar
		"postgres":    DialectPostgres,
		"PostgreSQL":  DialectPostgres,
		"postgresql":  DialectPostgres,
		"pg":          DialectPostgres,
		"  postgres ": DialectPostgres,
		"sqlite":      DialectMysql, // export-only: not a save format
		"nonsense":    DialectMysql,
	}
	for in, want := range cases {
		if got := normalizeDialect(in); got != want {
			t.Errorf("normalizeDialect(%q) = %q, want %q", in, got, want)
		}
	}
}

// TestMysqlFilesUnaffected: adding dialects must not change what an unmarked
// (pre-dialect) file emits, or every existing .sql would churn on save.
func TestMysqlFilesUnaffected(t *testing.T) {
	legacy := sampleSchema() // Dialect is "" — as every existing file is
	sql := legacy.GenSQL()
	if strings.Contains(sql, "(PostgreSQL)") {
		t.Errorf("unmarked schema emitted postgres:\n%s", sql)
	}
	if !strings.HasPrefix(sql, "-- Generated by erd-creator\n") {
		t.Errorf("legacy header changed:\n%s", firstLine(sql))
	}
	// and it round-trips through the mysql parser as before
	parsed, err := ParseDDL(sql)
	if err != nil {
		t.Fatal(err)
	}
	if parsed.GenSQL() != sql {
		t.Error("legacy file round-trip drifted")
	}
	if parsed.Dialect != DialectMysql {
		t.Errorf("legacy file parsed as %q, want mysql", parsed.Dialect)
	}
}
