// grammar_sqlite_test.go — the SQLite saved-file grammar: emit↔parse round-trip,
// type mapping, comments, and rejects. Mirrors grammar_test.go's coverage of the
// mysql path and grammar_postgres_test.go's coverage of the postgres one.
package main

import (
	"strings"
	"testing"
)

// sqliteSample is sampleSchema with a few constructs SQLite renders specially:
// BOOLEAN and DATETIME (no native type), an indexed column, and an FK action.
func sqliteSample() *Schema {
	return &Schema{Dialect: DialectSqlite, Tables: []Table{
		{Id: "t1", Name: "users", Columns: []Col{
			{Name: "id", Type: "INT", Pk: true, Nn: true, Ai: true, Comment: "pk"},
			{Name: "email", Type: "VARCHAR(190)", Nn: true, Ux: true},
			{Name: "status", Type: "ENUM('active','banned')"},
			{Name: "active", Type: "BOOLEAN"},
			{Name: "seen_at", Type: "DATETIME", Comment: "last login"},
		}},
		{Id: "t2", Name: "posts", Columns: []Col{
			{Name: "id", Type: "BIGINT", Pk: true, Nn: true, Ai: true},
			{Name: "user_id", Type: "INT", Ref: &Ref{TableId: "t1", Action: "SET NULL"}},
			{Name: "tag", Type: "VARCHAR(40)", Ix: true},
		}},
	}}
}

func TestSqliteRoundTripStable(t *testing.T) {
	s := sqliteSample()
	sql1 := s.GenSQL()
	s2, err := ParseDDL(sql1)
	if err != nil {
		t.Fatal(err)
	}
	if sql2 := s2.GenSQL(); sql1 != sql2 {
		t.Errorf("round-trip drift:\n%s\n----\n%s", sql1, sql2)
	}
	// identity: a sqlite file must reopen as sqlite, not silently become mysql
	if s2.Dialect != DialectSqlite {
		t.Errorf("dialect = %q, want %q", s2.Dialect, DialectSqlite)
	}
}

func TestSqliteDetectDialect(t *testing.T) {
	if got := detectDialect(sqliteSample().GenSQL()); got != DialectSqlite {
		t.Errorf("detectDialect = %q, want sqlite", got)
	}
	// the sqlite header contains the generic marker too, so ordering matters:
	// mysql must not win on the shared "generated by erd-creator" prefix
	if got := detectDialect("-- Generated by erd-creator (SQLite)\nCREATE TABLE `a` (\n  `id` INT\n);\n"); got != DialectSqlite {
		t.Errorf("detectDialect = %q, want sqlite", got)
	}
}

// TestSqliteShapes pins the constructs that differ from MySQL's rendering.
func TestSqliteShapes(t *testing.T) {
	sql := sqliteSample().GenSQL()
	for _, want := range []string{
		"INTEGER PRIMARY KEY",                      // rowid alias instead of AUTO_INCREMENT
		"CHECK (`status` IN ('active', 'banned'))", // ENUM → TEXT + CHECK
		"CREATE INDEX IF NOT EXISTS `idx_posts_tag` ON `posts` (`tag`);",
		"FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL",
	} {
		if !strings.Contains(sql, want) {
			t.Errorf("missing %q in:\n%s", want, sql)
		}
	}
	for _, banned := range []string{"AUTO_INCREMENT", "ENGINE=InnoDB", "ENUM("} {
		if strings.Contains(sql, banned) {
			t.Errorf("sqlite output must not contain %q:\n%s", banned, sql)
		}
	}
}

// TestSqliteTypeMappingIsStable: SQLite has no BOOLEAN or datetime type, so the
// emitter writes INTEGER/TEXT. Those are valid model types, so the mapping is
// one-way on purpose — re-emitting a reopened file must not keep rewriting the
// type (BOOLEAN→INTEGER→INTEGER), which is what a lossy round-trip would do.
func TestSqliteTypeMappingIsStable(t *testing.T) {
	s := sqliteSample()
	s2, err := ParseDDL(s.GenSQL())
	if err != nil {
		t.Fatal(err)
	}
	if got := s2.GenSQL(); got != s.GenSQL() {
		t.Errorf("type mapping not stable:\n%s\n----\n%s", s.GenSQL(), got)
	}
	byName := map[string]Col{}
	for _, c := range s2.Tables[0].Columns {
		byName[c.Name] = c
	}
	if byName["active"].Type != "INTEGER" {
		t.Errorf("BOOLEAN should read back as INTEGER, got %q", byName["active"].Type)
	}
	if byName["seen_at"].Type != "TEXT" {
		t.Errorf("DATETIME should read back as TEXT, got %q", byName["seen_at"].Type)
	}
	// ENUM is the exception: its values live in the CHECK constraint, so they
	// must be recovered exactly or the schema would change on reopen.
	if got := byName["status"].Type; got != "ENUM('active','banned')" {
		t.Errorf("ENUM not recovered from CHECK: %q", got)
	}
}

// TestSqliteCommentRoundTrip: the comment rides in the same comma-joined entry
// as its column. As a separate entry it picked up the join's comma and the
// parser read it back as part of the text ("pk" → "pk,").
func TestSqliteCommentRoundTrip(t *testing.T) {
	s := &Schema{Dialect: DialectSqlite, Tables: []Table{{Id: "t1", Name: "t", Columns: []Col{
		{Name: "id", Type: "INT", Pk: true, Ai: true, Comment: "pk"},
		{Name: "note", Type: "VARCHAR(10)", Comment: "no trailing comma"},
	}}}}
	sql := s.GenSQL()
	if strings.Contains(sql, "pk,") {
		t.Errorf("comment picked up the join comma:\n%s", sql)
	}
	s2, err := ParseDDL(sql)
	if err != nil {
		t.Fatal(err)
	}
	if got := s2.Tables[0].Columns[0].Comment; got != "pk" {
		t.Errorf("comment = %q, want %q", got, "pk")
	}
	if got := s2.Tables[0].Columns[1].Comment; got != "no trailing comma" {
		t.Errorf("comment = %q, want %q", got, "no trailing comma")
	}
}

// TestSqliteCommentWithColon: the "-- name: text" prefix is stripped by matching
// the KNOWN column name, not by splitting on the first ": ", so a colon in
// either the name or the text survives.
func TestSqliteCommentWithColon(t *testing.T) {
	s := &Schema{Dialect: DialectSqlite, Tables: []Table{{Id: "t1", Name: "t", Columns: []Col{
		{Name: "a:b", Type: "INT", Pk: true, Ai: true, Comment: "has: colon"},
		{Name: "plain", Type: "INT", Comment: "x:y:z"},
	}}}}
	sql := s.GenSQL()
	s2, err := ParseDDL(sql)
	if err != nil {
		t.Fatalf("%v\n%s", err, sql)
	}
	if got := s2.Tables[0].Columns[0].Comment; got != "has: colon" {
		t.Errorf("comment on colon-named column = %q, want %q", got, "has: colon")
	}
	if got := s2.Tables[0].Columns[0].Name; got != "a:b" {
		t.Errorf("column name = %q, want %q", got, "a:b")
	}
	if got := s2.Tables[0].Columns[1].Comment; got != "x:y:z" {
		t.Errorf("comment = %q, want %q", got, "x:y:z")
	}
}

// TestSqliteIndexedPkKeepsIndex: the rowid-alias branch used to `continue` past
// the index collection, so an indexed PK column silently lost its CREATE INDEX.
func TestSqliteIndexedPkKeepsIndex(t *testing.T) {
	s := &Schema{Dialect: DialectSqlite, Tables: []Table{{Id: "t1", Name: "t", Columns: []Col{
		{Name: "id", Type: "INT", Pk: true, Ai: true, Ix: true},
	}}}}
	sql := s.GenSQL()
	if !strings.Contains(sql, "CREATE INDEX IF NOT EXISTS `idx_t_id`") {
		t.Errorf("indexed PK lost its index:\n%s", sql)
	}
	s2, err := ParseDDL(sql)
	if err != nil {
		t.Fatal(err)
	}
	if !s2.Tables[0].Columns[0].Ix {
		t.Error("index flag lost on round-trip")
	}
	if got := s2.GenSQL(); got != sql {
		t.Errorf("drift:\n%s\n----\n%s", sql, got)
	}
}

func TestSqliteCompositePK(t *testing.T) {
	s := &Schema{Dialect: DialectSqlite, Tables: []Table{{Id: "t1", Name: "m", Columns: []Col{
		{Name: "a", Type: "INT", Pk: true},
		{Name: "b", Type: "INT", Pk: true},
	}}}}
	sql := s.GenSQL()
	if !strings.Contains(sql, "PRIMARY KEY (`a`, `b`)") {
		t.Errorf("composite PK not emitted as a table constraint:\n%s", sql)
	}
	s2, err := ParseDDL(sql)
	if err != nil {
		t.Fatal(err)
	}
	if n := len(pkCols(s2.Tables[0])); n != 2 {
		t.Errorf("composite PK lost: %d cols", n)
	}
}

// TestSqliteEscaping: identifiers are backticked like MySQL's, and enum values
// containing a comma must not split the CHECK list.
func TestSqliteEscaping(t *testing.T) {
	s := &Schema{Dialect: DialectSqlite, Tables: []Table{{Id: "t1", Name: "we`ird", Columns: []Col{
		{Name: "a`b", Type: "INT", Pk: true, Ai: true},
		{Name: "e", Type: "ENUM('a''b','c,d')"},
		{Name: "c", Type: "VARCHAR(10)", Comment: "it's \"quoted\""},
	}}}}
	sql := s.GenSQL()
	s2, err := ParseDDL(sql)
	if err != nil {
		t.Fatalf("%v\n%s", err, sql)
	}
	if s2.Tables[0].Name != "we`ird" || s2.Tables[0].Columns[0].Name != "a`b" {
		t.Error("backtick identifiers mangled")
	}
	if got := s2.Tables[0].Columns[1].Type; got != "ENUM('a''b','c,d')" {
		t.Errorf("enum values mangled: %q", got)
	}
	if got := s2.Tables[0].Columns[2].Comment; got != `it's "quoted"` {
		t.Errorf("comment mangled: %q", got)
	}
	if got := s2.GenSQL(); got != sql {
		t.Errorf("escaping drift:\n%s\n----\n%s", sql, got)
	}
}

func TestSqliteRejects(t *testing.T) {
	header := "-- Generated by erd-creator (SQLite)\n"
	cases := map[string]string{
		"garbage line":    header + "CREATE TABLE `a` (\n  ???\n);\n",
		"no tables":       header + "-- nothing\n",
		"outside table":   header + "DROP TABLE `a`;\n",
		"duplicate table": header + "CREATE TABLE `a` (\n  `id` INT\n);\nCREATE TABLE `a` (\n  `id` INT\n);\n",
	}
	for name, sql := range cases {
		if _, err := ParseDDL(sql); err == nil {
			t.Errorf("%s: expected error", name)
		}
	}
}

// TestSqliteDanglingFKDropped mirrors the mysql/postgres behaviour: an FK whose
// parent is absent is dropped rather than crashing the load.
func TestSqliteDanglingFKDropped(t *testing.T) {
	sql := "-- Generated by erd-creator (SQLite)\nCREATE TABLE `a` (\n  `id` INT,\n  FOREIGN KEY (`id`) REFERENCES `gone` (`id`) ON DELETE CASCADE\n);\n"
	s, err := ParseDDL(sql)
	if err != nil {
		t.Fatal(err)
	}
	if s.Tables[0].Columns[0].Ref != nil {
		t.Error("dangling ref must be dropped")
	}
}

// TestSqliteSaveable: sqlite is a first-class saveable dialect now, so the save
// guard must accept it (it previously refused, which is what kept the missing
// parser from producing unreadable files).
func TestSqliteSaveable(t *testing.T) {
	s := sqliteSample()
	if !s.saveable() {
		t.Error("sqlite must be saveable")
	}
	if got := s.GenSQL(); !strings.Contains(got, "SQLite") {
		t.Errorf("GenSQL must emit sqlite DDL:\n%s", got)
	}
}
