// pattern_gap_test.go — pins for the just-applied pattern refactors plus
// remaining gaps. Append-only home for these; regress_parse_test.go already
// covers single-column ghost PK/UX/IX and the open/copy 413 paths, so those
// are not duplicated here.
//
// Each test names the user-visible behaviour: identical diagnostics across
// grammars, 500s that never echo paths, unified 400 prefixes.
package main

import (
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// ---- 1. markPKColumns: a composite PK naming a ghost column errors
// identically across all grammars ----
//
// TestGhostPKUXIXRejectedAllDialects pins single-column ghost clauses; the
// shared markPKColumns loop also serves multi-column PKs, and the three
// strict parsers must report the same text (same line, same quoting of the
// name) so a file refused by one grammar is refused the same way by all.
func TestGhostCompositePKIdenticalAcrossDialects(t *testing.T) {
	fixtures := map[string]string{
		DialectMysql: "-- Generated by erd-creator\n" +
			"CREATE TABLE `a` (\n  `id` INT,\n  PRIMARY KEY (`id`, `ghost`)\n) ENGINE=InnoDB;\n",
		DialectMariaDB: "-- Generated by erd-creator (MariaDB)\n" +
			"CREATE TABLE `a` (\n  `id` INT,\n  PRIMARY KEY (`id`, `ghost`)\n) ENGINE=InnoDB;\n",
		DialectPostgres: "-- Generated by erd-creator (PostgreSQL)\n" +
			"CREATE TABLE \"a\" (\n  \"id\" INT,\n  PRIMARY KEY (\"id\", \"ghost\")\n);\n",
		DialectSqlite: "-- Generated by erd-creator (SQLite)\n" +
			"CREATE TABLE `a` (\n  `id` INT,\n  PRIMARY KEY (`id`, `ghost`)\n);\n",
	}
	var want string
	for _, dialect := range []string{DialectMysql, DialectMariaDB, DialectPostgres, DialectSqlite} {
		_, err := ParseDDL(fixtures[dialect])
		if err == nil {
			t.Fatalf("%s: composite PK over ghost column accepted", dialect)
		}
		if want == "" {
			want = err.Error()
			if !strings.Contains(want, `unknown column "ghost"`) {
				t.Fatalf("first error does not name the ghost column: %q", want)
			}
			continue
		}
		if err.Error() != want {
			t.Errorf("%s error %q differs from %q", dialect, err.Error(), want)
		}
	}
}

// ---- 2. internalFail: 500 responses never echo filesystem paths ----
//
// The helper's contract is that format/args go to the log only and the body
// is the bare msg. Pinned directly, plus through the two store paths whose
// failures reach it without an existing pin (save temp creation, copy read).
func TestInternalFailNeverEchoesPath(t *testing.T) {
	rec := httptest.NewRecorder()
	internalFail(rec, "save failed", "save temp %s: %v", "/etc/secret/store", errors.New("boom"))
	if rec.Code != http.StatusInternalServerError {
		t.Fatalf("code %d, want 500", rec.Code)
	}
	if body := rec.Body.String(); body != "save failed\n" {
		t.Errorf("body %q, want exactly the msg", body)
	}
	if strings.Contains(rec.Body.String(), "/etc/secret") {
		t.Errorf("path leaked into 500 body: %q", rec.Body.String())
	}
}

// A store dir that is a FILE, not a directory: the schema validates and the
// DDL generates, so save reaches createTemp, which fails (not a directory).
// User-visible: 500 "save failed" with no path.
func TestSaveTempFailureIs500WithoutPath(t *testing.T) {
	dir := t.TempDir()
	notADir := filepath.Join(dir, "notadir")
	if err := os.WriteFile(notADir, []byte("x"), 0o644); err != nil {
		t.Fatal(err)
	}
	h := handleFiles(notADir)
	rec := do(t, h, "PUT", "/api/files/a.sql", jsonBody(sampleSchema()))
	if rec.Code != http.StatusInternalServerError {
		t.Fatalf("code %d, want 500 (%s)", rec.Code, rec.Body.String())
	}
	if !strings.Contains(rec.Body.String(), "save failed") {
		t.Errorf("body should say 'save failed': %q", rec.Body.String())
	}
	if strings.Contains(rec.Body.String(), "notadir") {
		t.Errorf("path leaked into 500 body: %q", rec.Body.String())
	}
}

// A source named *.sql that is a DIRECTORY: stat passes, the open succeeds,
// and the read fails (EISDIR), reaching copyFile's internalFail branch.
// User-visible: 500 "copy failed" with no path, and no target left behind.
func TestCopyReadFailureIs500WithoutPath(t *testing.T) {
	dir := t.TempDir()
	if err := os.Mkdir(filepath.Join(dir, "a.sql"), 0o755); err != nil {
		t.Fatal(err)
	}
	h := handleFiles(dir)
	rec := do(t, h, "POST", "/api/files/copy", jsonBody(map[string]string{"from": "a.sql", "to": "b.sql"}))
	if rec.Code != http.StatusInternalServerError {
		t.Fatalf("code %d, want 500 (%s)", rec.Code, rec.Body.String())
	}
	if !strings.Contains(rec.Body.String(), "copy failed") {
		t.Errorf("body should say 'copy failed': %q", rec.Body.String())
	}
	if strings.Contains(rec.Body.String(), dir) {
		t.Errorf("path leaked into 500 body: %q", rec.Body.String())
	}
	if _, err := os.Stat(filepath.Join(dir, "b.sql")); err == nil {
		t.Error("failed copy left a target behind")
	}
}

// ---- 3. failValidation/failBadJSON: shared prefixes on every 400 ----
//
// The refactors unified every schema/JSON rejection onto two helpers; the pin
// is the prefix on each reachable path, so a future inline http.Error with a
// different wording fails here.
func TestFailPrefixesUnified(t *testing.T) {
	badSchema := func() []byte {
		b, err := json.Marshal(Schema{Tables: []Table{{ID: "t1", Name: "bad\x01", Columns: []Col{}}}})
		if err != nil {
			t.Fatalf("marshal: %v", err)
		}
		return b
	}

	// invalid schema → "invalid schema: " on lint, inserts, export, save
	lintRec := do(t, http.HandlerFunc(handleSchemaAPI), "POST", "/api/lint", strings.NewReader(string(badSchema())))
	if lintRec.Code != http.StatusBadRequest || !strings.HasPrefix(lintRec.Body.String(), "invalid schema: ") {
		t.Errorf("lint invalid schema: %d %q", lintRec.Code, lintRec.Body.String())
	}
	insRec := do(t, http.HandlerFunc(handleSchemaAPI), "POST", "/api/inserts", strings.NewReader(string(badSchema())))
	if insRec.Code != http.StatusBadRequest || !strings.HasPrefix(insRec.Body.String(), "invalid schema: ") {
		t.Errorf("inserts invalid schema: %d %q", insRec.Code, insRec.Body.String())
	}
	expRec := do(t, http.HandlerFunc(handleExport), "POST", "/export", strings.NewReader(
		`{"dialect":"mysql","schema":{"tables":[{"id":"t1","name":"t","columns":[{"name":"a","type":"VARCHAR(1;DROP)"}]}]}}`))
	if expRec.Code != http.StatusBadRequest || !strings.HasPrefix(expRec.Body.String(), "invalid schema: ") {
		t.Errorf("export invalid schema: %d %q", expRec.Code, expRec.Body.String())
	}
	saveRec := do(t, handleFiles(t.TempDir()), "PUT", "/api/files/a.sql", strings.NewReader(string(badSchema())))
	if saveRec.Code != http.StatusBadRequest || !strings.HasPrefix(saveRec.Body.String(), "invalid schema: ") {
		t.Errorf("save invalid schema: %d %q", saveRec.Code, saveRec.Body.String())
	}

	// bad JSON → "bad json: " on lint, export, save, rename, copy
	for name, rec := range map[string]*httptest.ResponseRecorder{
		"lint":   do(t, http.HandlerFunc(handleSchemaAPI), "POST", "/api/lint", strings.NewReader(`{oops`)),
		"export": do(t, http.HandlerFunc(handleExport), "POST", "/export", strings.NewReader(`{oops`)),
		"save":   do(t, handleFiles(t.TempDir()), "PUT", "/api/files/a.sql", strings.NewReader(`{oops`)),
		"rename": do(t, handleFiles(t.TempDir()), "POST", "/api/files/rename", strings.NewReader(`{oops`)),
		"copy":   do(t, handleFiles(t.TempDir()), "POST", "/api/files/copy", strings.NewReader(`{oops`)),
	} {
		if rec.Code != http.StatusBadRequest || !strings.HasPrefix(rec.Body.String(), "bad json: ") {
			t.Errorf("%s bad json: %d %q", name, rec.Code, rec.Body.String())
		}
	}
}

// ---- 4. statCapped: boundary + error passthrough (the 413s themselves are
// pinned by TestSizeCapOpenAndCopy; this pins the helper both callers share)
func TestStatCappedBoundary(t *testing.T) {
	dir := t.TempDir()
	at := filepath.Join(dir, "at.sql")
	if err := os.WriteFile(at, make([]byte, maxOpenFile), 0o644); err != nil {
		t.Fatal(err)
	}
	if tooLarge, err := statCapped(at); err != nil || tooLarge {
		t.Errorf("exactly maxOpenFile: tooLarge=%v err=%v, want false/nil", tooLarge, err)
	}
	over := filepath.Join(dir, "over.sql")
	if err := os.WriteFile(over, make([]byte, maxOpenFile+1), 0o644); err != nil {
		t.Fatal(err)
	}
	if tooLarge, err := statCapped(over); err != nil || !tooLarge {
		t.Errorf("maxOpenFile+1: tooLarge=%v err=%v, want true/nil", tooLarge, err)
	}
	if _, err := statCapped(filepath.Join(dir, "gone.sql")); err == nil {
		t.Error("missing file should return the stat error for the caller to map")
	}
}

// ---- 5. uncovered refactor branches ----

// attachPendingFKs drops an FK whose CHILD column is gone (valid parent table,
// ghost child): the refactored guard split table-missing from column-missing,
// and only the table half had a pin. The drop must warn "unknown column".
func TestAttachPendingFKUnknownColumnWarns(t *testing.T) {
	s := &Schema{Tables: []Table{
		{ID: "t1", Name: "users", Columns: []Col{{Name: "id", Type: "INT", Pk: true}}},
		{ID: "t2", Name: "posts", Columns: []Col{{Name: "user_id", Type: "INT"}}},
	}}
	byName := map[string]int{"users": 0}
	byID := map[string]int{"t1": 0, "t2": 1}
	var reasons []string
	attachPendingFKs(s, byName, byID,
		[]pendingFK{{tableID: "t2", col: "ghost", table: "users", action: "CASCADE"}},
		func(p pendingFK, reason string) { reasons = append(reasons, reason) })
	if s.Tables[1].Columns[0].Ref != nil {
		t.Error("FK on a ghost child column must be dropped")
	}
	if len(reasons) != 1 || reasons[0] != "unknown column" {
		t.Fatalf("drop reason = %v, want [unknown column]", reasons)
	}
	if w := fkDropWarning(pendingFK{col: "ghost"}, "unknown column"); !strings.Contains(w, "unknown column") {
		t.Errorf("warning does not name the cause: %q", w)
	}
	// default branch: an unexpected reason still renders, never empty
	if w := fkDropWarning(pendingFK{col: "c"}, "bogus"); !strings.Contains(w, "dropped") {
		t.Errorf("default warning renders nothing useful: %q", w)
	}
}

// lintFK strips the postgres [] suffix before comparing: an INT[] FK onto an
// INT PK is a match, not a mismatch. The strip was added with the lintFK
// extraction and had no direct pin; the negative control keeps it honest.
func TestLintArraySuffixNoMismatch(t *testing.T) {
	match := &Schema{Tables: []Table{
		{ID: "t1", Name: "p", Columns: []Col{{Name: "id", Type: "INT", Pk: true}}},
		{ID: "t2", Name: "c", Columns: []Col{{Name: "tags", Type: "INT[]", Ref: &Ref{TableID: "t1"}}}},
	}}
	if l := match.Lint(); len(l) != 0 {
		t.Errorf("INT[] FK onto INT PK flagged: %v", l)
	}
	mismatch := &Schema{Tables: []Table{
		{ID: "t1", Name: "p", Columns: []Col{{Name: "id", Type: "INT", Pk: true}}},
		{ID: "t2", Name: "c", Columns: []Col{{Name: "v", Type: "VARCHAR(9)", Ref: &Ref{TableID: "t1"}}}},
	}}
	if l := mismatch.Lint(); len(l) == 0 {
		t.Error("VARCHAR FK onto INT PK no longer flagged")
	}
}

// saveFile's validateDialectForSave branch: an unknown non-empty dialect is
// refused with the shared prefix before anything reaches disk (export's
// unknown-dialect 400 is pinned in main_test.go; the save half was not).
func TestSaveUnknownDialectRejected(t *testing.T) {
	dir := t.TempDir()
	h := handleFiles(dir)
	body, _ := json.Marshal(&Schema{Dialect: "oracle", Tables: []Table{
		{ID: "t1", Name: "t", Columns: []Col{{Name: "id", Type: "INT"}}},
	}})
	rec := do(t, h, "PUT", "/api/files/a.sql", strings.NewReader(string(body)))
	if rec.Code != http.StatusBadRequest {
		t.Fatalf("code %d, want 400 (%s)", rec.Code, rec.Body.String())
	}
	if !strings.HasPrefix(rec.Body.String(), "invalid schema: ") {
		t.Errorf("body lacks the shared prefix: %q", rec.Body.String())
	}
	if !strings.Contains(rec.Body.String(), "oracle") {
		t.Errorf("body should name the dialect: %q", rec.Body.String())
	}
	if _, err := os.Stat(filepath.Join(dir, "a.sql")); err == nil {
		t.Error("rejected save left a file behind")
	}
}
