// regress_parse_test.go — regression pins for recently-fixed parse and
// validation defects, plus the fail-closed/size-cap boundaries.
//
// Each test names the user-visible behaviour: a file that fails to reopen,
// a relationship that vanishes, an oversized upload. Assertions stay on
// errors/warnings/status codes, not on internal helpers.
package main

import (
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// ---- 1. stray END TABLE: a file must fail to open, not crash the server ----
//
// A ") ENGINE=InnoDB" line with no open CREATE TABLE used to index Tables[-1]
// and panic. The user-visible contract: the open is refused with a diagnostic
// naming the cause ("not inside CREATE TABLE").
func TestStrayEndTableRefused(t *testing.T) {
	cases := map[string]string{
		"lone end with comment": ") ENGINE=InnoDB COMMENT='x';",
		"double end after close": "-- Generated by erd-creator\n" +
			"CREATE TABLE `a` (\n  `id` INT\n) ENGINE=InnoDB;\n) ENGINE=InnoDB;\n",
		"end before any table": "-- Generated by erd-creator\n) ENGINE=InnoDB;\n" +
			"CREATE TABLE `a` (\n  `id` INT\n) ENGINE=InnoDB;\n",
	}
	for name, sql := range cases {
		func() {
			defer func() {
				if r := recover(); r != nil {
					t.Errorf("%s: panicked: %v", name, r)
				}
			}()
			_, _, err := parseMysql(sql, DialectMysql)
			if err == nil {
				t.Errorf("%s: expected error, got none", name)
				return
			}
			if !strings.Contains(err.Error(), "not inside CREATE TABLE") {
				t.Errorf("%s: error %q does not name the cause", name, err)
			}
		}()
	}
}

// The same stray-end shape through the public entry point, which is what the
// open-file path calls.
func TestStrayEndTableViaParseDDL(t *testing.T) {
	_, err := ParseDDL(") ENGINE=InnoDB COMMENT='x';")
	if err == nil {
		t.Fatal("expected error")
	}
	if strings.Contains(err.Error(), "panic") {
		t.Errorf("panic leaked: %v", err)
	}
	if !strings.Contains(err.Error(), "not inside CREATE TABLE") {
		t.Errorf("error does not name the cause: %v", err)
	}
}

// ---- 2. ghost PK/UX/single-IX: a clause naming a column that does not exist
// must be refused, not silently dropped (the PK/index would vanish with no
// diagnostic). One case per clause kind per dialect. ----

func ghostDDL(dialect, clause string) string {
	switch dialect {
	case DialectPostgres:
		head := "-- Generated by erd-creator (PostgreSQL)\n"
		switch clause {
		case "pk":
			return head + "CREATE TABLE \"a\" (\n  \"id\" INT,\n  PRIMARY KEY (\"ghost\")\n);\n"
		case "ix":
			return head + "CREATE TABLE \"a\" (\n  \"id\" INT\n);\nCREATE INDEX \"ix\" ON \"a\" (\"ghost\");\n"
		}
	case DialectSqlite:
		head := "-- Generated by erd-creator (SQLite)\n"
		switch clause {
		case "pk":
			return head + "CREATE TABLE `a` (\n  `id` INT,\n  PRIMARY KEY (`ghost`)\n);\n"
		case "ix":
			return head + "CREATE TABLE `a` (\n  `id` INT\n);\nCREATE INDEX IF NOT EXISTS `ix` ON `a` (`ghost`);\n"
		}
	default: // mysql + mariadb share the grammar
		head := "-- Generated by erd-creator\n"
		if dialect == DialectMariaDB {
			head = "-- Generated by erd-creator (MariaDB)\n"
		}
		switch clause {
		case "pk":
			return head + "CREATE TABLE `a` (\n  `id` INT,\n  PRIMARY KEY (`ghost`)\n) ENGINE=InnoDB;\n"
		case "ux":
			return head + "CREATE TABLE `a` (\n  `id` INT,\n  UNIQUE KEY `ux` (`ghost`)\n) ENGINE=InnoDB;\n"
		case "ix":
			return head + "CREATE TABLE `a` (\n  `id` INT,\n  KEY `ix` (`ghost`)\n) ENGINE=InnoDB;\n"
		}
	}
	return ""
}

func TestGhostPKUXIXRejectedAllDialects(t *testing.T) {
	// which clause kinds each dialect's grammar expresses: postgres/sqlite
	// render single-column uniqueness as a column flag, so only pk/ix apply
	clauses := map[string][]string{
		DialectMysql:    {"pk", "ux", "ix"},
		DialectMariaDB:  {"pk", "ux", "ix"},
		DialectPostgres: {"pk", "ix"},
		DialectSqlite:   {"pk", "ix"},
	}
	for dialect, kinds := range clauses {
		for _, kind := range kinds {
			sql := ghostDDL(dialect, kind)
			if sql == "" {
				t.Fatalf("%s/%s: no fixture", dialect, kind)
			}
			_, err := ParseDDL(sql)
			if err == nil {
				t.Errorf("%s %s on ghost column: accepted, want rejection", dialect, kind)
				continue
			}
			if !strings.Contains(err.Error(), "unknown column") {
				t.Errorf("%s %s: error %q does not say unknown column", dialect, kind, err)
			}
		}
	}
}

// ---- 3. dangling FK: the relationship is dropped from the model but reported
// on the open response, so the user learns why an edge is missing. ----

func TestDanglingFKWarnsStrictOpen(t *testing.T) {
	sql := "CREATE TABLE `a` (\n  `id` INT,\n" +
		"  CONSTRAINT `fk_a_id` FOREIGN KEY (`id`) REFERENCES `gone` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB;\n"
	s, warnings, err := ParseDDLWithWarnings(sql)
	if err != nil {
		t.Fatalf("strict open must load, got: %v", err)
	}
	if s.Tables[0].Columns[0].Ref != nil {
		t.Error("dangling ref must be dropped from the model")
	}
	if len(warnings) == 0 {
		t.Fatal("dangling FK dropped with no warning")
	}
	found := false
	for _, w := range warnings {
		if strings.Contains(w, "gone") || strings.Contains(w, "unknown table") {
			found = true
		}
	}
	if !found {
		t.Errorf("warning does not name the missing parent: %v", warnings)
	}
}

func TestDanglingFKWarnsImportOpen(t *testing.T) {
	// foreign-shaped DDL takes the lenient path; the drop must still be reported
	sql := "CREATE TABLE a (\n  id INT,\n  CONSTRAINT fk FOREIGN KEY (id) REFERENCES gone (id) ON DELETE CASCADE\n);\n"
	s, warnings, err := ParseImport(sql)
	if err != nil {
		t.Fatalf("import must load, got: %v", err)
	}
	if s.Tables[0].Columns[0].Ref != nil {
		t.Error("dangling ref must be dropped from the model")
	}
	if len(warnings) == 0 {
		t.Fatal("import dropped the FK with no warning")
	}
}

// The open-file HTTP path surfaces the warning alongside the schema.
func TestDanglingFKWarningReachesOpenResponse(t *testing.T) {
	dir := t.TempDir()
	sql := "CREATE TABLE `a` (\n  `id` INT,\n" +
		"  CONSTRAINT `fk_a_id` FOREIGN KEY (`id`) REFERENCES `gone` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB;\n"
	if err := os.WriteFile(filepath.Join(dir, "dangle.sql"), []byte(sql), 0o644); err != nil {
		t.Fatal(err)
	}
	rec := do(t, handleFiles(dir), "GET", "/api/files/dangle.sql", nil)
	if rec.Code != 200 {
		t.Fatalf("open: %d %s", rec.Code, rec.Body)
	}
	if !strings.Contains(rec.Body.String(), `"warnings"`) {
		t.Errorf("open response carries no warnings: %s", rec.Body)
	}
}

// ---- 4. GenInserts fail-closed ----
//
// GenInsertsFor runs every value through validateOutput and returns the error
// instead of unchecked text. The gate is reachable only by a value that passes
// input validation yet trips the output scan — with the current allowlists no
// such value exists (identifiers reject `;`/controls up front), so the honest
// pin is: every representable column still emits, and the gate function itself
// rejects a hostile line. If a future type/default slips past Validate, this
// documents where it must be caught.
func TestGenInsertsFailClosedGate(t *testing.T) {
	s := &Schema{Tables: []Table{{ID: "t1", Name: "t", Columns: []Col{
		{Name: "id", Type: "INT", Pk: true},
		{Name: "note", Type: "VARCHAR(10)"},
	}}}}
	out, err := s.GenInserts()
	if err != nil {
		t.Fatalf("valid schema must emit inserts: %v", err)
	}
	if !strings.Contains(out, "INSERT INTO `t`") {
		t.Errorf("inserts missing table:\n%s", out)
	}
	// the gate the inserts path shares with DDL trips on an escaped value
	if err := validateOutput("INSERT INTO `t` (`a`) VALUES ('x'); DROP TABLE t; --\n"); err == nil {
		t.Error("validateOutput accepted an embedded separator the inserts path relies on it to catch")
	}
}

// ---- 5. type-arg comment + unbalanced paren: rejected by Validate early ----

func TestTypeArgCommentRejectedEarly(t *testing.T) {
	s := &Schema{Tables: []Table{{ID: "t1", Name: "t", Columns: []Col{
		{Name: "a", Type: "VARCHAR(1--2)"},
	}}}}
	if err := s.Validate(); err == nil {
		t.Fatal("VARCHAR(1--2) accepted by Validate")
	}
	// "early" means the field validator, not the last-gate output scan: the
	// error names the type, and GenSQL refuses too rather than emitting.
	if _, err := s.GenSQL(); err == nil {
		t.Error("GenSQL emitted a type Validate rejects")
	}
}

func TestUnbalancedParenTypeRejected(t *testing.T) {
	for _, ty := range []string{"X((", "VARCHAR(10", "INT)"} {
		s := &Schema{Tables: []Table{{ID: "t1", Name: "t", Columns: []Col{
			{Name: "a", Type: ty},
		}}}}
		if err := s.Validate(); err == nil {
			t.Errorf("type %q accepted by Validate", ty)
		}
		if _, err := s.GenSQL(); err == nil {
			t.Errorf("GenSQL emitted unbalanced type %q", ty)
		}
	}
}

// ---- 6. ghost composite index refused by validateShape ----

func TestGhostCompositeIndexRejected(t *testing.T) {
	s := &Schema{Tables: []Table{{ID: "t1", Name: "t", Columns: []Col{
		{Name: "a", Type: "INT"}, {Name: "b", Type: "INT"},
	}, Indexes: []Index{{Cols: []string{"a", "ghost"}}}}}}
	err := s.Validate()
	if err == nil {
		t.Fatal("composite index over a ghost column accepted")
	}
	if !strings.Contains(err.Error(), "no such column") {
		t.Errorf("error does not name the missing column: %v", err)
	}
	if _, gerr := s.GenSQL(); gerr == nil {
		t.Error("GenSQL emitted a composite index Validate rejects")
	}
}

// ---- 7. size cap: files over 8 MiB are refused with 413, not loaded ----

func TestSizeCapOpenAndCopy(t *testing.T) {
	dir := t.TempDir()
	h := handleFiles(dir)

	// seed a small real file for the copy source
	rec := do(t, h, "PUT", "/api/files/small.sql", jsonBody(sampleSchema()))
	if rec.Code != 204 {
		t.Fatalf("seed: %d %s", rec.Code, rec.Body)
	}
	// grow it past the cap on disk (the stat check must fire before any read)
	big := append([]byte(mustGenSQL(sampleSchema())), make([]byte, maxOpenFile)...)
	if err := os.WriteFile(filepath.Join(dir, "small.sql"), big, 0o644); err != nil {
		t.Fatal(err)
	}

	rec = do(t, h, "GET", "/api/files/small.sql", nil)
	if rec.Code != http.StatusRequestEntityTooLarge {
		t.Errorf("open oversized: %d, want 413", rec.Code)
	}

	rec = do(t, h, "POST", "/api/files/copy", jsonBody(map[string]string{"from": "small.sql", "to": "big-copy.sql"}))
	if rec.Code != http.StatusRequestEntityTooLarge {
		t.Errorf("copy oversized: %d, want 413", rec.Code)
	}
	if _, err := os.Stat(filepath.Join(dir, "big-copy.sql")); err == nil {
		t.Error("oversized copy left a file behind")
	}
}

// ---- 8. unknown trailing referential action is reported, not defaulted ----

func TestUnknownReferentialActionReported(t *testing.T) {
	// user-visible: importing a dump with a misspelled action keeps CASCADE
	// but tells the user the file said something unrecognized
	var loss importLoss
	del, upd := impActions("ON DELETE CASCDE", &loss)
	if del != "CASCADE" {
		t.Errorf("ON DELETE default changed: %q", del)
	}
	if upd != "" {
		t.Errorf("ON UPDATE should stay omitted: %q", upd)
	}
	if len(loss.result()) == 0 {
		t.Error("misspelled action silently defaulted with no loss recorded")
	} else if !strings.Contains(strings.Join(loss.result(), "\n"), "unrecognized") {
		t.Errorf("loss does not say unrecognized: %v", loss.result())
	}

	// end to end through the import: the schema loads AND the warning rides along
	s, warnings, err := ParseImport("CREATE TABLE a (\n  id INT,\n  pid INT REFERENCES p(id) ON DELETE CASCDE\n);\nCREATE TABLE p (\n  id INT PRIMARY KEY\n);\n")
	if err != nil {
		t.Fatalf("import: %v", err)
	}
	_ = s
	found := false
	for _, w := range warnings {
		if strings.Contains(w, "unrecognized") {
			found = true
		}
	}
	if !found {
		t.Errorf("import warnings missing the action loss: %v", warnings)
	}
}

// ---- 9. impNoise word boundary: a table named BEGINNER must not vanish ----

func TestImpNoiseWordBoundary(t *testing.T) {
	if impNoise("BEGINNER") {
		t.Error("BEGINNER treated as noise")
	}
	if impNoise("COMMITTED") {
		t.Error("COMMITTED treated as noise")
	}
	// the real directives are still skipped
	for _, line := range []string{"BEGIN", "BEGIN;", "COMMIT", "COMMIT;"} {
		if !impNoise(line) {
			t.Errorf("%q should be noise", line)
		}
	}
	// user-visible: a dump creating BEGINNER opens with that table present
	s, _, err := ParseImport("CREATE TABLE BEGINNER (\n  id INT PRIMARY KEY\n);\n")
	if err != nil {
		t.Fatalf("import: %v", err)
	}
	if len(s.Tables) != 1 || s.Tables[0].Name != "BEGINNER" {
		t.Errorf("BEGINNER table lost on import: %+v", s.Tables)
	}
}

// ---- 10. GenSQL unknown dialect errors, never silently emits mysql ----

func TestGenSQLUnknownDialectErrors(t *testing.T) {
	s := &Schema{Dialect: "oracle", Tables: []Table{{ID: "t1", Name: "t", Columns: []Col{
		{Name: "id", Type: "INT"},
	}}}}
	_, err := s.GenSQL()
	if err == nil {
		t.Fatal("GenSQL accepted an unknown dialect")
	}
	if !strings.Contains(err.Error(), "unknown dialect") {
		t.Errorf("error does not name the problem: %v", err)
	}
	// empty (every pre-dialect file) still means mysql
	s.Dialect = ""
	if _, err := s.GenSQL(); err != nil {
		t.Errorf("empty dialect rejected: %v", err)
	}
}

// ---- 11. handleFileOp/saveFile uncovered error branches ----

func TestFileOpBadJSONBody(t *testing.T) {
	h := handleFiles(t.TempDir())
	rec := do(t, h, "POST", "/api/files/rename", strings.NewReader(`{oops`))
	if rec.Code != http.StatusBadRequest {
		t.Errorf("rename bad json: %d, want 400", rec.Code)
	}
	rec = do(t, h, "POST", "/api/files/copy", strings.NewReader(`{oops`))
	if rec.Code != http.StatusBadRequest {
		t.Errorf("copy bad json: %d, want 400", rec.Code)
	}
}

func TestFileOpMissingSourceStoreGone(t *testing.T) {
	// renaming out of a store dir that vanished is a 400 (unresolvable),
	// not a panic and not a 500
	dir := t.TempDir()
	h := handleFiles(dir)
	if err := os.RemoveAll(dir); err != nil {
		t.Fatal(err)
	}
	rec := do(t, h, "POST", "/api/files/rename", jsonBody(map[string]string{"from": "a.sql", "to": "b.sql"}))
	if rec.Code != http.StatusBadRequest {
		t.Errorf("rename with missing store: %d, want 400", rec.Code)
	}
}

func TestSaveFileOversizedBody(t *testing.T) {
	// a PUT body over the 1 MiB cap is refused before parsing
	h := handleFiles(t.TempDir())
	big := strings.NewReader(strings.Repeat("x", (1<<20)+1))
	rec := do(t, h, "PUT", "/api/files/big.sql", big)
	if rec.Code != http.StatusBadRequest {
		t.Errorf("oversized save: %d, want 400", rec.Code)
	}
}
