// erd.js — schema model + MySQL DDL generate/parse + auto-layout.
// The emitted .sql is the source of truth; parser only reads what generate() writes.
import { HDR_H, ROW_H } from "./geometry.js";

export const TYPES = [
  "INT", "BIGINT", "SMALLINT", "TINYINT", "DECIMAL", "VARCHAR", "TEXT",
  "BOOLEAN", "DATE", "DATETIME", "TIMESTAMP", "JSON", "ENUM",
];
export const DEFAULT_TYPE = {
  DECIMAL: "DECIMAL(10,2)", VARCHAR: "VARCHAR(255)",
};
export const baseType = (t) => t.split("(")[0];
const INT_RE = /^(INT|BIGINT|SMALLINT|TINYINT)/;

export let nextTableId = 1;
export let nextColId = 1;
export function newTable(name) {
  return {
    id: "t" + nextTableId++, name, x: 0, y: 0,
    columns: [{ id: "c" + nextColId++, name: "id", type: "INT", pk: true, nn: true, ai: true, ux: false, ix: false, comment: "", ref: null }],
  };
}
export function newColumn() {
  return { id: "c" + nextColId++, name: "column", type: "VARCHAR(255)", pk: false, nn: false, ai: false, ux: false, ix: false, comment: "", ref: null };
}
export function cloneTable(t) {
  return {
    ...t,
    id: "t" + nextTableId++,
    columns: t.columns.map((c) => ({ ...c, id: "c" + nextColId++, ref: c.ref ? { ...c.ref } : null })),
  };
}
export function bumpCounters(schema) {
  for (const t of schema.tables) {
    nextTableId = Math.max(nextTableId, +t.id.slice(1) + 1);
    for (const c of t.columns) nextColId = Math.max(nextColId, +c.id.slice(1) + 1);
  }
}

export const isInt = (t) => INT_RE.test(baseType(t));

// lint: FK base-type vs referenced PK base-type mismatch; FK onto composite PK.
export function lint(schema) {
  return schema.tables.flatMap((t) =>
    t.columns.filter((c) => c.ref).flatMap((c) => {
      const p = schema.tables.find((x) => x.id === c.ref.tableId);
      if (!p) return [];
      const pks = p.columns.filter((x) => x.pk);
      if (pks.length > 1) return [`${t.name}.${c.name} → ${p.name} has composite PK; single-col FK is invalid DDL`];
      const pk = pks[0] ?? p.columns[0];
      return pk && baseType(pk.type) !== baseType(c.type)
        ? [`${t.name}.${c.name} ${baseType(c.type)} vs ${p.name}.${pk.name} ${baseType(pk.type)}`]
        : [];
    })
  );
}

export const quoteIdent = (n) => "`" + n.replace(/`/g, "``") + "`";
const sqlString = (s) => "'" + s.replace(/'/g, "''") + "'";

function ddlType(c) {
  const open = c.type.indexOf("(");
  const base = (open < 0 ? c.type : c.type.slice(0, open)).toUpperCase();
  if (c.ai && INT_RE.test(base)) return base;
  return open < 0 ? base : base + c.type.slice(open);
}

export function generate(schema) {
  const out = ["-- Generated by erd-creator"];
  for (const t of schema.tables) {
    if (!t.columns.length) continue; // empty table → invalid DDL; skip (UI also guards)
    const lines = [];
    for (const c of t.columns) {
      let s = `  ${quoteIdent(c.name)} ${ddlType(c)}`;
      if (c.nn || c.pk) s += " NOT NULL";
      if (c.ai && INT_RE.test(c.type)) s += " AUTO_INCREMENT";
      if (c.ux) s += " UNIQUE";
      if (c.comment) s += ` COMMENT ${sqlString(c.comment)}`;
      lines.push(s);
    }
    const pks = t.columns.filter((c) => c.pk).map((c) => quoteIdent(c.name));
    if (pks.length) lines.push(`  PRIMARY KEY (${pks.join(", ")})`);
    for (const c of t.columns) if (c.ix) lines.push(`  KEY ${quoteIdent(`idx_${t.name}_${c.name}`)} (${quoteIdent(c.name)})`);
    for (const c of t.columns) {
      if (!c.ref) continue;
      const rt = schema.tables.find((x) => x.id === c.ref.tableId);
      if (!rt) continue;
      const rp = rt.columns.filter((x) => x.pk);
      if (rp.length > 1) continue; // composite PK parent → invalid single-col FK; lint warns
      const rpk = rp[0] ?? rt.columns[0];
      lines.push(
        `  CONSTRAINT ${quoteIdent(`fk_${t.name}_${c.name}`)} FOREIGN KEY (${quoteIdent(c.name)}) ` +
        `REFERENCES ${quoteIdent(rt.name)} (${quoteIdent(rpk.name)}) ON DELETE ${c.ref.action || "CASCADE"}`
      );
    }
    out.push(`\nCREATE TABLE ${quoteIdent(t.name)} (\n${lines.join(",\n")}\n) ENGINE=InnoDB;`);
  }
  return out.join("\n") + "\n";
}

export function generateInserts(schema) {
  const out = ["-- Seed row templates (edit values, remove per table as needed)"];
  for (const t of schema.tables) {
    if (!t.columns.length) continue; // empty table → invalid INSERT; skip
    const vals = t.columns.map((c) => {
      const b = baseType(c.type);
      if (c.ai) return "NULL";
      if (INT_RE.test(b)) return "0";
      if (b === "DECIMAL" || b === "BOOLEAN") return b === "BOOLEAN" ? "FALSE" : "0.00";
      if (b === "DATE") return "'2026-01-01'";
      if (b === "DATETIME" || b === "TIMESTAMP") return "NOW()";
      if (b === "JSON") return "'{}'";
      return "''";
    });
    out.push(`INSERT INTO ${quoteIdent(t.name)} (${t.columns.map((c) => quoteIdent(c.name)).join(", ")}) VALUES (${vals.join(", ")});`);
  }
  return out.join("\n") + "\n";
}

// parse(sql) -> schema. Line-based; understands only the subset generate()/generateInserts() emit.
const KEYWORD_RE = /^(PRIMARY KEY|UNIQUE KEY|CONSTRAINT|KEY|INDEX|FOREIGN KEY)\b/i;
export function parse(sql) {
  const schema = { tables: [], _byName: {} };
  let cur = null;
  sql.split("\n").forEach((raw, i) => {
    const line = raw.trim();
    if (!line || line.startsWith("--") || /^INSERT INTO/i.test(line)) return;
    let m = line.match(/^CREATE TABLE (\S+) \($/i);
    if (m) {
      const name = unquote(m[1]);
      if (schema._byName[name]) throw new Error(`line ${i + 1}: duplicate table "${name}"`);
      cur = { id: "t" + nextTableId++, name, x: 0, y: 0, columns: [], _pending: [] };
      schema.tables.push(cur);
      schema._byName[name] = cur;
      return;
    }
    if (/^\) ENGINE=InnoDB;?$/i.test(line)) { cur = null; return; }
    if (!cur) throw new Error(`line ${i + 1}: not inside CREATE TABLE: ${line}`);
    const body = line.replace(/,$/, "");
    if ((m = body.match(/^PRIMARY KEY \((.+)\)$/i))) {
      mark(cur, m[1]); return;
    }
    if ((m = body.match(/^UNIQUE KEY (\S+) \((.+)\)$/i))) {
      const c = cur.columns.find((x) => x.name === unquote(m[2]));
      if (c) c.ux = true;
      return;
    }
    if (/^(KEY|INDEX) (\S+) \(.+\)$/i.test(body)) {
      const cn = body.slice(body.indexOf("(") + 1, body.lastIndexOf(")"));
      const c = cur.columns.find((x) => x.name === unquote(cn));
      if (c) c.ix = true;
      return;
    }
    if ((m = body.match(/^CONSTRAINT \S+ FOREIGN KEY \((\S+)\) REFERENCES (\S+) \((\S+)\)( ON DELETE (SET NULL|SET DEFAULT|NO ACTION|RESTRICT|CASCADE))?$/i))) {
      cur._pending.push({ col: unquote(m[1]), table: unquote(m[2]), action: m[5] || "CASCADE" });
      return;
    }
    if (KEYWORD_RE.test(body)) throw new Error(`line ${i + 1}: unsupported clause: ${line}`);
    m = body.match(/^(\S+) ([A-Z]+(?:\([^)]*\))?)( NOT NULL)?( AUTO_INCREMENT)?( UNIQUE)?(?: COMMENT '((?:[^']|'')*)')?$/i);
    if (!m) throw new Error(`line ${i + 1}: cannot parse: ${line}`);
    const c = newColumn();
    c.name = unquote(m[1]);
    c.type = m[2].replace(/^([A-Za-z]+)(\(.*)?$/, (_, b, rest) => b.toUpperCase() + (rest ?? ""));
    c.nn = !!m[3]; c.ai = !!m[4]; c.ux = !!m[5];
    c.comment = m[6] ? m[6].replace(/''/g, "'") : "";
    cur.columns.push(c);
  });
  for (const t of schema.tables) {
    for (const p of t._pending) {
      const c = t.columns.find((x) => x.name === p.col);
      const rt = schema._byName[p.table];
      if (c && rt) c.ref = { tableId: rt.id, action: p.action };
    }
    delete t._pending;
  }
  delete schema._byName;
  if (!schema.tables.length) throw new Error("no CREATE TABLE found");
  bumpCounters(schema);
  return schema;
}

function mark(cur, list) {
  for (const n of list.split(",")) {
    const c = cur.columns.find((x) => x.name === unquote(n.trim()));
    if (c) c.pk = true;
  }
}

// Auto-layout: layered by FK depth, referenced tables leftmost. No coords stored.
export function layout(schema) {
  const byId = Object.fromEntries(schema.tables.map((t) => [t.id, t]));
  const depth = new Map();
  const d = (id, seen) => {
    if (depth.has(id)) return depth.get(id);
    if (seen.has(id)) return 0; // cycle guard
    seen.add(id);
    const refs = byId[id].columns.filter((c) => c.ref && byId[c.ref.tableId]).map((c) => d(c.ref.tableId, seen));
    const val = refs.length ? Math.max(...refs) + 1 : 0;
    depth.set(id, val);
    return val;
  };
  for (const t of schema.tables) d(t.id, new Set());
  const cols = new Map();
  for (const t of schema.tables) {
    const layer = depth.get(t.id);
    if (!cols.has(layer)) cols.set(layer, []);
    cols.get(layer).push(t);
  }
  const COL_W = 340, GAP = 12;
  for (const [layer, ts] of cols) {
    let y = 40;
    for (const t of ts) {
      t.x = 40 + layer * COL_W;
      t.y = y;
      y += HDR_H + t.columns.length * ROW_H + 24 + GAP; // box height from geometry.js
    }
  }
}

function unquote(s) {
  s = s.trim();
  return s.startsWith("`") ? s.slice(1, -1).replace(/``/g, "`") : s;
}
