// HTTP contract of grpc the frontend relies on — request fixture only, no browser.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { expect, test } from "@playwright/test";

const schema = {
	tables: [
		{
			id: "t1",
			name: "users",
			columns: [
				{
					name: "id",
					type: "INT",
					pk: true,
					nn: true,
					ai: true,
					ux: false,
					ix: false,
					comment: "",
					ref: null,
				},
			],
		},
	],
};

test("lint + inserts + export accept the wire schema", async ({ request }) => {
	expect(
		await (await request.post("/api/lint", { data: { schema } })).json(),
	).toEqual([]);
	expect(
		await (await request.post("/api/inserts", { data: { schema } })).text(),
	).toContain("INSERT INTO `users`");
	expect(
		await (
			await request.post("/export", { data: { dialect: "postgres", schema } })
		).text(),
	).toContain('CREATE TABLE "users"');
});

test("export rejects unknown dialect with 400", async ({ request }) => {
	expect(
		(
			await request.post("/export", { data: { dialect: "oracle", schema } })
		).status(),
	).toBe(400);
});

test("files: traversal + bad name rejected, save/read/delete round-trip", async ({
	request,
}) => {
	expect(
		(
			await request.put("/api/files/..%2Fescape.sql", { data: schema })
		).status(),
	).toBe(400);
	expect(
		(await request.put("/api/files/nope.txt", { data: schema })).status(),
	).toBe(400);

	expect(
		(await request.put("/api/files/api.spec.sql", { data: schema })).status(),
	).toBe(204);
	const got = await (await request.get("/api/files/api.spec.sql")).json();
	expect(got.tables[0].name).toBe("users");
	expect((await request.delete("/api/files/api.spec.sql")).status()).toBe(204);
	expect((await request.get("/api/files/api.spec.sql")).status()).toBe(404);
});

test("open: schema fields at root + warnings alongside when import skips", async ({
	request,
}) => {
	expect(
		(await request.put("/api/files/api.warn.sql", { data: schema })).status(),
	).toBe(204);
	const got = await (await request.get("/api/files/api.warn.sql")).json();
	expect(got.tables[0].name).toBe("users");
	expect(got.warnings ?? []).toEqual([]);
	expect((await request.delete("/api/files/api.warn.sql")).status()).toBe(204);
});

test("open of a missing file → 404 with the name in the message", async ({
	request,
}) => {
	// the open endpoint answers 404 for a name that was never saved, and says
	// which name — the UI surfaces the error with the file, so the message
	// must carry it
	const res = await request.get("/api/files/ghost.sql");
	expect(res.status()).toBe(404);
	expect(await res.text()).toContain("ghost.sql");
});

test("export dialects produce expected headers", async ({ request }) => {
	const cases = [
		["mysql", "MySQL"],
		["mariadb", "MariaDB"],
		["postgres", "PostgreSQL"],
		["sqlite", "SQLite"],
	];
	for (const [dialect, header] of cases) {
		const body = await (
			await request.post("/export", { data: { dialect, schema } })
		).text();
		expect(body).toContain(`Generated by erd-creator (${header})`);
		expect(body).toContain("CREATE TABLE");
	}
});

test("mariadb schema saves and reopens as mariadb, not mysql", async ({
	request,
}) => {
	const md = { dialect: "mariadb", tables: schema.tables };
	const put = await request.put("/api/files/md.sql", { data: md });
	expect(put.status()).toBe(204);

	// reopening reports mariadb — this used to come back as mysql, because the
	// dialect was collapsed during normalization
	const reopened = await (await request.get("/api/files/md.sql")).json();
	expect(reopened.dialect).toBe("mariadb");
	expect(reopened.tables[0].name).toBe("users");

	// and it is exportable to every other dialect
	for (const dialect of ["mysql", "postgres", "sqlite"]) {
		const body = await (
			await request.post("/export", {
				data: { dialect, schema: reopened },
			})
		).text();
		expect(body).toContain("CREATE TABLE");
		expect(body).not.toContain("JSONB");
	}
});

test("sqlite schema saves and reopens as sqlite", async ({ request }) => {
	// sqlite used to be refused here (no parser). It now round-trips, so the
	// same guarantee mariadb has must hold: the file keeps its own dialect
	// rather than silently coming back as mysql.
	const sq = { dialect: "sqlite", tables: schema.tables };
	const put = await request.put("/api/files/sq.sql", { data: sq });
	expect(put.status()).toBe(204);

	const reopened = await (await request.get("/api/files/sq.sql")).json();
	expect(reopened.dialect).toBe("sqlite");
	expect(reopened.tables[0].name).toBe("users");

	// the saved bytes are sqlite DDL, not MySQL with a different header. There
	// is no raw-file endpoint (GET parses), so read what the server wrote —
	// playwright runs the server with -dir schemas-e2e.
	const raw = readFileSync(
		fileURLToPath(new URL("../../schemas-e2e/sq.sql", import.meta.url)),
		"utf8",
	);
	expect(raw).toContain("Generated by erd-creator (SQLite)");
	expect(raw).toContain("INTEGER PRIMARY KEY");
	expect(raw).not.toContain("AUTO_INCREMENT");

	// and it stays exportable to every other dialect
	for (const dialect of ["mysql", "mariadb", "postgres"]) {
		const body = await (
			await request.post("/export", { data: { dialect, schema: reopened } })
		).text();
		expect(body).toContain("CREATE TABLE");
	}
});

test("sqlite save/reopen preserves enum values and comments", async ({
	request,
}) => {
	// ENUM has no sqlite type, so it becomes TEXT + CHECK. The values must
	// survive the round-trip or reopening would silently change the schema.
	const sq = {
		dialect: "sqlite",
		tables: [
			{
				id: "t1",
				name: "acct",
				columns: [
					{ name: "id", type: "INT", pk: true, ai: true, comment: "pk" },
					{ name: "status", type: "ENUM('active','banned')" },
				],
			},
		],
	};
	expect(
		(await request.put("/api/files/acct.sql", { data: sq })).status(),
	).toBe(204);
	const reopened = await (await request.get("/api/files/acct.sql")).json();
	const cols = reopened.tables[0].columns;
	expect(cols.find((c) => c.name === "status").type).toBe(
		"ENUM('active','banned')",
	);
	// the comment must not pick up the comma that separates column entries
	expect(cols.find((c) => c.name === "id").comment).toBe("pk");
});

test("sqlite types mode is recorded and survives a reopen", async ({
	request,
}) => {
	// The mode changes the saved bytes, so it has to be recoverable from the
	// file. Otherwise a portable file reopens as native and the UI claims a
	// convention the file does not follow.
	const base = {
		dialect: "sqlite",
		tables: [
			{
				id: "t1",
				name: "ev",
				columns: [
					{ name: "id", type: "INT", pk: true, ai: true },
					{ name: "flag", type: "BOOLEAN" },
					{ name: "when", type: "DATETIME" },
				],
			},
		],
	};

	// native is the default: the header is unchanged and the type is kept
	const nat = await request.put("/api/files/nat.sql", { data: base });
	expect(nat.status()).toBe(204);
	const natRaw = readFileSync(
		fileURLToPath(new URL("../../schemas-e2e/nat.sql", import.meta.url)),
		"utf8",
	);
	expect(natRaw.split("\n")[0]).toBe("-- Generated by erd-creator (SQLite)");
	expect(natRaw).toContain("`flag` BOOLEAN");
	const natBack = await (await request.get("/api/files/nat.sql")).json();
	expect(natBack.sqliteTypes).toBe("native");
	expect(natBack.tables[0].columns.find((c) => c.name === "flag").type).toBe(
		"BOOLEAN",
	);

	// portable rewrites to the storage class and records the mode
	const port = await request.put("/api/files/port.sql", {
		data: { ...base, sqliteTypes: "portable" },
	});
	expect(port.status()).toBe(204);
	const portRaw = readFileSync(
		fileURLToPath(new URL("../../schemas-e2e/port.sql", import.meta.url)),
		"utf8",
	);
	expect(portRaw.split("\n")[0]).toContain("types: portable");
	expect(portRaw).toContain("`flag` INTEGER");
	const portBack = await (await request.get("/api/files/port.sql")).json();
	expect(portBack.sqliteTypes).toBe("portable");
	// documented loss: the model type is gone after a reopen
	expect(portBack.tables[0].columns.find((c) => c.name === "flag").type).toBe(
		"INTEGER",
	);

	// the mode must not leak into the other dialects
	const asMysql = await (
		await request.post("/export", {
			data: { dialect: "mysql", schema: { ...base, sqliteTypes: "portable" } },
		})
	).text();
	expect(asMysql).toContain("`flag` BOOLEAN");
	expect(asMysql).not.toContain("types:");
});

test("lint surfaces FK type mismatch (INT vs TEXT)", async ({ request }) => {
	const bad = {
		tables: [
			{
				id: "t1",
				name: "users",
				columns: [
					{
						name: "id",
						type: "INT",
						pk: true,
						nn: true,
						ai: true,
						ux: false,
						ix: false,
						comment: "",
						ref: null,
					},
				],
			},
			{
				id: "t2",
				name: "posts",
				columns: [
					{
						name: "user_id",
						type: "VARCHAR(255)",
						pk: false,
						nn: false,
						ai: false,
						ux: false,
						ix: false,
						comment: "",
						ref: { tableId: "t1", action: "CASCADE" },
					},
				],
			},
		],
	};
	const lint = await (
		await request.post("/api/lint", { data: { schema: bad } })
	).json();
	expect(lint.length).toBeGreaterThan(0);
	expect(lint.join(" ")).toContain("vs");
});

test("inserts: AI → NULL, BOOLEAN → FALSE, default → empty string", async ({
	request,
}) => {
	const s2 = {
		tables: [
			{
				id: "t1",
				name: "events",
				columns: [
					{
						name: "id",
						type: "INT",
						pk: true,
						nn: true,
						ai: true,
						ux: false,
						ix: false,
						comment: "",
						ref: null,
					},
					{
						name: "active",
						type: "BOOLEAN",
						pk: false,
						nn: false,
						ai: false,
						ux: false,
						ix: false,
						comment: "",
						ref: null,
					},
					{
						name: "note",
						type: "VARCHAR(255)",
						pk: false,
						nn: false,
						ai: false,
						ux: false,
						ix: false,
						comment: "",
						ref: null,
					},
				],
			},
		],
	};
	const body = await (
		await request.post("/api/inserts", { data: { schema: s2 } })
	).text();
	expect(body).toContain("NULL");
	expect(body).toContain("FALSE");
	expect(body).toContain("''");
});
