import { chromium } from "@playwright/test";
const b = await chromium.launch();
const p = await b.newPage();
p.on("console", (m) => console.log("CONSOLE", m.type(), m.text()));
p.on("pageerror", (e) => console.log("PAGEERROR", e.message));
await p.goto("http://127.0.0.1:8731/");
await p.waitForTimeout(2500);
console.log("tname count:", await p.locator(".tname").count());
console.log("title:", await p.title());
await b.close();
